- po/opencpn_nl_NL.po
The translation for two sentences in options.cpp had the word 'port' translated with the Dutch word for 'harbour'. It should be 'poort' in this sentences.
> opencpn_nl_NL.po: translation of 'port' (haven -> poort)

- src/chart1.cpp
- src/options.cpp
The first time the options window is opened, the "General" tab is selected,
the second time, the "Units" tab is selected.  This change ensures that
the behavior is consistent and less confusing.
> Give more consistent behavior for options dialog in gtk

- src/s52plib.cpp
- src/s57chart.cpp
This should fix FS #1704. I also wonder whether attribute HEIGHT should be converted to feet or not.
VERCLL is not a valid attribute at least not that I can find. And VERCOP was not being converted at all which leads to confusion on charts. OpenCPN has been displaying vertical clearance open and closed in meters instead of the requested units. If fathoms is the requested depth units these few attributes should remain as feet.
> Corrected typo VERCLL and added VERCOP to feet conversion.

- include/triangulate.h
The inline function semantics changes in GCC version 5, leading in linking problems on Fedora 22 (http://www.gnu.org/software/gcc/gcc-5/porting_to.html)
> Fix linking with GCC5

- plugins/grib_pi/src/GribUIDialog.cpp
- src/printtable.cpp
This patch makes building with VS2013 possible.
I took some notes regarding the use of this toolchain at https://github.com/nohal/OpenCPN/wiki/Building-using-Visual-Studio-2013
Surprisingly enough, the resulting binary (while using wx2.8) is compatible with the existing plugin DLLs built with VS2010 so if we decide to switch the default Windows toolchain, the transition seems transparent until we move to wx3.
> Fix build with Visual Studio 2013

- include/ocpn_plugin.h
- include/pluginmanager.h
- include/toolbar.h
- src/chcanv.cpp
- src/options.cpp
- src/pluginmanager.cpp
- src/routeprop.cpp
- src/toolbar.cpp
I needed these functions for one of my plugins, and also added support to install/upgrade plugins without restarting opencpn.
> Plugin 1.13 

- include/chcanv.h
- include/ocpn_plugin.h
- src/pluginmanager.cpp
This change is to allow scrolling when creating a boundary. It moves the CheckEdgePan from private to public in the chcanv class and provides an external CheckEdgePan_PlugIn API call.
> Make CheckEdgePan avaialble to plugins

- src/chart1.cpp
- src/options.cpp
- src/toolbar.cpp
enable the transparent toolbar for xfce4 window manager.. hopefully some developers can test this on other window managers enable support.
Eventually we should just render the toolbar using opengl and it will work everywhere on all operating systems
> Transparent toolbar opengl

- src/chart1.cpp
gchar is `typedef char   gchar;` /usr/include/glib-2.0/glib/gtypes.h, but gtypes.h is not used and this also is currently the only gchar in the source code.  So instead simply use a plain char.
> use char instead of gchar

- src/chart1.cpp
`pOLE` is set in the loop, but then tested outside of the loop.  This works of the loop terminates early because then `pOLE` really points to the correct entry.  However, if the list does not contain an entry with the required name, pOLE simply points to the last element of the list.
Solution is to simply reset pOLE to null inside the list.
> Avoid mis-use of pointer

- src/OCPNPlatform.cpp
Create OCPN's config files opencpn subdirectory of ~/Library/Preferences. Leave logfile in ~/Library/Logs to coexist with Xcode, etc.
> On OSX put config files in opencpn subdirectory

- include/chartimg.h
- include/glTexCache.h
- src/chartdbs.cpp
- src/chartimg.cpp
- src/glTexCache.cpp
Hi,
replace wxFile... with wxFFile...
- It speeds up a little ocpn start and chart rendering.
- It speeds up a lot, at least for me on linux, opengl cache building:
nearly twice as fast on a 2 cores cpu when the cache is on a normal partition.
5 time faster when files and the cache are stored on an encrypted partition.
Regards
Didier
> use Buffered io for cache and raster charts

- include/ocpn_plugin.h
- include/options.h
- src/chart1.cpp
- src/options.cpp
- src/pluginmanager.cpp
The chart downloader plugin will be able to directly add chart dirs and triger DB updates uppon chart downloads.
For the purposes of the chart downloader we can rely on the toolbox being shown. If we would like to allow the DB manipulations even for plugins not integrating into the toolbox, we would have to implement the codepath for g_options == NULL
> Enhance the plugin API to allow chart DB manipulation

- src/chart1.cpp
Hi,
Most of them are used by AIS and I haven't tested it very well.
There's still two missing colors:
CHDRD in chcanv.cpp with no definition in chartsymbols
UBLK in ais.cpp, typo for UBLCK?
regards
Didier
> add missing colors used before chartsymbols is loaded

- src/chart1.cpp
- src/statwin.cpp
Hi,
Hide the chart info window, thumbnail and quilt highlight on:
- piano change, there's no guarantee that the chart under the mouse pointer hasn't changed. 
It could be smarter though.
- on color scheme change, the chart info text color was wrong and the thumbnail was replaced by a white rectangle. I tried to update them but gave up it works with wx3 but with 2.8 the main canvas wasn't updated until the mouse leaves the piano.
Regards
Didier
> reset rollover on piano or color scheme change

- src/chartdb.cpp
Hi,
Code was leaking a CacheEntry  on piano rollover for every vector chart not in the cache.
This change always add the new entry to the cache but it has to change IsChartInCache method.
Regards,
Didier
> Cache entry leak

- CMakeLists.txt
Debug no -O flag generated
Release -O3
RelWithDebInfo -O2
MinSizeRel -O2
Change only for Linux (i.e. NOT WIN32 and NOT APPLE )
> Let CMAKE choose optimistion based on setting of CMAKE_BUILD_TYPE

- src/cm93.cpp
Hi,
The last one at least for displaying charts.
The few remaining leaks found with valgrind are in Init functions and hopefully are one-off and not growing.
There's still issues with memory fragmentations though.
Regards
Didier
BTW I'd like to access a recent coverty report, is it possible?
Thanks.
> small leak in cm93

- include/pluginmanager.h
- src/options.cpp
- src/pluginmanager.cpp
Mainly usable to set the order of overlay rendering, where the overlays provided by plugins higher on the list in the Toolbox are rendered over the overlays provided by those lower.
The order is saved in the config file and persistent across sessions. Newly installed plugins are placed at the end of the list in loading order.
> Implement configurable plugin order.

- src/cm93.cpp
Hi,
Yet a valgrind corner case with CM93 charts.
Regards
Didier
> cm93, uninitialised value if m_last_vp is not valid

- src/glChartCanvas.cpp
- src/glTexCache.cpp
Hi,
I've been able to trigger this one by displaying a big chart with an empty texture cache and starting a cache rebuild, either the cache is corrupted or texture entries are lost.
Also flush to system after writing the header.
Regards
Didier
> Cache rebuild

- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/GribOverlayFactory.h
- plugins/grib_pi/src/IsoLine.cpp
Hi,
speedup a little bit grib display by:
- computing colors table  to wxColour object only once when creating the factory.
- in extract isoline most values are outside grid cell range so test for this case first, computing all  isolines in one loop should be faster but it's more work.
Regards
Didier
> Grib speedup

- plugins/grib_pi/src/GribOverlayFactory.cpp
If the grib file entries switch from .25 degree data to .5 degree data while particles are displayed, the number of particles are miscalculated and thousands of new particles are created stalling OpenCPN.
> Fix grib particle looping (FS#1794)

- include/glChartCanvas.h
- include/options.h
- src/chart1.cpp
- src/glChartCanvas.cpp
- src/navutil.cpp
- src/options.cpp
This makes it possible to use software opengl at least on linux systems with intel graphics
In the future we can extend this by using glshim to select a software library if available
which will make it possible to use software OpenGL on most supported platforms
> Add option to use software OpenGL (if mesa is available)

- include/chcanv.h
- src/NavObjectCollection.cpp
- src/chcanv.cpp
- src/navutil.cpp
1)  The point to be changed is searched by his GUI instead of his name/position as in certain conditions and mainly when dragging, these parameters have been changed. This ovoids to create some unexpected points. This is the main raison to way points proliferation  after a crash.
2) Do not generate an "updateWaypoint" when dragging a route point.
3) Do not generate an "updateroute" or "updatewaypoint" when only clicking on a route point or a way point without doing anything else or only highlighting in case of touch screen . This ovoids to overload the file with many useless entries.
Nevertheless I am not sure these commits will solve all the problems in all cases. Particularly I faced some randomly cases with W8.1 where the change file was not removed after a crash,  
Jean Pierre
> Improve changes file management  to ovoid points proliferation after crash(#FS1824 -1785)

- include/chartimg.h
- src/chartimg.cpp
This change eliminates the use of the line buffer cache (of palette index)
which as it turns out is actually slower (due to requiring more memory manipulation)
and uses a lot more ram
The performance is anywhere from 15-50% faster and ram usage is greatly reduced
if the cache is disabled (android or low ram systems), the performance improvement
is even more significant
It would be possible to improve the performance further:
1)  Using 32 bit data instead of 24 bit data.  Initial tests show a 15-20% speed up
because 4 bytes is much more efficient to work with than 3 (can use avx and sse instructions)
In opengl mode there is even more improvement because the opengl driver will convert the 24 bit
data into 32 bits in graphics memory anyway.  The 25% more memory used is temporary just for …
> Improve performance of loading raster charts

- src/compass.cpp
Hi,
if it was a true window its parent wouldn't get them.
Fix the issue:
When toggling the course up mode by clicking on the icon the chart is moved to
the cursor position in the right corner, the canvas is reacting to the
left click release event.
Regards.
Didier
> Compass window, don't propagate any mouse event

- src/glTexCache.cpp
Hi, 
My mistake.
in CompressionWorkerPool::OnEvtThread add back missing StartTopJob(),
it was wrongly removed in commit 9909f946199837310154b421bd94d9b388437869,
copy and paste error.
Regards
Didier
> Missing StartTopJob in background compression OnEvtThread

- include/options.h
- src/options.cpp
Another pull request that attempts to clean up the code a bit.
There is nothing fancy here just some whitespace/newline removals etc..
The most interesting changes are the switch from C-Style casting to C++-Style casting (see b47e8e3 and 347bfff), clearing wxMemoryDC, used for native checkboxes in a listctrl, properly (see 961f418) and a pointer fix (see 195e101).
> Scrub options.cpp and options.h

- include/options.h
- src/options.cpp
The code in options.cpp/options.h still needs a lot of work, I'll do what I can in my free time.
So far I have...
... applied the style guide
... applied C++ style casting (see 2c2c49b and 88169ba)
... removed dynamic class macros and the bulk that came with it (see 0a124f4)
... added a base class to mark classes uncopyable (see df6a6d7)
... removed a bit of bulk for differentiating between compact device (see 683a6ba)
... removed global object being passed by value in class methods (see efb220e)
> Polish options.cpp and options.h

- src/cm93.cpp
improve the algorithm for adjusting cm93 detail scale factor to work better at small scale factors
"hidden" islands can appear much sooner (eg: bermuda on cm93)
> improved cm93 detail level

- src/chartdbs.cpp
Hi,
For example if you create a group with only the cm93 directory, when selected this group only display the world chart.
it may have side effect.
Regards
Didier
> on linux c21dbcc94ef78f0ad31c6a5df932920a2ab0a4aa breaks groups with cm93

- include/glTexCache.h
- src/glTexCache.cpp
Hi,
Replace the O(n) texture lookup with an O(1) one.
For a fully populated cache the memory footprint is also smaller, store only 2 integers per entry vs 6 integers.
May need to test if there's a mismatch between process texture size on one stored in cache. 
Regards
Didier
> Texture, use O(1) for searching texture in cache

- plugins/dashboard_pi/src/wind_history.cpp
When I tried to build a fresh clone of this repo, I got a couple of errors like this: 
```
//OpenCPN/plugins/dashboard_pi/src/wind_history.cpp:331:45: error: cannot pass objects of non-trivially-copyable type ‘class wxString’ through ‘...’
label1.Printf(_("--- %s"), m_WindSpeedUnit);
```
Fixed by explicitly converting with `c_str()`.
This file has a lot of inconsistent white space (mixing tabs/spaces, 2/4/6 spaces).  Are you interested in a PR fixing that?
Are you interested in a PR enabling CI (appveyor for windows builds, travis/circleCI for linux builds)?
> Fixes build by explicitly converting to c string

- include/options.h
- src/options.cpp
Dave...
here is my proposal for the whitespace issue (Discussed here: https://github.com/OpenCPN/OpenCPN/pull/386) and a wildly used code style from Google (Defined here: https://google-styleguide.googlecode.com/svn/trunk/cppguide.html)
Using clang-format, all I had to do is (from the base dir):
> clang-format -style=Google -i src/options.cpp include/options.h
I am definitely against defining a code-style of our own, as I've seen projects break up over nonsensical discussions over personal preference. I'd also use a rather popular code-style as they tend to be supported through various IDE plugins, formatting tools, etc..
Greetings,
Mike
> Use clang-format (with Google code-style) to reformat options.cpp/h

- src/pluginmanager.cpp
The zip files downloaded by chartdldr_pi were never removed because the OutputStream had the files open.
> Delete OutputStream in CurlThread

- src/multiplexer.cpp
because some garmin gps discard the first waypoint sent
> Send waypoint message twice without any delay between

- src/chart1.cpp
You can distribute a portable version of OCPN with including maps in a subdir "charts". This is very useful if you use OCPN from a USB pen drive on various computers.
> Add a default path for portable charts.

- src/chart1.cpp
Detects the language of Windows UI.
From MSDN:
`GetUserDefaultUILanguage`: Minimum supported client is Windows 2000 Professional
`GetLocaleInfo`: Minimum supported client is Windows 2000 Professional
> Add UI language detection for Windows on first start.

- .travis.yml
- appveyor.yml
Linux build just took about 13 mins.
You'll have to enable a hook in github/travis to make this work for the OpenCPN/OpenCPN repo.
> CI: travis (linux builds), Appveyor (windows build)

- include/ocpn_plugin.h
Only showed up when the & was removed from GetSingleWaypoint.
I should have got it earlier.
> Duplication in opencpn_plugin.h

- plugins/chartdldr_pi/data/chart_sources.xml
- plugins/chartdldr_pi/src/chartdldr_pi.cpp
- src/OCPNPlatform.cpp
This addresses three separate issues:
On OS X log files for OpenCPN were appearing in the wrong directory. This should now be fixed.
I've added Peruvian RNCs to the chart catalog; this patch also adds them to the list of chart sources.
And finally, I've added a patch for a bug when trying to add chart sources manually (the modal dialog box won't close!).
> A few bug fixes, and adding Peruvian charts to chart downloader

- plugins/chartdldr_pi/src/chartdldr_pi.cpp
hi,
If there's no charts directory you can kill OCPN by clicking on 'Show local files' button.
Regards
Didier
> chart dld plugin: protect against null chartSource

- CMakeLists.txt
- include/dychart.h
- src/canvasMenu.cpp
wxGTK3 is built with GTK2 on Debian while it's built with GTK3 on Fedora.
wxGTK3 should pull the required dependencies without needing to add GTK2 or GTK3 in our packaging. Let's try to remove it:
The only place we're including some gtk dependencies is:
```
include/dychart.h: #include <gtk/gtk.h>
```
and the only gtk_* call is commented out:
```
src/canvasMenu.cpp:// gtk_widget_modify_bg (GTK_WIDGET(contextMenu->m_menu), GTK_STATE_NORMAL, &color);
```
*GdkColor color* is unused sot the whole block can be removed.
Then I guess we can remove the include from dychart.h and we don't need gtk include (thus dependency)
The other definition ocpnHAS_GTK is unused
The only remaining gtk is this block of code:
```
IF (NOT WIN32 AND NOT APPLE)
ADD_DEFINITIONS("pkg-config --cflags --libs gtk+-2.0") …
```
> Remove gtk direct dependency

- src/options.cpp
This helper is based on my own silly experiences. What! -  it's not working! Ahaa-- One zero forgotten in the entered MMSI, that's why the alert is still there. 
But, the OK button leaves it as is if user for some reasons like the entered number.
> MMSI properties- Add warning box if entered MMSI is not 9 gigits.

- include/ocpn_plugin.h
- include/pluginmanager.h
- src/pluginmanager.cpp
Extensions to the networking API to support functionality needed by Squiddio plugin.
Not commiting directly to the master as the Android counterparts of the wxCurl implementation are missing.
> Extend the plugin API with online check and HTTP POST

- src/s52plib.cpp
Hi,
two things:
- fully remove c9dbc4cc change to DoRenderObjet 
or under water rocks inside safety depth areas aren't displayed with standard mode .
- ObjectRenderCheckCat is showing in perf top but it can be optimised after the first pass.
Regards
Didier
> S52 speedup

- src/chcanv.cpp
Hi,
You can kill OCPN by pressing TAB key during startup, before g_Compass is created
in OnInit.
Regards
Didier
> protect against null g_Compass pointer

- include/chartdb.h
- include/glChartCanvas.h
- include/glTexCache.h
- src/chartdb.cpp
- src/glChartCanvas.cpp
- src/glTexCache.cpp
Hi,
Replace usage of time with a counter.
it's called rather often for charts textures and on some systems it's a slow syscall, well more than one, it's also stats /etc/localtime.
Regards
Didier
> Charts cache replace time with a counter for LRU aging.

- src/AIS_Target_Data.cpp
One new MID code added this year.
From www.itu.int:
Maritime Identification Digits
Series 	Allocated to	Date 	Operational Bulletin 	
-------
374 	       PNR 	               13/05/2015 	1078
> New MMSI MID code added. 374-PA

- include/Route.h
- src/NavObjectCollection.cpp
- src/Route.cpp
This greatly speeds up the loading time after a crash with a large number of route points
in a track to add.  For example if my computer ran out of power after a few days,
the next boot of opencpn trying to apply navobj.xml.changes would take about a minute
which is a very long time.  Now it is less than a second.
Similar logic could be applied for deleting points or other operations, but
maybe it's not really useful.
Conflicts:
src/NavObjectCollection.cpp
> optimize route distance calculation when adding new points

- include/Select.h
- src/Select.cpp
- src/chcanv.cpp
Hi,
Code in chcanv.c is keeping references to route/waypoint and may use them after they have been deleted.
It's using a slow linear search. It could be an issue in  IsSelectableSegmentSelected if there's a lot of waypoints, it's called from the buble timer callback.
Regards
Didier
> route, fix use after freed

- src/s57chart.cpp
Hi
Conditional symbology can change objects display category.
Reset it to its default value after a display style change.
Regards
Didier
> reset objects >m_DisplayCat in UpdateLUPs

- include/ocpn_plugin.h
- src/pluginmanager.cpp
This is an attempt to allow scalable fonts to be used in plugins. There is an issue with high resolution screens and the use of popups. The fonts are not being scaled correctly
> Add OCPNGetScaledFont_PlugIn api call

- src/datastream.cpp
If there is no TCP server then at least on Windows the wxSOCKET_LOST event is issued every 5 seconds and generates an endless stream of messages in the log file.
> Prevent needless entries in the log file when no TCP server is reachable.

- src/ais.cpp
- src/chart1.cpp
- src/chcanv.cpp
- src/compass.cpp
- src/glChartCanvas.cpp
- src/viewport.cpp
This removes skew compensation from opengl skewed raster charts,  Normal rotation is used to display skewed charts chart-up.
Non-opengl displayed skewed raster charts have many fixes but still use skew compensation.
> Fix skewed chart problems.

- include/s52plib.h
- src/s57chart.cpp
Hi,
Or after thumbnail creation lights 'L' and anchors 'A' setting are reset to 'on' in display ALL mode. 
Regards
Didier
> save plib noshow array when building thumbnail

- src/s52plib.cpp
Hi,
My previous patch 7761d11 was wrong...
Symptom: stuff like 260 deg (for recommended tracks) were not always displayed.
Regards
Didier
> s52plip parse text, zero terminated

- src/glTexCache.cpp
This has existed since 681a1b29 5/29/2015.
I don't know what this fixes, but it doesn't look right.
> Fix compressed cache file open.

- include/ocpndc.h
- src/ais.cpp
- src/ocpndc.cpp
This greatly improves ais rendering speed under opengl with typical options.  I'm confident with this change but it can also wait until after the stable release.
To do much better, we could build a texture containing all the possible permutations of the ships, then generate triangles and texture coordinates, then simply push this in one pass which would probably be really fast as there are no state changes, far fewer primitives, and the rendered quality would also be slightly better.
> ais optimizations

- include/Quilt.h
- include/chartdb.h
- src/Quilt.cpp
- src/chartdb.cpp
Hi,
Charts can (or should) be locked by other tasks and they shouldn't be unlocked when recomputing the quilt stack .
Regards
Didier
> Quilt, only unlock chart owned by it.

- plugins/chartdldr_pi/src/chartcatalog.cpp
- plugins/chartdldr_pi/src/chartcatalog.h
- plugins/chartdldr_pi/src/chartdldr_pi.cpp
- plugins/chartdldr_pi/src/chartdldr_pi.h
- src/pluginmanager.cpp
- src/wxcurl/dialog.cpp
- src/wxcurl/thread.cpp
- src/wxcurl/wx/curl/thread.h
Hi,
- a558926: I'm not sure setlocale (LC_ALL) is needed at all but without resetting LC_NUMERIC it trashes navobj.xml if in user default locale decimal point is a comma.
- 51352fe: not all zip downloaded have directories (triggered a wxAssert)
- without fa6cf11 I was unable to download the full US ENC set on a 32 bits system, memory reached 
3 GB twice.
Regards
Didier
> Charts downloader fix

- include/chartdb.h
- src/chartdb.cpp
- src/glChartCanvas.cpp
Hi,
foreground compression task can yield and the rendering logic
under memory pressure can free cache entries.
DeleteCacheChart: decrement lock counter by one and only delete
in cache if it's 0.
Regards
Didier
> lock chart in cache when compressing in the foreground

- include/ocpn_plugin.h
- plugins/grib_pi/src/GrabberWin.cpp
- plugins/grib_pi/src/GrabberWin.h
- plugins/grib_pi/src/GribRequestDialog.cpp
- plugins/grib_pi/src/GribSettingsDialog.cpp
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribUIDialog.h
- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/GribUIDialogBase.h
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
- src/pluginmanager.cpp
To do that is needed
- If scaled graphic interface is set
- the scaled GUI factor value set by the user
- compute the scaled factor as it is done in OCPNPlateform.cpp:GetToolbarScaleFactor
The two parameters are easy to get from reading the config file
To compute the factor, there is two choices : duplicate the code or include the function access in the plugin API , that is what I propose.
> Apply grib_pi scaled gui  from core

- src/glChartCanvas.cpp
These wxASSERT tests occasionally fail when switching from normal graphics to opengl with no way to recover.
> Replace wxASSERT with regular test.

- include/Quilt.h
Hi,
Fix the following:
select with the piano a raster chart, zoom out until it switches
to cm93 or gshhs chart, select a S57 chart and then zoom in,
raster are back.
Regards
Didier
> Reset m_zout_family whent setting a valid reference chart

- src/chart1.cpp
Hi
On a slow box it's rather easy to click twice on the toolbar with weird results like being unable to close OCPN and so on.
Regards
Didier
> protect against trying to launch multiple options dialog (double click)

- plugins/chartdldr_pi/src/chartdldr_pi.cpp
Hi,
SelectCatalog sets  m_lbChartSources selected item which fires a wxEVT_COMMAND_LIST_ITEM_SELECTED event ie SetSource so no reason to call it again (it's slow).
Only tested on linux.
Regards
Didier
> SelectCatalog calls SetSource indirectly as an event

- include/glTexCache.h
- src/glChartCanvas.cpp
- src/glTexCache.cpp
Hi,
small speedup, OCPN always write to disk all texture levels, don't write the catalog after every level but only once, it increases the window for cache corruption a little if OCPN crashes when writing the cache but then the data saved is dubious anyway. if it's a computer crash it does change nothing as OCPN  only sync the stream  not the disk.
Regards
Didier
> only write raster cache catalog once, not after writing every level

- include/options.h
- src/options.cpp
Hi,
don't call SetInitialVectorSettings each time the panel is displayed but only if it wasn't previously  called.
- it was slower
- if you made changes, switch panel and back, these changes were lost.
Regards
Didier
> options: only call SetInitialVectorSettings once

- src/chartdbs.cpp
Hi,
finddbIndex is called very often, use the wxString copy rather than converting again and again from char *
Regards
Didier
> use the wxstring version

- include/glTexCache.h
- src/glTexCache.cpp
Hi,
my previous was PR f22a182edff8f3d84d0d51bf98ee0381c36e869b was from an older patch and I forgot one 'little' thing when updating it:
UpdateCacheLevel is often called with the texture already in the cache file, in this case ocpn must not write a new catalog.
This PR deal with this case. If no UpdateCacheLevel write something don't write a new catalog.
Regards
Didier
> only write cache catalog if we actually update the cache

- src/glChartCanvas.cpp
Hi,
when building cache replace the logic used for distance.
The old method was using the chart center point but with big charts it can be hundreds if not thousands miles from ownship even if the chart is in the viewport.
The new logic is:
- if the chart contains ownship set the distance to zero.
- use the nearest edge.
Regards
Didier
> raster cache update: tweak chart distance logic

- src/s52plib.cpp
Hi,
With openGL texts and symbols aren't rotated in heading up mode.
Fix the bounding boxes for both.
For texts it's cosmetic and they still may overlap in quilt mode between charts.
For symbols I'm not 100% positive but I think previously  some symbols could not be rendered, remainder: you can double check bounding box in Object Query... with DebugS57=1 in opencpn.conf 
Regards
Didier
> Heading up

- include/glTexCache.h
- src/CM93DSlide.cpp
- src/chart1.cpp
- src/chcanv.cpp
- src/cm93.cpp
- src/glChartCanvas.cpp
- src/glTexCache.cpp
- src/s57chart.cpp
Hi,
In this case, zoom/panning is going to be choppy.
Have to remove most HideBusySpinner and move it into OnPaint.
Test with linux, DC and openGL modes.
Regards,
Didier
> Display the Busy cursor if texture cache is empty.

- src/ais.cpp
- src/chartdbs.cpp
Hi,
a2f1349 only matter with a lot of charts but  GetPathSeparator is  slow.
94fb3a4 in AIS , keep most used colors around rather than calling GetGlobalColor each time.
Regards
Didier
> Trivial speedup

- src/chart1.cpp
A lot of newbies get hung up because the initial tool tip of the ENC text toolbar button is wrong. It was hard coded instead of looking at the persistent state of the button. Now it follows the persistent state from the previous run of O.
> Initialize show/hide ENC tool tip text string per actual persistent state

- src/options.cpp
Hi,
if the user change TextureCompression mode OCPN must reset compression and delete all textures factories. 
Do the test before storing the new value in m_bTextureCompression not after...
I have look hard at the way glTextFactory are deleted and the interaction with the background spooler and it seems to be ok.
Regards
Didier
> test if cleanup is needed before setting m_bTextureCompression

- plugins/grib_pi/src/GribOverlayFactory.cpp
The viewport rotation already has correct skew adjustment.
> Remove skew from rotation in Grib texture.

- include/options.h
- src/options.cpp
Hi,
A regression, sort of.
wx SendIdleEvents is always traversing the whole widgets tree even the hidden ones, I have double checked with wx source code. When the options dialog is populated there's a lot of widgets.
NMEA can emit many idle events...
For example on my small box when replaying a capture at 200 messages/seconds OCPN CPU usage is around 85%, with this patch it's 30%.
On the other hand this patch may have unwanted side effects.
Regards
Didier
> Don't propage idle events in option dialog if not shown it's really slow

- src/bitmaps/styles.xml
Set the gps icons size directly rather than using tool icon size which changes between horizontal and vertical orientation.
> Add dimensions to gps bar icons.

- include/FontMgr.h
- src/AISTargetAlertDialog.cpp
- src/AISTargetQueryDialog.cpp
- src/FontMgr.cpp
- src/OCPNPlatform.cpp
- src/RolloverWin.cpp
- src/TCWin.cpp
- src/about.cpp
- src/chart1.cpp
- src/chcanv.cpp
- src/concanv.cpp
- src/glChartCanvas.cpp
- src/options.cpp
- src/s52plib.cpp
Hi
A try for fixing the font cache issue.
It's a copy of wx code with two changes:
1) don't test family if there's a font name, a font name can only have one family and in wxcode they use it first.
2) a wxASSERT for testing if the cache round trip, after testing on windows  it should be remove;
Regards
Didier
> Findorcreatefont

- src/chcanv.cpp
This cleans up an error introduced in 0dd308fd.
> Include rotated viewport in cached bitmap check.

- src/chcanv.cpp
I think this was just an oversight. Other uses of console pointer check for null before checking IsShown() method.
> Found intermittent null pointer deref

- src/navutil.cpp
If the users presses CANCEL some of the export functions would set the persistent GPXIODir variable in opencpn.ini to empty string. This is probably not what the user expects and is inconsistent with other export and import functions.
> Do not clear GPXIODir if user presses CANCEL button in file open dialog.

- include/Quilt.h
- include/chcanv.h
- src/Quilt.cpp
- src/chart1.cpp
- src/chcanv.cpp
Hi,
When toggling quilt off only unlock charts in the quilt not all charts, some charts can also be locked by texture background processes and unlocking them  can kill ocpn.
Regards
Didier
> toggle quilt, only unlock quilt charts

- include/chartimg.h
- src/chartimg.cpp
Before this was handled when the chart crossed the IDL,
but in the case where the viewport did and the chart did not,
the calculation used to be incorrect giving black charts in quilts
and failing to render single chart mode in dc-mode
> Correct coordinate calculation for raster charts

- src/styles.cpp
- src/toolbar.cpp
Hi,
- if the user hasn't defined a color for tooltips text uses  UITX1, black on dark UIBCK is unreadable, same as piano roll over.
- Tweak icon colors dimming in dusk and night modes, IMO it's still too dark for icons with a background (wmm journey style) but I'm unable to find a combination where vdr raster icons in traditional style aren't too bright.
Regards
Didier
> Toolbar tweaks

- src/chcanv.cpp
Hi,
I'm not sure how it's possible, related to timer firing? maybe it's only under valgrind but I have seen case where OnSize is called before pscratch_bm is set. OnSize delete pscratch_bm.
Regards
Didier
> set pscratch_bm early

- src/chart1.cpp
hi,
On exit plugins are unloaded and it triggers  a new toolbar each time, this toolbar is never displayed.
With SVG it's slow, all icons are recomputed.
On my (slow) box with 4/5 plugins enabled it adds 2 seconds to the exit time.
Regards
Didier
> On exit don't recompute a new toolbar

- src/styles.cpp
Hi,
with wx2.8 if an icon has no alpha but it's too big or too small it's not rendered.
eg: WMM pluging in journeyman style
BTW
- Who has the last WMM svg icon? In the tree svg text is missing. There's a nice unused compass icon in journeyman, It could replace the stock one.
- the Grib svg icon  is fine in wx2.8 but the last columns is truncated in wx3.0 
Regards
Didier
> wx 2.8 fix mergebitmaps if no alpha and not same size (WMM plugin)

- src/chart1.cpp
Hi
follow up on 52e94890e4e444f45ef215338c5a72c064f1b2e2
'Correct fault on single-chart thumbnail overlap of Chartbar.'
- There's a mismatch between screen and client coordinates.
- If the toolbar is reduced don't bother with overlap.
- Use the canvas client size not full size for the thumbnail maximum size or the status bar heigh is not subtracted.
- When centring move the thumbnail up the piano size,some river charts as 4/1 ratio and the thumbnail is really big and they still overlap!
Regards
Didier
> Thumbnail overlapping piano

- include/options.h
- src/options.cpp
Hi,
073fd68 ocpn killed:
linux 32 bits wx3.0.2 gtk2 
- open options dialog -> chart group pane, with 2 or 3 groups
- select a group
- remove a chart in a directory
- close options dialog 
- open options dialog  -> chart group 
- SIGKILL
Only test on linux.
Other are trivial leaks
Regards
Didier
> Options fixes

- plugins/grib_pi/src/GribRequestDialog.cpp
- plugins/grib_pi/src/GribRequestDialog.h
It was impossible to send a request when manually drawing the requested area  crossing the 180°
longitude line. There was also a fault in estimated area size in this case
Sorry to have seen this bug and corrected it so late
jean pierre
> Correct grib area manual drawing when crossing 180/-180 longitude line

- src/ais.cpp
In non-GL mode the drawing of AIS tracks one segment at a time makes debugging AIS scenarios nearly impossible. It is more efficient to draw each AIS track at one go using StrokeLines().
In GL mode it appears there is no equivalent call that will draw all segments from a vector of points. If there were a way then GL mode could be sped up somewhat but not as much.
Tested with a few thousand AIS track points and it is significantly faster in non-GL mode.
> Speed up track drawing in non-OpenGL mode.

- src/chart1.cpp
- src/multiplexer.cpp
- src/navutil.cpp
Allow the use of setting MaxWaypointNameLength in opencpn.ini to enable sending longer than 6 character waypoint names to GPS
> Allow longer waypoint names in Send to GPS

- .gitignore
Since building on Windows requires to put additional files into source tree, and some files are also automatically generated there by make-scripts, this fix will ensure that none of that garbage will ever be committed by accident.
> Adapt `.gitignore` to in-tree builds on Windows.

- plugins/grib_pi/src/GribRecord.h
- plugins/grib_pi/src/GribV1Record.cpp
Hi,
Zygrib NOAA is using  LV_ATMOS_ENT for cloud cover records, convert it to LV_ATMOS_ALL so grib_pi can display them.
Regards
Didier
> grib add LV_ATMOS_ALL from zyGrib for cloud cover

- plugins/grib_pi/src/GribReader.cpp
- plugins/grib_pi/src/GribReader.h
- plugins/grib_pi/src/GribRecord.cpp
- plugins/grib_pi/src/GribRecord.h
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribV1Record.cpp
- plugins/grib_pi/src/GribV2Record.cpp
Hi
Compute the right value for accumulation records, ie subtract the previous value if it overlaps.
It was mostly ok for zyGrib NOAA total precipitation data, they are reset every 6 hours (cf stepRange column):
grib_ls output
```
edition      centre       typeOfLevel  level        dataDate     stepRange    shortName    packingType  gridType     
1            kwbc         surface      0            20160411     0-3          tp          grid_simple  regular_ll  
1            kwbc         surface      0            20160411     0-6          tp          grid_simple  regular_ll  
1            kwbc         surface      0            20160411     6-9          tp          grid_simple  regular_ll  
1            kwbc         surface      0            20160411     6-12         tp          grid_simple …
```
> compute the right value for accumulation records

- plugins/grib_pi/src/GribReader.cpp
- plugins/grib_pi/src/GribV1Record.cpp
- plugins/grib_pi/src/GribV1Record.h
- plugins/grib_pi/src/GribV2Record.cpp
- plugins/grib_pi/src/GribV2Record.h
hi,
remove unused GribV2Record::readPackedBits and make it a static function in V1, it doesn't use grib object members.
grib v2: bailout quickly if the decoded attribute is not used ( it was using uninitialized value)
> Grib2 cleanup

- plugins/grib_pi/src/GribOverlayFactory.cpp
Hi,
fixes for rendering texts and overlapping  arrows if gribs cover the whole world and roll over.
cf:
http://nomads.ncdc.noaa.gov/data/gfsanl/
Notes:
- Overlays still not working... need two textures.
- There's a lot of asserts generated by requests at 90, -90 lat.
- isolines aren't closed around 359 /0 longitude.
Regards
Didier
> Grib for whole world

- src/navutil.cpp
Hi
'Route from track' can loop more than there's points in the track and it trigger trivial wxAssert iwwx dialog code:
```
../src/generic/progdlgg.cpp(435): assert "value <= m_maximum" failed in Update(): invalid progress value
../src/gtk/gauge.cpp(95): assert "pos <= m_rangeMax" failed in SetValue(): invalid value in wxGauge::SetValue()
```
Attach a track from weather routing showing this issue when trying to use 'route from track' button.
[track.zip](https://github.com/OpenCPN/OpenCPN/files/254929/track.zip)
Regards
Didier
> fix a wxAssert in RouteFromTrack

- src/chart1.cpp
Hi,
Unlike cm and s57 charts s63 plugin can't call SetPLIBColorScheme when opening a chart.
If this function it's not called some s52 stuff aren't correctly initialized. 
cf http://www.cruisersforum.com/forums/f134/s63-charts-wont-load-164390-2.html#post2105833
To reproduce: ocpn without menu (which called LoadS57 on init) and  a s63 only group.
Regards
Didier
> set s52lib color scheme on init

- plugins/grib_pi/src/GribOverlayFactory.cpp
Hi,
Speedup a little grib overlay rendering by using a smaller texture for small file.
try to use a texture size close to the grid size with a minimum size  of 128 and a maximum size of 1024.
Regards
didier
> Grib overlay

- plugins/grib_pi/src/GribV2Record.cpp
Hi,
GRIB2 and GRIB1 don't use the same unit for isobaric level... Convert GRIB2 Pascal to GRIB1 hectoPascal, used by geopotential heights.
Regards
Didier
> convert grib2 isobaric level to hectoPascal (grib1 unit)

- src/chart1.cpp
Hi,
- Most functions call by JumpToPosition expect -180 .. 180  longitude, enforce it.
for example NOAA nam grid  afwaca is using 0 .. 360 
latitudeOfFirstGridPointInDegrees = 30.054;
longitudeOfFirstGridPointInDegrees = 260;
latitudeOfLastGridPointInDegrees = 0.138;
longitudeOfLastGridPointInDegrees = 299.852;
[NOAA NAM Caribbean/Central America](http://nomads.ncep.noaa.gov/cgi-bin/filter_nam_crb.pl?file=nam.t00z.afwaca00.grb2.tm00&lev_10_m_above_ground=on&lev_2_mb=on&lev_entire_atmosphere_%5C%28considered_as_a_single_layer%5C%29=on&lev_mean_sea_level=on&lev_surface=on&var_APCP=on&var_PRMSL=on&var_TCDC=on&var_TMP=on&var_UGRD=on&var_VGRD=on&var_WTMP=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fnam.20160523)
if open in ocpn and click on 'Zoom To Center' it will display the grib …
> Jumptoposition

- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
The dialogue position was not always kept when toggle show/hide plugin
For example if you put it on the bottom/right side of the  canvas, it jumps to the top/left (in fact to the arbitrary default position.) This new code ovoid this boring behaviour
> Improve grib Ctrl Bar & cursor data positioning

- CMakeLists.txt
Currently, plugins get installed to */usr/local/lib64/opencpn* in openSUSE by default, while at run time they are being searched for in */usr/local/lib/opencpn* by wxWidgets. This patch fixes the installation path in the corresponding section of *CMakeLists.txt*.
> Fix plugin installation path for openSUSE.

- src/chartdbs.cpp
There is an implicit threshold in `ChartDatabase::DetectDirChange()`, empirically set to 10'000 files, that triggers speedy termination with a result that means “This directory contents has changed, it needs
to be re-processed again”. Therefore, instead of improving performance by avoiding some large and unnecessary job, it results in doing even larger, much more superfluous and complex processing (which
also needs to be fixed, by the way). I suggest to remove this artificial and non-configurable limitation.
Are there any situations where this limit may indeed provide some sanity safeguard? As far as I understand, chart stores of “special” types like CM-93/2 are explicitly excluded from such detection and thus will not suffer from this change; moreover, CM charts in particular are not …
> Partially fix FS#1465 by removing scan limit.

- NSIS.template.in
based on length of patch version number as it causes 4.2.xxxx to be considered a downgrade from 4.2.0
@bdbcat do you remember why we use this? Shall we apply it to the master as well? It will of course make a versioning cycle like 4.2.0 -> 4.2.2xxx -> 4.2.2 impossible due to being considered a downgrade, but IMHO will be less weird.
> Do not distinguish between stable and beta version in NSIS

- include/georef.h
- src/chartimg.cpp
- src/georef.cpp
Hi,
The code tried to not use adjustment with WGS84 datum but it was testing against  wgs72, fix it. Nonetheless it seems that
- a lot off homebrew charts are using wgs84 with a DTM  
- some other softwares don't use GD but only DTM.
So still keep the old behaviour, should be a little bit faster .
Regards
Didier
> Raster datum wgs84

- src/chcanv.cpp
- src/glChartCanvas.cpp
Hi,
If CPUS are removed we have to remove them in  compress_msg_array 
eg:
Rebuild the cache, skip
in a terminal 
echo 0 > /sys/devices/system/cpu/cpu1/online
Rebuild the cache
cf:
http://www.cruisersforum.com/forums/f134/opencpn-rc-4-1-1301-release-158718-16.html#post2014864
These global variables aren't nice though.
Regards
Didier
> in case cpus count is not constant

- include/triangulate.h
Without these declarations, compile without optimization fails.
> Added more C99 external inline function declarations for GCC5

- src/Select.cpp
hi,
My previous change had a copy and paste thinko and could trigger an endless loop if you create a route, append a waypoint and try to delete it.
Regards
Didier
> fix endless loop in DeleteAllSelectableRouteSegments

- include/triangulate.h
Without these extra lines opencpn will not complie/link under Ubuntu 16.04 (linux mint 18) using gcc 5.3.1
> Fixes for gcc 5 compile

- include/cm93.h
- src/cm93.cpp
- src/wxcurl/dialog.cpp
- src/wxcurl/wx/curl/dialog.h
Hi,
c++ is a mess, overloaded virtual functions call the one in the base class not the derived one.
I'm not sure the new cm93 scale behavior is the right one as cm93chart::GetNormalScaleMax was never called.
There's another one but a Sean patch remove it (use vectors for track https://github.com/OpenCPN/OpenCPN/pull/638 )
Regards
Didier
> Overloaded virtual

- plugins/chartdldr_pi/src/chartdldr_pi.cpp
Android version uses a two-line label, but non-Android uses a one-line
label.  When the download starts the label is changed to "Abort".  This
patch restores the original label for non-Android after download finished.
> Fix label for char download button

- include/triangulate.h
GCC 6 was released and needs the same declarations as GCC 5
> Make this file compile correctly with GCC-6

- src/gshhs.cpp
This fixes a bug introduced in commit 05c95b5d by Sean.  I emailed
him about this and he replied:
> I think you are right, it is misplaced.
> The reason nobody noticed or cared is this function is never called anymore.
> You could change it back to fix the warning...
> Fix misplaced brace

- src/chcanv.cpp
- src/mygeom.cpp
- src/routeprop.cpp
This fixes some indentation problems flagged by gcc-6 where an `else`
block without `{}` is followed by lines that are indented equally.
Concrete example:
```
if (foo) {
bar();
else
baz();
boo();
```
gcc-6 will flag the `boo()` line as a warning.
> Fix misleading indentation

- src/chartimg.cpp
Added the cast.  The better fix would be to make SIZE_X etc. unsigned
but that would be a much more intrusive patch because there are tons
of comparisons with signed integers (many of which propably should be
unsinged as well).
> Missing cast, causing "compare signed to unsigned" warning

- src/routemanagerdialog.cpp
Code used a tracklist pointer for a route list instead of a track list.  This caused
a crash when converting a track (generated by weather routing) into a route using
the track and route dialog.
The fix for this is in `OnTrkRouteFromTrackClick`.  This patch also fixes a similar
issue in `OnTrkMenuSelected` but I do not know how to invoke this code, so please
verify that this is correct before merging.
> Fix crash when exporting route to track

- include/routeman.h
- src/routeman.cpp
This fixes the problem that if no route/track with the GUID
exists the method simply returns the last route/track.
> Return NULL if route or track are not found

- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribUIDialog.h
We want to use the latest GRIB file at startup.  However, we were
finding files based on suffix and simply using the newest, even if that
was not a valid GRIB file.  Now we instead use the latest valid GRIB
file.
This is an enhancement of the previous pull request that is stricter about
file names and handles the "no valid GRIB file" scenario correctly.
> Really use the latest GRIB file (V2)

- plugins/chartdldr_pi/src/unrar/coder.cpp
- plugins/chartdldr_pi/src/unrar/extract.cpp
- plugins/chartdldr_pi/src/unrar/file.cpp
- plugins/chartdldr_pi/src/unrar/filefn.cpp
- plugins/chartdldr_pi/src/unrar/list.cpp
- plugins/chartdldr_pi/src/unrar/rarvm.cpp
- plugins/chartdldr_pi/src/unrar/rijndael.cpp
- plugins/chartdldr_pi/src/unrar/timefn.cpp
- plugins/chartdldr_pi/src/unrar/ulinks.cpp
- plugins/chartdldr_pi/src/unrar/unicode.cpp
- plugins/chartdldr_pi/src/unrar/unpack20.cpp
- plugins/chartdldr_pi/src/unrar/unpack30.cpp
- plugins/chartdldr_pi/src/unrar/unpack50.cpp
- plugins/grib_pi/src/jasper/jpc/jpc_cs.c
- plugins/grib_pi/src/jasper/jpc/jpc_dec.c
- plugins/grib_pi/src/jasper/jpc/jpc_mqenc.c
- src/options.cpp
- src/viewport.cpp
This is a re-implementation of #689 on top of current *master* branch, needed after #691 was merged as da7b094aad3cc7d5d9222aa807920ba94800d4ff.
Warnings that were left:
* Use of `tmpnam` in Jasper.
* Possible wrapping of `localtime_r` for multi-threaded wxWidgets.
Unfortunately, code smell mostly comes from third-party sources, like Jasper and Unrar, which may be re-imported again in the future.
> Prevent compiler warnings (well, most of).

- src/canvasMenu.cpp
Currently, in modern Windows environments, such as Windows 7 + wxWidgets 3.0, an extra bullet is displayed in “Chart Groups” context menu, — because the bullet character is explicitly added to menu item string by OpenCPN specifically for Windows.
Perhaps this quirk was required for some older Windows and/or wxWidgets version, but is superfluous now; not checked whether *Windows XP* is affected though. However, no other occurrence of that bullet character is found elsewhere in source tree, which makes me suspect that this case was really unique.
> Fix double bullet in chart group menu on Windows.

- plugins/chartdldr_pi/src/unrar/extract.cpp
- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/GribRequestDialog.cpp
- src/OCPNRegion.cpp
- src/glChartCanvas.cpp
- src/pluginmanager.cpp
Another set of fixes for mis-indentation flagged by
recenty GCC6.  Most were fixed by changing the indentation,
and a few by adding explicit {}.
> More GCC6 inspired indentation fixes

- src/chart1.cpp
Most toolbar buttons that show a dialog window hide that window
if the button is clicked while that window is shown.  For
consistency, make the route manager button behave identically.
> Toggle Route Manager Dialog Window from toolbar button

- CMakeLists.txt
- include/FlexHash.h
- src/FlexHash.cpp
- src/chart1.cpp
- src/chartdbs.cpp
- src/options.cpp
This is a single-commit version of PR #721.
* Adjusted the conditions under which chart header is loaded from file on directory scanning, changing it from mandatory to on-demand only, thus avoiding that costly loading procedure for unchanged documents.
* Fixed a newly discovered bug of not saving directories' new magic numbers in memory, which resulted in unnecessary updates until program restart. (That is, updated directory hashes were saved to config file, but immediately discarded from in-memory database, thus reverting to their previous values on subsequent scans during the same session.)
* Changed the method of directory's magic number calculation, replacing an addition-based checksum (susceptible to collisions) with cryptographic-grade hash, while retaining the original storage …
> Optimize chart database updates

- include/GoToPositionDialog.h
- include/SendToGpsDlg.h
- include/TrackPropDlg.h
- include/gpxdocument.h
- src/AISTargetListDialog.cpp
- src/ConnectionParams.cpp
- src/TrackPropDlg.cpp
- src/canvasMenu.cpp
- src/chart1.cpp
- src/chartdbs.cpp
- src/chcanv.cpp
- src/cm93.cpp
- src/glTextureManager.cpp
- src/options.cpp
- src/pluginmanager.cpp
- src/routemanagerdialog.cpp
- src/routeprop.cpp
This is the first part of string literal normalization, mostly targeted at superfluous string elimination. However some changes also involve bringing the spelling to “canonical” style, except when there is an existing string that would fit. Also, several strings have been removed from translation at all.
> Fix string literals by removing duplicates

- src/chart1.cpp
- Turned “unit_test_1” command line switch into an option that specifies the number of charts to display during the test, — instead of using a hard-coded limit. Zero or negative number stands for unlimited test.
- Added “-h” / “--help” option so that help could be requested directly.
- Added description to command line parameters.
- Reordered command line parameters with accordance to their similarity.
> Make “unit_test_1” limit configurable

- src/AIS_Target_Data.cpp
Hi,
cf:
FS#2145 - '4.4.0 doens't correctly handle destination' data:
!AIVDM,1,1,,A,139J0t000tPDIAVMvRVWWV;J0<00,0_09
!AIVDM,2,1,1,A,539J0t02;a3<@lhl001<<PhE=LTNlPti=@DTp01529t<<78@:?45E51h,0_68
!AIVDM,2,2,1,A,DQ1Cg?TSiA0V@08,2*2B
OCPN must escape HTML entities, likely also need in s57 obj INFORM text.
Regards
Didier
> escape HTML entities in AIS target query dialog

- src/AIS_Decoder.cpp
Fix to make NMEA TLL and TMM sentences equal in ARPA target lost logic. Needed for MARPA massaging from BR24Radar_pi
> ARPA TMM Lost logic fix

- src/OCPNPlatform.cpp
When searching for translation catalogs in Unix systems, wxWidgets defaults to *`$prefix`/share/locale*, where installation prefix refers to its own — wxWidgets' prefix (usually */usr* for packages provided by system), — not the application's one. On the other hand, canonical installation prefix for OpenCPN is */usr/local*, even when installed from package. Such a mismatch provokes inability to locate *.mo* files.
This patch explicitly adds */usr/local* to wxWidget search list. Alternative installation prefix may be specified in `OPENCPN_PREFIX` environment variable.
This is a rework of PR #724 atop of commit 3ab2bc457c976e5d4f1fa7cd1821345e4f640648.
> Fix search path for string translations in Unix.

- CMakeLists.txt
Currently, when an ancient *version.h* somehow gets in the source tree, it takes over any automatically generated header file of same name, which may cause all kind of build issues:
* an incorrect version string get inserted into the main executable;
* compilation of certain plugins cannot complete because of missing `PLUGIN_VERSION_MAJOR` etc.
With the proposed patch, whenever *include/version.h* is discovered in the root source tree, the user will be explicitly told to remove that file before proceeding with build configuration.
> Abort build configuration if include/version.h exists

- include/chcanv.h
- src/chcanv.cpp
This patch add two new functions to the measure function (M or F4).
- Delete of the last segment, during measurement, by delete or backspace key.
By this it is easier to correct a long measurement route.
- A distance circle, during measurement, to be able to easily find what's in range.
The circle distance function is enabled by: SHIFT+M or SHIFT+F4
This was a desired function from:
FS#1994 - Tool Measure add variable range ring with radius distance & shortcut
This is my first post and I have only worked with OpenCPN and GIT for one week.
I hope this is a way to contribute otherwise ignore this.
> Update of Measurement function

- plugins/dashboard_pi/src/nmea0183/gsv.cpp
It came up that new GNSS receivers are using the NMEA 4.1 protocol which has an extra field in the GSV sentence. This PR ignores the extra field and makes the parser a little bit smarter.
In the long run we need to decide how to deal with more than 12 satellites and various constellations that are reusing PRNs from GPS constellation. For now this fix at least gets Dashboard satellite viewer working with these new receivers.
> Allow GSV sentence with extra field per NMEA 4.1

- src/chartsymbols.cpp
I think it is an error to destroy the LUP data before removing the pointer from the array. Also, the index is known so is probably a better idea to remove it by index instead of by binary search.
> Remove LUP first by index then destroy.

- src/chart1.cpp
The COG filter algorithm "signals" loss of data by making the filtered COG a NaN. So if that happens we should not use it to rotate the VP. That can put the VP into a bit of a tizzy because other things depend on a valid rotation angle and for speed they don't check each time they use the rotation angle.
> Do not rotate viewport with NaN as the COG.

- src/options.cpp
WP Arrival circle radius is set to a minimum value at 0.001 in option.cpp : 4889:
g_n_arrival_circle_radius = wxMax(g_n_arrival_circle_radius, .001);
But the value for m_pText_ACRadius in options.cpp row 722 is set from g_n_arrival_circle_radius but with only two decimals thus new WPs will get 0.00 and "following a route" will never arrive and the AP will be set to turn around when a WP is passed.
> Correct number of decimals in Options Arrival Circle Radius

- plugins/grib_pi/src/GribUIDialog.cpp
This is a trivial patch. Colour is the last argument to SetCellBackgroundColour() not the first.
> Correct order of arguments to SetCellBackgroundColour().

- include/chcanv.h
- src/chart1.cpp
- src/chcanv.cpp
- src/navutil.cpp
The size of tide rectangles (the rectangular "icons" drawn on the
chart to show tide height at tide stations) was previously hard-coded
in terms of pixels, and so the rectangles become too small to be
readable on high-resolution displays. The changes in this commit make
the size of the tide rectangles depend on screen resolution, to be
readable on any display.
The changes also introduce a parameter TideRectangleScale, default
value 100, which can be set in the opencpn configuration file to allow
users to modify the scaling of the tide reactangles, by analogy with the
existing CurrentArrowScale parameter for adjusting displayed size of
current arrows.
The changes have been tested under Ubuntu 16.04 LTS and Windows 10, on
displays up to 3200x1800 resolution.
Cf. …
> Make tide rectangles' displayed size depend screen resolution

- src/s57chart.cpp
Hi,
cm93 charts (and s63 ?) don't call AssembleLineGeometry function so they leak m_ve_hash memory, free it in destructor. Also free m_vc_hash if any. 
Regards
Didier
> free m_ve_hash m_vc_hash in s57 dtor

- src/AIS_Decoder.cpp
Sorry, forgot to add ship name obtained from AIS message 19 as a condition to load it into the hash table
> Add AIS message_ID 19 to ship name hash table

- include/TCWin.h
- src/TCWin.cpp
In some circumstances, current graphs would be displayed without an
explicit "0" line, which would make it difficult to see the precise
times of slack current. This commit arranges the graph's  vertical
coordinates so that the "0" line of slack current is always displayed.
This implements (my own) flyspray feature request FS#2119.
> Always show zero line on current graphs

- include/TCWin.h
- src/TCWin.cpp
- src/chcanv.cpp
- src/navutil.cpp
Even in Beta 4.5.213, tide and current graph windows (instances of TCWin)
do not render well on high-resolution displays because the window size
is too small. This commit addresses this problem by scaling each TCWin by
a factor that depends on the screen resolution.
This commit also introduces a configuration file parameter
TideCurrentWindowScale, default value 100, which allows the user to
modify the scaling, along the lines of the existing parameters
CurrentArrowScale and TideRectangleScale.
Cf. http://www.cruisersforum.com/forums/f134/opencpn-scaling-problems-with-high-resolution-displays-179462.html#post2316692
> Scale tide and current graph windows depending on screen resolution

- src/navutil.cpp
On Mac OS X the save dialog always prompts users if they want to overwrite existing files. So if you try to overwrite a GPX file, you are prompted twice, once by the OS, and once by OCPN. This commit fixes this problem, and shouldn't affect other platforms.
I've tested this on OS X 10.12.3
An alternative fix would be to add "wxFD_OVERWRITE_PROMPT" to the flags for wxFileDialog in OCPNPlatform::DoFileSelectorDialog, and remove OCPN's own dialog box entirely; this would need to be tested on other platforms.
> Remove "Overwrite existing file" dialog on Mac

- src/s57chart.cpp
This allows the ENC thumbnail to be shown after a restart without first displaying the ENC.
> Remove sha1 from ENC thumbnail bitmap file name.

- src/glTextureManager.cpp
- src/navutil.cpp
Hi,
- NCPUCount cd issue https://github.com/OpenCPN/OpenCPN/issues/686
- On linux I have a rendering glitch when building the raster cache and sometime the dialog button is not visible, with  wxPD_CAN_SKIP closing the dialog box is impossible. 
- If there's a lot of charts with  raster cache already fully computed you can't close the dialog box, the screen is not updated.
Regards
Didier
> Raster cache

- opencpn.spec.in
* Switched to the new UI data layout.
* Made content selection more generic and future-proof overall, also preventing warnings.
* Removed cleanup commands that are obsolete for out-of-tree builds.
> Update and generalize RPM spec

- include/glTextureManager.h
- include/s52plib.h
- src/glTextureManager.cpp
- src/s52plib.cpp
- src/s57chart.cpp
- src/texcmp/squish/alpha.h
- src/texcmp/squish/clusterfit.h
- src/texcmp/squish/colourblock.h
- src/texcmp/squish/colourfit.h
- src/texcmp/squish/colourset.h
- src/texcmp/squish/rangefit.h
- src/texcmp/squish/singlecolourfit.h
- src/texcmp/squish/singlecolourfitfast.h
- src/texcmp/squish/squish.cpp
- src/texcmp/squish/twocolourfitfast.h
Hi,
stuff I changed when looking for bugs
JobTicket: rename rect member m_rect
there's a lot of variable rect shadowing JobTicket rect member, make code harder to read.
replace include <squish.h> with "squish.h"
We really don't want to use a squish.h from system directories but the one in our source treee.
Regards
Didier
> various Cleanup

- include/FontMgr.h
- include/ais.h
- include/ocpn_plugin.h
- src/FontMgr.cpp
- src/ais.cpp
- src/chcanv.cpp
- src/glChartCanvas.cpp
- src/pluginmanager.cpp
The BR24radar_pi group is adding (M)ARPA support for which we are sending ARPA targets to OpenCPN.
We would like to be able to draw these on the radar-only PPI windows, with the added bonus that we also see the AIS targets on the PPI display. This is also what the Navico plotters do.
This commit refactors ais.cpp in as minimal a fashion as possible so that it allows sharing of the AIS drawing code with the plugin(s).
> Plugin API 1.14 - Externalize AIS drawing

- plugins/dashboard_pi/src/wxJSON/jsonreader.cpp
- plugins/dashboard_pi/src/wxJSON/jsonval.cpp
- plugins/dashboard_pi/src/wxJSON/jsonwriter.cpp
- plugins/grib_pi/src/jsonreader.cpp
- plugins/grib_pi/src/jsonval.cpp
- plugins/grib_pi/src/jsonwriter.cpp
- plugins/wmm_pi/src/jsonreader.cpp
- plugins/wmm_pi/src/jsonval.cpp
- plugins/wmm_pi/src/jsonwriter.cpp
- src/wxJSON/jsonreader.cpp
- src/wxJSON/jsonval.cpp
- src/wxJSON/jsonwriter.cpp
hi,
There's a lot of stuff like:
wxLogTrace( traceMask, _T("(%s) searched key=\'%s\'"), __PRETTY_FUNCTION__, key.c_str());
in json code, by default it does nothing but it's still slow, building the function parameters is slow enough to show up in perf traces, up to 5% with a lot of plugins enable.
With wxDEBUG_LEVEL defined as 0 wxLogTrace is empty and there's no slow down.
Of course plugins outside OCPN tree have to be modified too.
An other option would be to put json and font stuff in OCPN plugin ABI.
By default wxDEBUG_LEVEL is defined as 1 in debug.h which is included by wx/wxprec.h in most (all?) OCPN source files. Thus using -DwxDEBUG_LEVEL=0 argument would remove a lot of ASSERTs.
Regards
Didier
> json , disable wxLogTrace in release mode, it's slow

- plugins/grib_pi/src/email.cpp
On macOS, open the default MUA application with the grib request e-mail.
Tested only with the default Mail.app client on macOS Sierra.
> Implement support for Mail.app to send grib requests

- src/Quilt.cpp
Hi,
Test was removed by 1019bb51 but for charts with only nocvr areas visible you get:
Eclipsed chart is not visible and displayed charts are dark green.
Regards
Didier
> don't Quilt invisible chart

- src/s52plib.cpp
Hi,
With the latest code it's possible to rescale no opengl rendered  symbols by more than 2 but there's symbols with  width of two...
It triggered a wxAssert
Regards
Didier
> Render symbol, protect against image with zero width or height

- src/chart1.cpp
- src/chcanv.cpp
- src/navutil.cpp
- src/options.cpp
Add "hidden" option to opencpn.conf (opencpn.ini) named SpaceDropMark that if set to 1 enables space bar to drop mark at own ship position.
> Optionally allow space bar to drop mark at own ship position

- src/chartimg.cpp
conic projections rely on internal reference points
or coefficients anyway so we already support all types
of conic projections.
We should remove the code that computes conformal conic
projection coordinates because it should never be used anyway.
I realize that conic charts (even of same type of conic)
cannot be quilted without opengl.  Currently allowed, it is technically
incorrect.   This is true of transverse mercator as well.
In many cases the error is less than a pixel so
could be allowed for that case.  It currently doesn't (and never did)
compute the error to verify that it is ok to quilt these charts.
We can quilt different projections without opengl as long as the max
error is below a pixel, but would be tricky to compute optimal quilts.
> support all conic projections

- src/s52cnsy.cpp
Hi,
' the value EXPSOU = 1 (within the range of the surrounding depth
area) should be populated in order to avoid the unnecessary display
of isolated danger symbols in ECDIS. '
standard display
master:
this version:
Mode all:
Time to move to preslib version 4 ?
Regards
Didier
> use EXPSOU in danger logic

- plugins/dashboard_pi/src/dashboard_pi.cpp
Several users has for understandable reasons used PITCH instead of PTCH. This patch make both names valid.
> Add transducer name PITCH for XDR Type A to Dashboard

- plugins/grib_pi/src/GribV1Record.cpp
Hi,
Was leaking memory when reading a bad file.
Regards
Didier
> grib: memory leak on read error

- src/routeprop.cpp
Eventually wxWidgets will flag this connection with an assert since it will never generate an event. The enter key event will go to the dialog box and not the text element itself thus these connections are pointless.
> Connecting to wxEVT_COMMAND_TEXT_ENTER is pointless here.

- src/Track.cpp
- src/TrackPropDlg.cpp
- src/georef.cpp
Added latitude offset in case latitudes of adjacent track points are too close together else the great circle distance calculator will divide by zero. Minimize the error thus introduced by minimizing the amount of offset. For tracks with thousand of points close together the error can add up to as much as 0.05NM.
Also, cached track length in the property dialog to avoid multiple calls to Track::Length().
Added wxASSERT in the great circle calculator to alert debuggers when a divide by zero is about to happen.
> Fix track length calc

- plugins/grib_pi/src/GribTable.cpp
When using an attribute pointer the wxGridTable object becomes the owner of the pointer. So if the same pointer is used multiple times to set the attributes for multiple rows or cells then wx will try to destroy it multiple times. To avoid this the ref counter needs to be incremented each usage after the first usage. This error caused multiple wxAsserts when the weather table is closed.
> Only free row attributes once.

- plugins/dashboard_pi/src/nmea0183/lat.cpp
- plugins/dashboard_pi/src/nmea0183/long.cpp
- src/nmea0183/lat.cpp
- src/nmea0183/long.cpp
Trying to trim or compare an empty wxString causes an assert. Sometimes the lat/long fields are empty with certain Garmin GPS units and possibly others when signal strength from satellites is low.
> Don't try to trim/compare with an empty string.

- src/chart1.cpp
- src/routeprop.cpp
There is still a bug in route properties. The object RouteProp is
created only once and reused each time the user views a route's
property sheet. However, if the user changes the compass heading
variation (true/magnetic) then the cached RouteProp object is
stale and may not have columns for the variation selected by the
user. This can cause a crash. The workaround is to close OpenCPN
anytime the user changes the variation options.
> Handle both true and magnetic heading/bearing cases in route property list.

- src/chartdbs.cpp
On slow computer BuildChartStack can be called from Init before reading
the DB.
Leading to a crash:
`````
*** opencpn (wxWidgets 3.0.2) crashed ***, see backtrace!
0x841a96c in wxCrashPrint::Report() at ??:0
0x4a7f293 in  at ??:0
0x511c1a8 in  at ??:0
0x81a7ee1 in ChartDB::BuildChartStack(ChartStack*, float, float) at ??:0
0x82482b3 in Quilt::BuildExtendedChartStackAndCandidateArray(bool, int, ViewPort&) at ??:0
0x82484fe in Quilt::AdjustRefOnZoomIn(double) at ??:0
0x81e26c8 in ChartCanvas::DoZoomCanvas(double, bool) at ??:0
0x81e2d72 in ChartCanvas::DoMovement(long) at ??:0
0x81e316a in ChartCanvas::DoTimedMovement() at ??:0
0x491a2f6 in wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const at ??:0
0x491a71b in …
```
> ChartDatabase set bValid to false in CTOR

- include/ocpn_plugin.h
- src/pluginmanager.cpp
Previous work on this had incorrectly omitted the DECL_EXP specification, so the API 1.14 changes did not work on Microsoft Windows.
Also, the new PluginGetFontColor() function was duplicate since there was already a GetFontColour_PlugIn(), so this is removed again.
> Fix API 1.14 for Microsoft Windows

- src/NavObjectCollection.cpp
to contain the obligatory gpxx::RouteExtensions::IsAutoNamed element
This makes our GPX files importable to Garmin Homeport
> Fix the GPXX extensions in saved GPX files

- src/chcanv.cpp
hi,
On a slow computer zooming events (via keyboard or mouse) can come in before charts database is fully initialized.
Regards
Didier
> On startup ChartData can be null in Zoom functions

- src/chcanv.cpp
Adding an alternative shortcut to drop a Man-Over-Board
(MOB) marker on the map when the Pause/Break key is
pressed. The existing shortcut (Ctrl-Space) remains untouched.
A single key shortcut is required to allow the straight forward 
use of the Linux device tree overlay feature in order to support
a MOB switch (e.g. connected to the GPIO pins of the Raspberry 
PI). This way allows to efficiently handle and emit MOB key 
events at kernel level and guarantees high reliability.
> Drop a MOB marker on Pause/Break key press

- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/grib_pi.cpp
- src/TCWin.cpp
- src/chart1.cpp
- src/chcanv.cpp
- src/tcmgr.cpp
Hi,
As you know we have some mighty tides here and most harbors are  behind locks so when planning knowing  seal level at destination matter a lot.
With this change tide and current can use a different clock, not only the system clock. As indicator it's using a different colors set.
The GRIB plugin uses it for driving tide gauges with its records' time.
System time, yellow gauge
Grib time, brown gauge
> Time source

- src/datastream.cpp
Doing so resulted in in the timer continuously reset,
and never actually firing.
> Do not restart timer if it is started already.

- src/canvasMenu.cpp
When a route is active users naturally right clicking on that route. But the context menu does not show the option to zero cross track error even though that could be why they clicked on it. This change adds the option to the route context menu.
> Show Zero XTE in active route context menu

- src/AIS_Decoder.cpp
Plugins like AIS radar need this data.
> Compute AIS target range and bearing even if GPS data is not valid.

- src/chcanv.cpp
Only set the timer (to 500ms) if it is not running yet.
> Fix issue #884 - AIS and route rollover popups never time out when refreshes are < 500 ms

- src/pluginmanager.cpp
This was causing the app to crash if it tried loading an incompatible plugin.
> Crash from incorrect log format parenthesis 

- plugins/grib_pi/src/GribV1Record.cpp
Hi,
fix for http://www.cruisersforum.com/forums/f134/inverted-grib-display-193517.html and missing rain.
The issue is with !hasDiDj being true, I'm not sure where is coming from in zyGrib but it' s not needed.
I have double checked with degrib and I get the same output lat,long, value. Moreover ECMF grib tools are able to convert this file  in readable for us grib V2 so I don't think is a badly generated file.
I don't have other files with !hasDiDj true.
Untested are files with a !hasDiDi and a BMS.
Regards
Didier
> Gribv1 without DiDj 

- src/TCWin.cpp
hi,
It's still possible to do it if OCPN is trying to display a not fully created TCWin after it's yielded.
Conditional jump or move depends on uninitialised value(s)
wxDCImpl::CalcBoundingBox(int, int) (dc.h:333)
wxWindowDCImpl::DoDrawRoundedRectangle(int, int, int, int, double) (dcclient.cpp:944)
DrawRoundedRectangle (dc.h:1186)
TCWin::OnPaint(wxPaintEvent&) (TCWin.cpp:765)
wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) 
And so on .
Regards
Didier
> Crashing Tc win

- include/ocpn_plugin.h
- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/IsoLine.cpp
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
- src/pluginmanager.cpp
Fixes #892 
I have started API 1.15 with added support for this functionality instead of implementing a workaround by reading the ini file from the plug-in, seems cleaner to me.
> Fix Grib plugin to use same screen size as main application

- src/glChartCanvas.cpp
A simple fix -- pass the context so that the plugins can either use it or create their own and restore it when done.
> Suggested fix for #886 - Pass m_pcontext to plugins on RenderGLCanvas().

- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/GribOverlayFactory.h
- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/GribUIDialogBase.h
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
Hi,
Add a plugin preference for drawing, or not, wind barbed arrows head. 
Less clutter with high resolution grid.
example is 1.3 km/1Hr grid wind and 250m/15mn current 
Regards
Didier
> grib add a 'draw barbed arrow head' plugin pref

- plugins/grib_pi/src/GribUIDialog.cpp
This can be reproduced for example using the weather_routing plugin: just define a route and click on "Calculate", OpenCPN will crash if no grib file is available.
Some discussion here: http://www.cruisersforum.com/forums/showthread.php?p=2535010
> Fix crash in grib_pi when data is requested but no grib file is loaded

- plugins/wmm_pi/src/MagneticPlotMap.cpp
- plugins/wmm_pi/src/WmmUIDialog.cpp
- plugins/wmm_pi/src/wmm_pi.cpp
In the wmm plugin dialogs there is on a view places the term declination used where variation is the correct one. In the code there are a lot of variables also named / marked as declination, but those are not changed, only the ones appear in the dialogs.
> Change "Declination" into "Variation" see FS#1065

- plugins/grib_pi/src/GribOverlayFactory.cpp
Hi,
push back Jean-Pierre 4.4 fix for missing current arrows in no GL mode
Regards
Didier
> Correct direction arrows display when no GL && hight definition graphic

- src/Quilt.cpp
Hi,
reduced regions  introduce visible artifacts if used for drawing quilt. 
unpatched with gray area:
patched
Regards
Didier
> don't use reduced region when drawing charts

- src/options.cpp
(silences an annoying assert on startup)
> Replace the 'empty line' on the Units tab with a spacer

- plugins/chartdldr_pi/src/chartdldr_pi.cpp
When downloading many small charts (typically vector charts), the 1 second yield
could actually become the limiting factoring on total download time, since the
next chart would not start downloading until the yield ended.  Reducing it to
100 milliseconds ameliorates that problem, but it still feels a bit laggy because
the progress indicator is still updating fairly infrequently.  10 milliseconds
is fast enough that the progress indicator shouldn't feel laggy, but still enough
to avoid over burdening the system.
> Reduce the yield time while downloading charts from 1 second to 10 milliseconds.

- src/chart1.cpp
- src/chcanv.cpp
Hi
I'm no 100% happy with this one, it's a copy and paste from DoChartUpdate.
Without this patch screen in single chart mode, not auto-follow  mode screen is not redrawn  when switching
to a group with no charts visible until you move the viewport, for example switching from a group with raster charts to a group without charts.
Regards
Didier
> in ChartsRefresh init Current_ch with a Dummy chart if not set

- src/chcanv.cpp
Hi,
fix improper merge conflict between f55bae
"Improve zoom logic to skip micro-zooms."
and 23c383
" in ChartsRefresh init Current_ch with a Dummy chart if not set"
Symptom: 
Unable to zoom in CM93 chart with the mouse after zooming it out to 1/70 000 000.
(kbd still working).
Regards
Didier
> SetViewPoint merge conflict resolution error

- plugins/grib_pi/src/GribRecord.cpp
Hi,
Copy first grib rather than returning null if we can't interpolate.
I'm not sure it's the proper solution put IMO returning empty record is worse. 
eg if you download a grib from
http://195.154.231.142/IFREMER/
there's 15 mn current but if interpolated every .5 mn it returns empty grib.
U/V aren't exactly as the same position. As i'm producing these gribs from IFREMER NCFD curvilinear grids I could re map them but in my understanding these kind of grids are rather common for current (IIRC German current).
It's an issue with weather routing, more with IFREMER hourly current though. With a lot of exclusion zones hourly step is too big (Think Needles and Solent) but with 30 mn step interpolation is returning 0 current speed and routing is wrong.
Regards
Didier
> Grib interpolate

- include/options.h
- src/options.cpp
Adds ability to set track highlight color from Ships config page.
The commit also fixes a bug with wxColourPickerCtrl for g_colourWaypointRangeRingsColour which allows the Opacity/Alpha to be set in wxColour. This breaks writing to the config file with wxC2S_HTML_SYNTAX as it does not support alpha data. Ideal fix would have been to disable Opacity slider in wxColourPickerCtrl but doesn't seem to be disabled.
> colourPicker on Ships config page for track highlight colour + bug fix for Range Ring Colours

- src/Osenc.cpp
- src/s52cnsy.cpp
Hi,
Save QUAPOS attribute in OCP senc file for point object.
Re use QUAPOS rather than QUALTY, (no integer value for QUALTY).
Need to recompute vector charts.
Regards
Didier
> point object put QUALTY logic back

- src/chart1.cpp
- src/chcanv.cpp
Hi,
in north up mode OCPN is currently  recomputing the chart stack every second or two  even if nothing change.
Don't do it. Bugs hidden by this may showing up though.
Regards
Didier
> don't update charts list in timer callback if we don't change viewpoint

- include/chart1.h
- include/s52plib.h
- src/chart1.cpp
- src/chcanv.cpp
- src/pluginmanager.cpp
- src/s52plib.cpp
Hi,
Reuse anchor logic, which has slightly since 4.8.0: now by default it's off. IMO Objects  affected by anchor and data quality should be grayed in mariner standard option.
Need oesenc changes 
line 8032 modification in s52plip.cpp
-    if( !ObjectRenderCheckRules( rzRules, vp ) )
+    if( !ObjectRenderCheckRules( rzRules, vp, true ) )
May have unwelcome side effects.
Regards
Didier
> keyboard shortcut for data quality FS #2294

- CMakeLists.txt
- FindEXIF.cmake
- include/pugiconfig.hpp
- include/pugixml.hpp
- src/pugixml.cpp
- src/wxsvg/include/wxSVG/ExifHandler.h
- src/wxsvg/include/wxSVG/SVGCanvasItem.h
- src/wxsvg/include/wxSVG/SVGDocument.h
- src/wxsvg/include/wxSVG/SVGStringList.h
- src/wxsvg/include/wxSVG/mediadec_ffmpeg.h
- src/wxsvg/src/ExifHandler.cpp
- src/wxsvg/src/SVGAnimationElement.cpp
- src/wxsvg/src/SVGCanvasItem.cpp
- src/wxsvg/src/SVGDocument.cpp
- src/wxsvg/src/SVGLineElement.cpp
- src/wxsvg/src/SVGPathElement.cpp
- src/wxsvg/src/SVGPointList.cpp
- src/wxsvg/src/SVGPolygonElement.cpp
- src/wxsvg/src/SVGPolylineElement.cpp
- src/wxsvg/src/SVGRectElement.cpp
- src/wxsvg/src/SVGSVGElement.cpp
- src/wxsvg/src/SVGStringList.cpp
- src/wxsvg/src/SVGTextElement.cpp
- src/wxsvg/src/cairo/SVGCanvasCairo.cpp
- src/wxsvg/src/cairo/SVGCanvasPathCairo.cpp
- src/wxsvg/src/cairo/SVGCanvasPathCairo.h
- src/wxsvg/src/mediadec_ffmpeg.cpp
- src/wxsvg/src/svgctrl.cpp
To keep up to date with upstreams, not fixing any apparent problems and can wait for O5.
wxSVG introduced support for exif metadata via libexif in 1.5.10. We support building with it on Linux and macOS when libexif is found, turn off the support if not (unlike the upstream which always requires it now).
On Windows we do not even try - another update to the dependency bundle would be needed with libexif and there was enough for O4.8.2 already.
> wxSVG and pugixml update

- src/ChInfoWin.cpp
Hi
Use 1 again for adjust on linux, but set clientsize.
It fixes my issue with xfce and wrong window size.
Notes:
- With unpatched version, sometime the size is right, ie with a lot of bottom white lines, sometimes it's displayed centered on screen. Unable to reproduce with this patch applied. 
- because it's a full dialog in night mode there's a nasty white flash. In my understanding the window is first rendered by the windows manager with the default background then redraw with dark background by the application. I tried to not delete this info window in chcanv.cp only hide/show it, did nothing. I also tried to set background color in CTOR , again no change. Changing the windows manager default background color could be the only option (I didn't test it).
Regards
Didier
> chart info window: set client size, help xfce window manager

- src/tcmgr.cpp
Hi,
In tide dialog box time can go backward. cf 
http://www.cruisersforum.com/forums/f134/opencpn-beta-version-4-8-10109-a-195843-2.html#post2552110
Regards
Didier
> TCMgr::GetHightOrLowTide missing abs in testing cache validity

- src/Quilt.cpp
Protects against:
- Overly complicated NOCOVR areas used while building the chart quilt. This helps to limit the performance impact of some badly designed ENC chart cells.
On the SCS ENC cells, the NOCOVR areas have up to 10000 PLYs, together with the similar complexity of the cell PLYs, combining the regions has disastrous performance impacts with little real effect.
- Overly complicated PLYs. Again seen only on some of the SCS ENC cells. When a shape too complicated is detected, it is skipped and the full chart extents are added to the region.
This is still just a partial improvement, the cells still are causing significant slowdown, but on decent HW, the application stays usable.
As far as I can tell, areas covered by sane chartmakers are completely unaffected.
> Implement simple safeguards to maintain quilting performance acceptable

- src/chcanv.cpp
had this issue with my surface pro 3 running arch linux that dragging around the visible part of the map was not usable at all when using touch. Fixed it in this small patch. Thoroughly tested. Might be worth a shot!
keep up the good work!
> fixed dragging issue with touch-enabled pcs

- include/glChartCanvas.h
- include/options.h
- src/Track.cpp
- src/cm93.cpp
- src/glChartCanvas.cpp
- src/navutil.cpp
- src/ocpndc.cpp
- src/options.cpp
- src/s52plib.cpp
Based on the points raised in https://github.com/OpenCPN/OpenCPN/issues/889 makes the polygon and line smoothing optional.
Of course I am no GL expert so have no idea whether or not we should also disable blending in case smoothing is off, but let's take this as a start...
> Make line and polygon smoothing optional in OpenGL mode.

- src/wxJSON/jsonreader.cpp
- src/wxJSON/jsonval.cpp
- src/wxJSON/jsonwriter.cpp
I am using wxJSON for signalk parsing for my pypilot (signalk autopilot) plugin.   As you know, on linux (unlike windows), the plugins will use the wxJSON symbols in opencpn rather than their own wxJSON.
wxLogTrace is unbearably slow.
So slow that it makes the plugin hiccup while it parses the signalk streams.
This is currently guarded in #ifdef NDEBUG.   The NDEBUG macro is never defined by linux builds, only windows ones.
I propose to just disable wxLogTrace in wxJSON.   It is for debugging wxJSON itself, not invalid json data.
> make wxLogTrace a noop in wxJSON always

- src/options.cpp
The "Port" string in options.cpp is about a Data port. The "Port" string in ais.cpp is about port as opposite to starboard. That's confusing translation to Swedish and may be the same for other languages? 
I know this is an old issue but this change may solve this one?
> Change one Port string to Data Port

- src/chartimg.cpp
This corrects argentina (and probably brazil) RNC charts
chartlist.dat needs to be removed... How do I force it to rebuild
chartlist.dat when I know the code changed?
Should we perform this for other types of raster charts besides KAP?
> perform intersection of covr region to chart image

- src/chart1.cpp
@bdbcat - Do you have memory why it was never enabled? Seems to be working just fine here.
> Allow transparent toolbar in OpenGL mode on macOS

- src/datastream.cpp
hi,
Over UDP Furuno adds a proprietary header which includes null bytes.
Copy the whole stuff from the socket not NMEA headers are removed later.
Caveat: a std:string with embedded null is asking for trouble, maybe it should be change to a vector.
Regards
Didier
> furuno UDP use ascii null char before NMEA sentences

- src/options.cpp
Original mod only set track highlight colour. (though variable name is TrackLineColour)
Recent commit correctly combined track colour and track highlight colour when displaying.
https://github.com/OpenCPN/OpenCPN/commit/dbefaf95dc8b7be1dc086902c822c4148e6f48cd
This pull request just clears up naming on Options -> Ships window.  Setting now titled 'Track Colour'
> correct name for track colour setting on Ships options page

- plugins/grib_pi/src/CustomGrid.cpp
- plugins/grib_pi/src/GribRecord.cpp
Hi,
Sometime undefined current value or UV vectors were used as if valid.
Attached a small grib showing the problem. If you move the cursor around you get bogus values, same when displaying a grib table.
Regards
Didier
NB
There's another bug, sometime it returns an overlay to big for this small file, I'm looking at it.
[test-grib.zip](https://github.com/OpenCPN/OpenCPN/files/1702303/test-grib.zip)
> Grib not def values

- src/NavObjectCollection.cpp
- src/routeman.cpp
Fixes #984 by using logic faster than the full-blown GUID generation. But it comes at a price of later maybe (List layer contents, export as GPX) exporting GPX with "predictable" GUIDs `LayGUIDxxxx`
> Assign a unique GUID to GPX loaded as a layer

- .travis.yml
Update travis build for O5 and produce a fully usable installer for macOS instead of building against stock wxmac
> Travis for O5

- src/LLRegion.cpp
The llregion will not work perfectly for grids like mbtiles but this may help.
Maybe we can use an alternate algorithm that works for tiles in a grid.
> improve LLRegion optimization for parallel overlapping segments

- src/OCPNPlatform.cpp
- src/chart1.cpp
In Win portable mode the two files was saved wo path separator thus in wrong place and by wrong name.
This fix runs fine in Windows but neither tested on Linux nor Mac. Please check before merge.
Thanks
> Fix portable save of CHRTLIST.DAT and MMSINAME.CSV

- src/SQLiteCpp/include/SQLiteCpp/Database.h
- src/mbtiles.cpp
This should fix compilation on modern Linux distros.
Currently we depend on https://github.com/OpenCPN/OpenCPN/blob/master/CMakeLists.txt#L941 to decide which version of `sqlite3_value` to forward declare. It does not work at least on Ubuntu 17.10+
Let's see where it breaks it...
> Use the actual sqlite3 headers to get the correct defines.

- src/chart1.cpp
The current implementation requires the GPS to work and provide both SOG and COG to establish an MOB route.
There is a clear problem leading to creation of a new MOB waypoint on every timer tick (every second) when any of the 3 forementioned conditions is not met.
There is an increasing number of GPS units not providing COG at close to zero speed as it is impossible to calculate reliably, so the problem would appear even on eg. an anchored boat with otherwise perfectly operational system and ready for a rescue operation.
The solution provided in this PR sure allows for false positives even when undesired, especially with external data feeds, but should make the operation under real world conditions safer and always fix the problem with repeated creation of the MOB waypoints.
> Change the AIS MOB logic

- include/NavObjectCollection.h
- src/NavObjectCollection.cpp
- src/navutil.cpp
Implements an information dialog displayed in case some waypoints were ignored during the import of a GPX file, which is usually the case when they already exist in a layer and turned out to be confusing for the users when done silently.
> Implement information about waypoints ignored during GPX import.

- include/viewport.h
- src/viewport.cpp
Avoids signed vs unsigned comparisons in viewport code.
Using signed typed for lengths in interfaces is becoming more and more encouraged these days.
> viewport: Use signed length and avoid warnings

- src/LLRegion.cpp
This PR fixes a portability issue. Not all STL implementations use a circular list implementation. The behavior of decrementing past the head or incrementing past the tail is undefined. MSVC never implemented the list object as a circular linked list.
> Handle iterators going off the end of the list in a portable way.

- plugins/dashboard_pi/src/instrument.cpp
Critical members were not initialized in constructor. Sometimes instrument could be drawn before GetSize() was called thus causing an uninitialized variable trap.
> Initialize m_DataHeight in constructors.

- plugins/grib_pi/src/GribOverlayFactory.cpp
Hi,
Trivial  but with very small grib area O was returning a puzzling overlay too big error.
Regards
Didier
> don't fail if grib overlay size start small

- include/OCPNPlatform.h
- src/OCPNPlatform.cpp
- src/chart1.cpp
- src/navutil.cpp
- src/options.cpp
Fix issues in portable mode like:
BasemapDir=F:\PortOCPN\gshhs\ 
Don't fix the same issue in WMM: I think we need plugin API change 
WMMDataLocation=F:\PortOCPN\plugins\wmm_pi\data\
I think we need a plugin API change so portable mode is detectable?
> Correct and clean up portable file savings

- include/chartimg.h
- src/glTexCache.cpp
Hi,
There's a missing virtual  in ChartBaseBSB chartpix_to_latlong declaration.
Remove what's look like a workaround for it when trying to call chartpix_to_latlong in a derived class (ChartPlugInWrapper).
Regards
Didier
> Chartbase thinko

- CMakeLists.txt
- include/options.h
- src/DarkMode.h
- src/DarkMode.mm
- src/chart1.cpp
- src/chcanv.cpp
- src/navutil.cpp
- src/options.cpp
I personally prefer the black window decorations always, but especially in night mode the default macOS light titlebar is annoying...
With this change:
Without this change:
There is still a lot of room for improvement in the dark modes, especially on macOS where wxWidgets toolkit does not exactly shine in combination with the theme support provided by the OS.
> Implement optional dark window decorations on macOS

- src/chcanv.cpp
1) When dragging a route point, the legs around this point are not selectable. The dragging action is not correctly ended.
2) If a route point is selected and drag-handle icon is shown, then a double click/tap anywhere deselect the point but the drag-handle icon stay visible.
2) when a route point is selected and drag-handle icon is shown, then a rightclick/long touch keep the selection witch can make confusion.
These small patches propose a solution to correct that
JP
> Correct somme mal-function related with touch mode and draghandle

- plugins/dashboard_pi/src/baro_history.cpp
- plugins/dashboard_pi/src/baro_history.h
- plugins/dashboard_pi/src/wind_history.cpp
- plugins/dashboard_pi/src/wind_history.h
Addresses #808. On Windows calling the local timezone function is expensive. This optimization eliminates thousands of such calls for every Draw() event. Should improve performance under any other OS as well.
> Optimize history graphs by avoiding thousands of calls to OS TZ func

- CMakeLists.txt
Minor fix needed on my MacOS environment, for some reason /usr/local/include is not added by any thing so even if exif is installed there the build fails. (MacOS 10.13.5)
Fixes Issue: #1109
> Add EXIF_INCLUDE_DIR to search path.

- plugins/chartdldr_pi/src/chartdldr_pi.cpp
- plugins/chartdldr_pi/src/chartdldr_pi.h
- src/wxcurl/base.cpp
Hi,
Cleanup, a bug in wxcurl (we don't use this method) and when downloading a list start to download next item in the background before unziping. 
This one really help with the next patch: keeping curl handler around between requests with a c++11 shared pointer, eg for using http 1.1 pipeline aka faster downloading of NOAA grib subset and co.
Regards
Didier
> Downloader cleanup

- plugins/grib_pi/src/GribV1Record.cpp
Hi,
It seems they don't use only one idModel, there's also 149 but because it's the only entry for idCenter 98 catch all idModel
Regards
Didier
> EMCWF generatingProcessIdentifier (idModel) isn't constant

- src/canvasMenu.cpp
this Pull request contains two patches
1)A small correction for Windows to apply correctly sub menu font when sub menu contains only check or radio items
2) A proposal for improvement
When right click or long touch on multiple object types, we get only one menu and this could be boring because if we don't get the desired menu, we have to zoom to separate (if possible) the different objects then click on the wanted one.
This patch adds as sub menus the menus of others objects which are selected under the cursor/thumb . For example, if we right click on an AIS target and there is a route under this target, we get now the AIS menu as before plus the route menu as sub menu, so we can access either the AIS menu commands or the route menu commands.
The main menu is systematically added as sub …
> Context Menu Changes 

- include/s57chart.h
- src/routemanagerdialog.cpp
- src/s57chart.cpp
- src/wxsvg/include/wxSVG/NodeList.h
- src/wxsvg/include/wxSVG/SVGElement.h
and implement sorting using `std::sort`
- Fixes build with current wxWidgets codebase (there are some breaking changes in dynamic array implementation which may be reverted or fixed to be backward compatible again at some point, but as all this is deprecated anyway, I simply replaced the problematic bits with normal stdlib stuff)
- This is C++11 code, so by merging it we really do cut off C++03-only compilers...
- The change to wxSVG is just making it compile, we do not use the affected code so eventually it will get addressed in a different (and better) way the next time we merge with upstream.
> Replace some wx arrays with std::vector

- src/wxcurl/base.cpp
- src/wxcurl/wx/curl/base.h
This fixes warnings like the following warning with clang.  These warnings represents a portability problem, in that compilers on other platforms (or even GCC/clang with -fshort-enums) could choose a different size for the enum.
> /tmp/OpenCPN/src/wxcurl/base.cpp:500:19: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
>     va_start(arg, info);
> Fix undefined behavior caused by use of va_start with types requiring default argument promotion.

- src/ais.cpp
The relevant wanting, which outlines how it could be used uninitialized:
```
/tmp/OpenCPN/src/ais.cpp:989:12: warning: variable 'theta' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
if(!g_bInlandEcdis){
^~~~~~~~~~~~~~~
/tmp/OpenCPN/src/ais.cpp:1022:29: note: uninitialized use occurs here
float sin_theta = sinf( theta ), cos_theta = cosf( theta );
^~~~~
/tmp/OpenCPN/src/ais.cpp:989:9: note: remove the 'if' if its condition is always true
if(!g_bInlandEcdis){
^~~~~~~~~~~~~~~~~~~
```
> Provide a default value for theta so it can't be used uninitialized below.

- plugins/grib_pi/src/GribV2Record.cpp
The test here is never true, because p2 is a zuint.  I'm a bit unclear on what the intended behavior actually was, since this check can never have actually worked.  Given that it never worked, I think it's safe to assume nobody has ever found a test case where it would trigger.
> Remove dead code.

- src/ConfigMgr.cpp
- src/navutil.cpp
- src/options.cpp
Correct default from 50 to 0.05
Check and correct old scrap from testers config.
Check and correct user abnormally setting in options.
Make all string consistent to three decimals.
Note: My max value on values check is 0.6. Pls change if also abnormal??
> Correct; WP arrival circle default, add watchdogs, string consistency

- src/CanvasConfig.cpp
- src/chcanv.cpp
Improve error checking of chart group ids
When starting MUI branch using an old opencpn.ini created by latest master branch the chart group ID is not always initialized and causes a crash.  This will cause grief as new users switch from non-MUI to MUI mode.
> Be sure canvasConfig.GroupID is always initialized

- src/AISTargetQueryDialog.cpp
If a waypoint is made from an ais-target, give it an decent name. (Now there is no name)
> Give a waypoint from an ais-target an usefull name.

- plugins/dashboard_pi/src/dashboard_pi.cpp
- src/chart1.cpp
Any device sending VAR=0.0 can be assumed to not really know what the actual variation is, so in this case we use WMM if available. This can happen for old GPS navigators without an updated WMM table. For certain devices are the only available options to send 0.0 or a manual variation.
Also a heading from some system can read RMC from the GPS and use that variation to create the HDG.
> Expect a variation = 0.0 to be a fake from a device wo updated wmm table

- src/TCDS_Ascii_Harmonic.cpp
FS#2425 - Tides ans current off by 1 hour in Newfoundland
With an negative fractional hours the minutes were added instead of substracted so -03:30 bcoming -3 + 30 = -2.5 hours
I didn't find any complications but maybe there are.
> Correct Newfoundland TC bug

- src/chcanv.cpp
The intended behavior is only for Ctrl-M/Cmd-M to do so
> Prevent Enter key from dropping mark at cursor

- src/TrackPropDlg.cpp
Currently the timestamp field in track properties dialog is too short. This makes using the dialog painful especially on touch devices where resizing the columns can be hard.
This change makes the timestamp field wider so timestamps are displayed. Additionally the column creation is factored out to a helper function to reduce copy-paste code.
> TrackPropDlg: Make timestamp column wider for common timestamps

- src/chart1.cpp
- src/chcanv.cpp
During destroy of the chart canvas wxWidgets tries to show the MUI bar that was just destroyed.
Reset pointers a little earlier so that this is no longer an issue.
> Fix two ordering issues in destroy

- include/ocpn_plugin.h
- include/pluginmanager.h
- src/glChartCanvas.cpp
- src/pluginmanager.cpp
Add virtual bool RenderGLOverlayMultiCanvas(wxGLContext *pcontext, PlugIn_ViewPort *vp, int max_canvas);
Required for radar_pi to display radar overlay in both canvasses
> Add multi canvas rendering to API 116

- include/NavObjectCollection.h
- src/NavObjectCollection.cpp
- src/chart1.cpp
- src/navutil.cpp
Saves status for "Show wpt names" for a Persistent layer into config so the same status is reloaded on next session.
> Save layer's show wpt-name status to config

- src/routeprop.cpp
If a waypoint is part of a layer it is more logic to open it on the description page as it is anyhow impossible to make changes to the properties. (And rather often layer waypoints do have a description)
FS#2357 - Change the behaviour of waypoints part of a layer
> Open WptDlg on description page if wpt is part of layer.

- include/AIS_Decoder.h
- src/AIS_Decoder.cpp
- src/navutil.cpp
Recently I came in contact with the Royal Dutch Lifeboat Association(KNRM). The KNRM is running 48 lifeboat station with voluntary crews. Most lifeboat station use OpenCPN to track there boats when in action. For this tracking 10+ base stations do have AIS receivers and the data of this receivers is merged and made available to every station. This leads to a few attention points that don't bother an ordinary user to much.
First the huge number of targets (4000+) also gives a larger number of corrupted messages. Most of the time a corrupted message will be blocked by the nmea checksum being wrong. However the checksum is relative small (255) which means there is a change of 1 : 255 (0.4%) that a corrupted message does have the correct checksum. And wit a lot of data this does happen.
The …
> Royal Dutch Lifeboat Association

- src/AISTargetListDialog.cpp
- src/ConfigMgr.cpp
- src/OCPNListCtrl.cpp
- src/chart1.cpp
- src/navutil.cpp
- src/toolbar.cpp
The column order, in the AIS target list dialog, will now be saved and reloaded in the same way as the column width.
> AIS target list dialog, save columns order

- src/CanvasConfig.cpp
Hi,
If opencpn.conf is missing.
Regards
Didier
> canvas config uninitialised values if there's no config file (valgrind)

- src/chcanv.cpp
This way a plugin can get the canvas clicked with PluginGetFocusCanvas()
Currently a right button click does not set focus. Therefore the plugin is ignorant of the canvas on which the context menu is clicked. Normally windows applications do set focus with a right button mouse click
> Set Focus on the canvas when right mouse button is clicked.

- src/OCPNPlatform.cpp
In testing latest master I found it is possible for gLocale to be blank in config file. In the Windows build it remains blank so makes UI difficult to use.
> Handle case where configuration Settings/Locale is empty for MSW build

- include/ocpn_plugin.h
- src/pluginmanager.cpp
This change to the API allows a plugin to determine if OCPN is closing down, by effectively exposing the state of g_bquitting which is used by OCPN internally. Currently a plugin only knows it has to 'deactivate' but not why. For inter plugin communications it allows sensible decisions on how to react, i.e. if user deactivated plugin then a warning message about the impact on other plugins can be issued, but if the system is shutting down then there should be no message. This also impacts information saved into the conf/ini file as there is a difference between the two reasons for deactivation.
I have come across this issue with the integration of Squiddio and OD where OD is providing the POI for Squiddio. If the user deactivates OD then the system needs to revert to OCPN Waypoints, but …
> Provide API call for plugins to determine if OCPN is shutting down

- include/ocpn_plugin.h
- src/pluginmanager.cpp
New API call to allow a plugin to find the canvas on which the mouse is. Allows plugins to then provision windows, i.e. rollover info boxes on the correct canvas and associated with the mouse.
> Mousecanvas

- CMakeLists.txt
- include/AIS_Decoder.h
- include/OCPN_Sound.h
- include/SystemCmdSound.h
- include/options.h
- src/AIS_Decoder.cpp
- src/ConfigMgr.cpp
- src/OCPN_Sound.cpp
- src/SystemCmdSound.cpp
- src/chart1.cpp
- src/chcanv.cpp
- src/navutil.cpp
- src/options.cpp
- src/pluginmanager.cpp
Make command line editable by expert user
Play most sounds so as to not block the UI.
Do not start another alert sound until previous is finished.
Use native Windows createProcessA() instead of system() because
then we don't see a popup window flash.
Now multiple instances of SoundFactory() objects can play at the
same time.
Do more runtime checks and less conditional build sections.
Prevent creating large number of command windows.
Allow spaces in the sound file path.
Break do_play() into 2 distinct functions Win/non-Win
Note: Will not compile with VS2013 due to use of safer snprintf().
> Improve command line sound system.

- src/options.cpp
When more than one screen is used.
By pressing add connection in the options dialog, ReCalculateSize() could possibly reposition the dialog outside the screen.
> Options dialog outside screen

- src/chartdb.cpp
Using linux wxWidgets was trowing in an assert. Was an easy fix.
> preventing wxWidgets assert for wxString.Printf() linux

- CMakeLists.txt
- src/chartsymbols.cpp
- src/libtess2/CMakeLists.txt
- src/myiso8211/ddfsubfielddefn.cpp
- src/wxcurl/base.cpp
Fix misspelled and copied __GNUC, use memcpy instead of strncpy
in some late code.
Mute the libtess warnings about delete on void* pointer during
current cycle. Needs better handling after 5.0.0.
Builds without warnings on gcc 8.2.0.
Someone should IMHO give at least the MacOS/clang build some love....
> Warnings: Fix gcc 8 warnings.

- include/Layer.h
- include/NavObjectCollection.h
- include/RoutePoint.h
- include/routemanagerdialog.h
- plugins/wmm_pi/po/wmm_pi.pot
- src/Layer.cpp
- src/NavObjectCollection.cpp
- src/navutil.cpp
- src/routemanagerdialog.cpp
- Convert the label-changing buttons to checkboxes to make the functionality clear
- Switch the label visibility to three states
- all visible
- all hidden
- honor the settings from the GPX file
> Enhance the layer WPT visibility logic

- include/concanv.h
- src/concanv.cpp
- Step 1 to #1260 implementation (To be finished at some later moment as we currently don't have any framework to collect and calculate performance averages)
- Clicking on the console cycles between the speed used for the calculations, instead of the original 2 states it now has 4
| <img width="94" alt="screen shot 2019-02-23 at 7 46 21 pm" src="https://user-images.githubusercontent.com/249856/53292649-58790080-37a4-11e9-8114-ec96a4a41678.png"> | <img width="101" alt="screen shot 2019-02-23 at 7 46 14 pm" src="https://user-images.githubusercontent.com/249856/53292650-58790080-37a4-11e9-93c1-5139806b0f74.png"> | <img width="95" alt="screen shot 2019-02-23 at 7 52 38 pm" src="https://user-images.githubusercontent.com/249856/53292667-a2fa7d00-37a4-11e9-9bde-61dbc150aa7d.png"> | <img …
> Implement switchable SOG/VMG for TTG calculation in console window

- include/Osenc.h
- plugins/grib_pi/src/GribRequestDialog.cpp
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
- src/ChartDataInputStream.cpp
- src/OCPNPlatform.cpp
- src/Osenc.cpp
- src/Quilt.cpp
Hi,
- A trivial memory leak.
- On window you can't delete an open file, xz compressed chart is using a temporary file and was trying to delete it while open. 
The same issue exists with Osenc temporary SENC/foo.000 (delete in ingestcell while open) but fixing it is way more intrusive and it's not that bad as with xz, it's always using the same name.
Regards
Didier
> Memory leak and deleting open files

- src/FontMgr.cpp
Undefined behavior sanitizer noticed the usage of wxNode (should have been wxFontListNode), cleaned code up and avoided casts.
> FontMgr: Avoid incorrect types and superfluous casts

- include/glChartCanvas.h
- src/OCPNPlatform.cpp
CPN_GLCaps includes at last one class (wxString Renderer) which needs
its constructor to be run (I get a NULL pointer dereference deep in the
libc++ internals otherwise), so make CPN_GLCaps a class too, and allocate
with the new operator.
This is probably dependant on the libstdc++ implementation (the one from gcc 5.5.0 in my case)
> Make CPN_GLCaps a class, fixes segfault

- src/AIS_Decoder.cpp
- src/AIS_Target_Data.cpp
- src/ConfigMgr.cpp
- src/chart1.cpp
- src/navutil.cpp
- Allows overriding the allowed maximum for AIS target tracks via `TargetTracksLimit` variable in `Settings/AIS` section of the configuration file
- Adds MMSI to the name of DSC targets to allow easy identification of the vessels in distress or reporting position
> Enhancements to the AIS and DSC handling as requested by SAR services

- src/OCPNPlatform.cpp
This provides a better result for multi-monitor setups because
gdk_screen_get_monitor_width_mm returns the summary of the width
of all horizontally arranged monitors.
> Use gdk_screen_get_width_mm under Linux

- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/wmm_pi/src/MagneticPlotMap.cpp
- src/chart1.cpp
- src/glTextureManager.cpp
- src/navutil.cpp
- src/options.cpp
- src/pluginmanager.cpp
- src/routeman.cpp
- src/routemanagerdialog.cpp
- src/toolbar.cpp
Hi
- It seems WX 3.1.2 has UI glitches with  the OS progress dialog on Windows.
Use the generic dialog everywhere, it's already the most used anyway.
- some plugins save their config in the DTOR, which is likely a bad idea, but when closing the config was already deleted.
- remove a couple of warnings.
Regards
Didier
> Mui progress dialog

- include/OCPNPlatform.h
- src/OCPNPlatform.cpp
- travisci_build.sh
Hi,
-travis script doesn't always return an error on failure.
for example:
https://travis-ci.org/did-g/OpenCPN/jobs/501481402
should have failed.
- there are ifdef in case wx is compiled without locale but it doesn't compile.
Regards
Didier
> Compiler travis

- include/SoundFactory.h
- include/chart1.h
- src/PortAudioSound.cpp
- src/SoundFactory.cpp
- src/chart1.cpp
I have re-enabled the tests and verified that the sound code seems to work fine under Linux. Attaching the patch which makes the tests available:
[0001-Sound-re-enable-test-code.patch.gz](https://github.com/OpenCPN/OpenCPN/files/2926987/0001-Sound-re-enable-test-code.patch.gz)
However, the actual use of the sound code in chart1 does not match the intended usage pattern. I just missed this part earlier. The top commit changes the old, timer-based code to using the new sound asynchronous capabilities.
Note that  bug basically is platform-agnostic and should hit all platforms  if not fixed.
Also, this PR reverts the earlier fix. This patch has some problems, the basic is assuming that  SoundFactories are either synchronous or not -- this is not correct, and will cause all sorts of problems …
> Sound: new fix for 1277

- src/OCPNPlatform.cpp
- src/RoutePropDlgImpl.cpp
- src/canvasMenu.cpp
- src/chart1.cpp
- src/chcanv.cpp
- src/options.cpp
For some information which platforms define which macros see http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system
Not touching `__UNIX__` for now. 
For both the Linux and Windows define both forms existed in the source, harmonizing to the more "correct" one. For the ANDROID one, it fixes the places where the define has been typoed.
> Fix platform defines

- .travis.yml
- CMakeLists.txt
- include/AboutFrame.h
- include/AboutFrameImpl.h
- src/AboutFrame.cpp
- src/AboutFrameImpl.cpp
Replaces the `wxHtmlWindow` with `wxWebView` for help display to support broader set of HTML features and multibyte Unicode characters.
This can't be merged until support for older Linux distros like Precise and Trusty is completely abandoned as `wxWebView` is not available there.
On Xenial the dependency is `libwxgtk-webview3.0-dev`, while on later Ubuntu releases `libwxgtk-webview3.0-gtk3-dev`. How messy it is on other distributions is unknown ATM...
Once merged, the following further work is needed:
- Update the developer documentation for the added dependency (`libwxgtk-webview3.0-dev` / `libwxgtk-webview3.0-gtk3-dev`)
- Update the PPA packaging scripts for the added dependency (`libwxgtk-webview3.0-dev` / `libwxgtk-webview3.0-gtk3-dev`)
> Use wxWebView for help display

- src/options.cpp
After clicking OK in the mmsi editing dlg nothing was updated (unless you did an explicit update of the mmsi number itself)
> mmsi_prop update after OK Btn click

- src/chcanv.cpp
This is the copy of the 'no touch" code
> Avoid crash when creating a route when the first RP finds a nearby one

- plugins/chartdldr_pi/src/chartdldr_pi.cpp
- plugins/chartdldr_pi/src/chartdldrgui.cpp
- plugins/chartdldr_pi/src/chartdldrgui.h
Allows the user to update the list of support chart catalog sources from the GUI instead of having to replace the data file in the install location.
> Allow chart source master catalog update from the internet

- src/glChartCanvas.cpp
Hi,
IMO Extended Stack should be emptied when switching quilt/single chart mode, but there's way too many branches in that code path to do it
Regards
Didier
> gl canvas don't overlay mbtiles charts in single chart mode

- src/Quilt.cpp
- src/mbtiles.cpp
Hi,
GetNativeScale of mbtiles is currently set to max zoom OSM_zoomScale meaning charts may not be included in the set if a mbtiles is used as reference chart.
Regards
Didier
> if there's other charts in the set don't use mbtiles as a reference chart

- include/Quilt.h
- include/chcanv.h
- src/ConfigMgr.cpp
- src/chart1.cpp
- src/chcanv.cpp
Hi,
Currently JumpToPosition can request very big scales, eg while opening a 110 degrees latitude grib file.
There's code in SetViewPoint for limiting it but it doesn't work in all cases 
`renderable = chartMaxScale * 64 >= VPoint.chart_scale;` 
is part of the problem, a new reference chart is rarely recomputed, but trying to change SetViewPoint code has many unexpected effects.
JumpToPosition has fewer callers.
Regards
Didier
> limit JumpToPosition scale

- src/chcanv.cpp
- src/mbtiles.cpp
Hi,
- In single chart mode projection used is the chart one, ie polyconic, web mercator, whatever but we can't keep it when switching to quilt mode. 
For testing either select a great lakes RNC or a MBTiles and switch between Quilt/Single chart mode.
There's still rendering glitches on switch but they are corrected by panning, zooming or periodic overlay (AIS) rewrite.
- testing a texture is not zero is done in most of O code, do it in mbtiles too, with some c11 cosmetic refactoring anyway  std::unordered_map is c11.
Regards
Didier
> Projection

- plugins/dashboard_pi/src/instrument.cpp
Hi
I discovered a problem with instruments back colour with my Linux Mint machine
This back colour is OK when the instrument is at the first position on the top of a dashboard but no OK  in the others positions You can see this in the two first shots attached and in the next he result of this patch.
This don't happen with W10.
JP![Capture after1](https://user-images.githubusercontent.com/2202442/54748443-f1e3d880-4bd1-11e9-949b-81582de8ec28.png)
> Correct dashboard instruments background colour

- libs/sound/CMakeLists.txt
Hi,
Naming output directory 'build' is not mandatory and CMAKE_BINARY_DIR is used for generating config.h
Regards
Didier
> Use the right directory for libsound include

- src/chcanv.cpp
Both under Linux Mint and Windows 10 when I create a route with very long legs and
whether I click YES or NOT to the great circle asking window, I get a crash.
> Correct Crash when creating long legs routes with touch option set

- src/chcanv.cpp
When creating a multi long leg route in touch mode the drawing is very curious and the length calculation is wrong. I don't know what was the purpose of this small part of code and I didn't find any other effect except destroying the the drawing and the lenght calculation
JP
> Correct route legs drawing when creating long leg routes in touch mode

- include/Quilt.h
- include/TexFont.h
- include/chartdbs.h
- include/glTexCache.h
- include/ocpndc.h
- src/Quilt.cpp
- src/TexFont.cpp
- src/chartdbs.cpp
- src/chcanv.cpp
- src/glChartCanvas.cpp
- src/glTexCache.cpp
- src/glTextureManager.cpp
- src/ocpndc.cpp
- src/s52plib.cpp
Hi,
callgrind and linux perf analysis.
On linux both getmemory and are slow
when profiling zooming with opengl:
- 10% of instructions were in scale text rendering. ==> use cache for all font textures not only s57 charts.
- 20% of instructions were in getmemory ==> only check once per chart not every textures.
Then perf output first line was getChartType ==> convert database values once when loading it not on every get, but I have a lot of charts.
Regards
Didier
> Speedup o50

- include/chart1.h
- src/chart1.cpp
Typo about writing "NMEA" for a variable name is corrected.
> Typo in variable name is corrected

- src/Quilt.cpp
Hi,
A MBTIle can't be a reference chart if there's other charts in the quilt but when zooming on overzoom if it's the largest scale it was selected as the overzoom (rendered) one so
- no reference chart on overzoom  ==> holes ==> filled with cm93, sometime a lot of them ==> big slowdown.
Regards
Didier
> Quilt adjust zoom allow infinite overzoom on the largest scale chart not a MBtile if any

- include/chart1.h
- src/chart1.cpp
- src/chartdb.cpp
Hi,
This revert chartdb.cpp da82d3
Single charts aren't protected by cache reference counting but they can't
be removed from memory.
Quick and dirty fix for #1325 
Currently you can kill O by:
view the ship on screen in single chart mode with a raster chart displayed.
rebuild the texture cache.
once the displayed chart is rebuilt, reference is invalid.
You can do the same with two canvas:
select a single chart in one canvas
move a lot in the second, after a while the single chart will be evicted from the cache.
Regards
Didier
> lock displayed single charts in memory

- CMakeLists.txt
- config.h.in
- include/OCP_DataStreamInput_Thread.h
- include/macutils.h
- src/OCP_DataStreamInput_Thread.cpp
- src/chart1.cpp
- src/macutils.c
Fixes for #1364.
@nohal:  verbose builds: We simply disagree, but you are the maintainer. Case closed.
@did-g: Thanks for good catches!
EDIT: One lesson from this: it's much easier to review config.h than looking for what's defined on the command line in the build logs. So, let's stick to config.h for  new configuration variables.
> Master-1364: Collateral damage after #1298 (#1364)

- CMakeLists.txt
Basically change` /usr/lib `=>` lib`
Closes: #1373 
Possibly related to:  #1370
Note: the Windows build fails, seemingly unrelated to this commit. It fails also on 1667e8cee
> Don't hardcode plugin installation path (#1373).

- CMakeLists.txt
- src/pluginmanager.cpp
Bug: The results from the  CMakeLists code looking for libelf was
not visible in the cpp code. The libelf section was also misplaced
in CMakeLists.
Closes: #1370
> build: Respect USE_LIBELF configuration (#1370)

- plugins/grib_pi/src/GribReader.cpp
- plugins/grib_pi/src/GribRecord.cpp
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribV2Record.cpp
Hi,
Backport grib current polar record to v5.0.x.
Not exactly a bug fix but it's a small patch.
For the summer I put on a site some very high resolution current / wind/ wave grib files. 
Using polar coordinates reduce their size, and if there's a v5.1 release in May/June it'd be great to have it in.
Regards
Didier
> Grib add current polar record type.

- src/Route.cpp
- src/RoutePoint.cpp
Hi,
First leg has no ETA but a valid ETD, update distance must use this ETD otherwise it adds its own route time to its departure time, a bit fragile though.
Fix issue https://github.com/OpenCPN/OpenCPN/issues/1362
Regards
Didier
> Route first eta

- CMakeLists.txt
- ci/docker-build-mingw.sh
- mingw/fedora/README.md
Actually use old the library in the CI build to walk around  #1380 until it's fixed, fixing misspelled option in the mingw ci job. 
While we are on it: CmakeLists: fix a warning and move some misplaced lines.
This should fix the build errors in #1379.
> build: ci mingw bugfix, cleanup (#1380).

- plugins/grib_pi/src/GribReader.cpp
- plugins/grib_pi/src/GribRecord.h
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribV2Record.cpp
Hi,
- GRIB wave:
Opencpn display only one set of wave height direction and period for total sea (ie combined wind wave and swell), for this WW3 model is using significant height +  wind wave direction, MWAM model is using wave period and wave direction. Try to be smart and select the right set...
- thinko: it's not because wind is using polar than current can't, remove the 'else'
- Pressure, if there's only surface level don't fake it as MSL but display it as is.
Regards
Didier
> Grib v5.0.x

- src/chart1.cpp
Fixes #1411 by manually adding an empty "Window" menu to the default menubar on macOS.
> Fix incorrect placement of Window menu on macOS

- src/ConnectionParams.cpp
- src/DarkMode.h
- src/DarkMode.mm
- src/chart1.cpp
- src/navutil.cpp
- src/options.cpp
Improves UI colours for dialogs etc cross-platform, especially on macOS.
- The most-improved platform is macOS 10.14+, where native light and dark modes are now used unmodified.
- Older macOS versions are also much improved.
- Windows 10 is improved, but still far from perfect.
Fixes #1412 – although I would like to do more work on this at some point, potentially fully reworking `DimeControl` and the colour-changing logic in general.
> Improve UI colours and macOS dark mode support

- src/AIS_Bitstring.cpp
Hey @nohal,
seems like a typo or someone forgot to use the `cs` variable.
> unused variable - probably a typo

- src/georef.cpp
Due to the forum thread [http://www.cruisersforum.com/forums/f134/add-second-gps-object-to-opencpn-221605.html](url) I found a problem in some georef functions.
First I found ll_gc_ll_reverse(...) return NAN for (very) small distances. I did correct this by first doing a (very) rough distance calc and then for small distances doing a ordinary mercator calculation. (< 0.1 delta lat or delta lon)
After doing so I found that the bearing returned by the DistanceBearingMercator(...) was constant 180 degrees off. So I did rewrite this function using formula's as they thought me on nautical college.
Did test both functions for all kind of courses and distances in all quadrants. Including greenwich and dateline crossing.
> Prevent nan return from /src/georef.cpp ll_gc_ll_reverse(..) and correct

- src/chart1.cpp
Instead of disabling menu shortcuts if `g_bresponsive` is true, only disable them on Android.
I believe this fix is appropriate. See #1414 for further discussion.
Fixes #1414
> Fix missing menu shortcuts with Scaled Graphics enabled

- ci/travis-build-mingw.sh
- ci/travis-build-osx.sh
- cmake/FindHarfBuzz.cmake
- cmake/FindPANGO.cmake
- cmake/OcpnFindCairo.cmake
- libs/wxsvg/CMakeLists.txt
- plugins/grib_pi/CMakeLists.txt
Recent pango libraries (1.44+) has a harfbuzz dependency.  Add a
new FindPango and FindHarfBuzz cmake finders and use them as
appropriate.
Tested on fedora 31 with pango-1.42.4-2
EDIT: For reference: closes #1453
> Handle Pango >=1.44 Harfbuz dep (Closes: #1453).

- src/Route.cpp
I got tired of adding all the patches to every PR just so the CI builds would complete without errors. This PR will build even though CI doesn't think so.
> Draw route points if they are visible in GL mode same as non GL

- src/AIS_Decoder.cpp
For the mmsi_properties translate AIVDM to AIVDO, do this only for the dynamic position messages, not for the static voyage messages. 
By shifting around a few lines of code it was possible to remove one for/next loop over the mmsi_properties, so it should be a little faster now.
> mmsi_properties AIVDM -> AIVDO

- src/chart1.cpp
- src/navutil.cpp
- src/toolbar.cpp
I do not know the intention of the new MUI – so maybe this is a bad idea? 
However, I think it is handy and it will de-clutter my screen if it is possible to move the main toolbar. Added possibility to move the toolbar by dragging it. To keep the new layout it is without the GrabberWin by simply dragging in topmost part of the toolbar win.
> MUI move the main toolbar.

- src/chart1.cpp
Latest version of wxWidgets will cause lots of warning messages because it cannot seek on /proc type files. This PR simplifies reading /proc/self/statm and it uses sysinfo to access installed system RAM.
> Refactor Linux version of GetMemoryStatus()

- CMakeLists.txt
Makes a build with all warnings enabled so we can start care about
them. Not enough to solve #1267, but still a small step in the
right direction.
Cherry-picked from #1457
> build: Add a OCPN_PEDANTIC config variable (#1267).

- CMakeLists.txt
- ci/travis-build-mingw.sh
- include/datastream.h
- include/options.h
- src/AIS_Decoder.cpp
- src/ConfigMgr.cpp
- src/ConnectionParams.cpp
- src/DetailSlider.cpp
- src/ais.cpp
- src/chart1.cpp
- src/datastream.cpp
- src/navutil.cpp
- src/options.cpp
- src/pluginmanager.cpp
Fixes mingw build errors as described in #1469, but in a slightly more long-term solution (f30)
F30 will be EOL around late spring -20. By then we need to have some kind of decision if/how the mingw builds should be used. It is possible to get a more long-term solution by moving to centos, but this will require rebuilding a lot of packages.
> Mingw build error fix (see #1469)

- src/options.cpp
I don't know when this bug was introduced. Saw it first time after today's master fetch:
The AutoHide checkbox was given an ID for no reason(?) and the ID was mixed up with another control and created the bug as of the shot below. (The "extra" autohide was not responsive)
After fix:
> Options AutoHide. Fix checkbox ID mix up

- CMakeLists.txt
- ci/travis-build-osx.sh
- include/ocpn_plugin.h
- include/pluginmanager.h
- include/semantic_vers.h
- src/AboutFrame.cpp
- src/pluginmanager.cpp
- src/semantic_vers.cpp
- src/testvers.cpp
Add some new attributes to the plugin API to establish a full plugin semantic version. Displays the complete plugin version and also makes the plugin API version visible in both Options | Plugins and About.
The PR closes #1443 and also handles IMHO still valid aspects of #1445.
This PR is not fully coordinated with #1457. Depending on which is merged first there is some rebasing to do.
> Version: Extend plugin version info API  + display extended version info

- src/pluginmanager.cpp
- in API116 support for RenderOverlay() and RenderGLOverlay() was no longer continued. However to provide continuity for older plugins these functions should be supported. The omission of RenderOverlay() and RenderGLOverlay() has not been noticed before, plugins using the api116 will be using the MultiCanvas versions of the above functions. However in later api versions these functions will be missed,  lacking these functions plugin code has to be converted from RenderGLOverlay to RenderGLOverlayMultiCanvas.
> Restoring RenderOverlay() and RenderGLOverlay()

- include/ocpn_plugin.h
- include/ocpn_types.h
- include/pluginmanager.h
- src/pluginmanager.cpp
- src/routeman.cpp
- SetActiveLegInfo() : directly send active leg info to plugin without loss of precision.
- ZeroXTE() : set XTE to zero from plugin, same as from context menu.
These functions are meant for a route following plugin, that controls an autopilot. With these functions the plugin has direct access with full precision to the active leg data, without having to do all calculations again. A plugin using this info can continue to use the OpenCPN active route window and context menu. The XTE in NMEA0183 is rounded off to 0.001 nm. To exactly follow a route a XTE a better precision is required.
This PR replaces PR #1506 (closed)
> Add active leg data functions to API117:

- plugins/dashboard_pi/src/nmea0183/dpt.cpp
Dashboard now silently removes any extra '-' in the DPT message.
> Navico instruments sometimes corrupts DPT offset field.

- include/zeroconf-detail.hpp
I had to patch one header file to build under Windows.  Would not build without this fix.  I have not checked every single files for a similar issue but don't think any others have the problem.
> One signalK include file did not identify WIN32 build

- src/pluginmanager.cpp
> Plugin Manager: Avoid referencing dead stack variable

- src/PluginPaths.cpp
Closes: #1566
Untested, the chocolatey servers are down. However, it's already broken so it shouldn't get worse. Looks good to me, though.
> PluginPaths.cpp: Fix broken windows data path (#1566).

- src/PluginPaths.cpp
> PluginPaths: Don't add extra /opencpn to path (#1535).

- include/pluginmanager.h
- src/pluginmanager.cpp
Without this change 'LateInit' is only called when OpenCPN starts up which impacts on the usability of plugins if they are communicating with each other. Example Squiddio and ODraw.
> Fix to ensure 'LateInit' is called for a plugin if it is enabled after OpenCPN has started

- src/ConfigMgr.cpp
- src/chart1.cpp
- src/navutil.cpp
Hi,
With multiple canvas global g_Group_index variable isn't used anymore.
Fix a regression with -unit_test_2. (it'd only display charts in active group).
Regards,
Didier
> Remove g group index

- src/PluginPaths.cpp
Fix horrible bug using find_last_of() instead of rfind().
Thanks to: transmitterdan for finding it.
See: https://github.com/OpenCPN/OpenCPN/commit/8f9a11e36dfa8918f9d
> PluginPaths: linux: Fix bad PATH setup.

- include/catalog_mgr.h
- include/download_mgr.h
- src/catalog_mgr.cpp
- src/download_mgr.cpp
The ui  still needs overall changes before actual bugs can be handled. Here are some:
- Refactor the initial catalog window to two separate ones (advanced/simple).
- Make some parts a little more dynamic.
- Clean up parenthood mess (again...)
- Various cleanup and minor fixes.
> Ui: Refactoring and clean-up

- include/catalog_parser.h
- src/catalog_parser.cpp
An attempt to simplify the new code in catalog_parser.cpp related to #1627. 
I have not tested this, I presume you have the test setup. Pretty confident though, besides a small uncertainty about the IsSameAs() semantics. Should be obvious if I got it wrong.
> C++fixes:  catalog_parser simplified code using c++ tools.

- src/OCPNPlatform.cpp
Compare Issue 1628 and more. Will set the option true when not on a touch screen. Or leave it set if the user has explicit set it also on the touch screen.
> Set EnableRolloverBlock on first time use when not a touch screen

- INSTALL
- data/doc/toolbar_buttons/tides_and_currents.html
sudo is best for all ubuntu users.
And docu mini-fix.
best regards,
Florian La Roche
> use "sudo" in install instructions, fix typo in docu

- include/catalog_handler.h
- include/catalog_parser.h
- src/catalog_handler.cpp
- src/catalog_parser.cpp
- src/download_mgr.cpp
- Use standard containers to drop duplicates
- Add undocumented OPENCPN_COMPAT_TARGET environment variable
test hook.
- Simplify (again) catalog_parser, move the recursive mechanics to catalog_handler.
For me, this is in a better shape. Show scrollbars where it should, at least on windows and linux.
macOS has an extremely annoying bug where the advanced catalog window disappears when it gets the focus(!). Need someone who understands macOS to cope with this; a working build chain shouldn't hurt either. However, this is *not* blocking, testing can proceed despite this by clicking the (invisible) window..
> catalog_parser: Rewrite meta-url code using real recursion.

- src/NetworkDataStream.cpp
This looks like a misplaced "break;" statement.
Can someone who sees strange items with lost connections try out this patch?
best regards,
Florian La Roche
> fix "break;" statement for lost connections

- src/pluginmanager.cpp
This looks like another missing "break;" statement for OpenGL-enabled plugins of O.
best regards,
Florian La Roche
> add missing "break;" for plugin-manager

- data/ocpn-plugins.xml
The old version crashed when loaded into xenial. New version is built
on an updated xenial host from same sources, and is verified in the plug-mgr branch.
> ocpn-plugins.xml: Update squiddio to 1.0.18.2 for xenial

- plugins/chartdldr_pi/src/chartdldr_pi.cpp
Show chart list during bulk download.
Remove redundant call to FillFromFile().
Optimize bulk download to save time when no charts will be updated.
> Improve feedback to user during bulk chart update

- include/dychart.h
- libs/serial/src/serial.cc
- plugins/dashboard_pi/src/dial.cpp
- plugins/grib_pi/CMakeLists.txt
- plugins/wmm_pi/CMakeLists.txt
Looking at the automatic Windows/Apple builds, the following cleanup
patches reduce warnings in the build logs.
best regards,
Florian La Roche
> code cleanup for the Windows/Apple builds

- src/AIS_Target_Data.cpp
Opening an AIS object properties dialog was giving an wxwidgets allert warning. Easy fix.
`ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type
BACKTRACE:
[1] wxString wxString::Format<long, long, int>(wxFormatString const&, long, long, int)
[2] AIS_Target_Data::BuildQueryResult()`
> wxWidgets Allert warning.

- plugins/dashboard_pi/src/clock.cpp
- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
- plugins/dashboard_pi/src/depth.cpp
- plugins/dashboard_pi/src/instrument.h
- src/chart1.cpp
- src/pluginmanager.cpp
First part of SignalK support for Dashboard.
Missing NMEA0183 messages on SignalK are so far: MTA, MWD and not less XDR. Let's see what future can offer. No further instruments for dedicated NMEA2000 data added so far.
Tested on Win and RPi. Please test of MacOs.
> Implement signalK support in Dashboard plugin II

- include/PluginHandler.h
- include/ocpn_utils.h
- src/PluginHandler.cpp
- src/chart1.cpp
- src/download_mgr.cpp
- src/navutil.cpp
- src/ocpn_utils.cpp
- src/pluginmanager.cpp
Check not only operating system but also version before deeming a plugin as compatible (that is, loadable).
The previous code which basically checked for Mint and used Ubuntu in this case case been removed, mostly because it wasn't possible to determine the version to use this way.
New code checks that operating system and operating system version are compatible with the  plugin by comparing the configuration constants  PKG_TARGET and  PKG_TARGET_VERSION with plugin metadata.
There are two ways to override the default checks:
- By setting compatOS and compatOsVersion in the configuration file manually (there is yet
no GUI). This overrides the PKG_TARGET\* variables.
- By setting the OPENCPN_COMPAT_VERSION environment  variable. This is used like
OS:VERSION for example Ubuntu:16.04
Closes: …
> Check also version in compatibliity check (#1681)

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
- Check reasonably temperature values. Null is sometimes passed through SignalK
- Decreased number of decimals for Baro pressure
- Adjust Barometer gauge scale to show 1013 hPa as middle position.
- Implemented new 40 sec watchdog to prepare for non nautical data from SignalK. (Often defaults to 30 sec)
> Check reasonably Barometer pressure due to Pa-hPa mismatch in SignalK.

- src/canvasMenu.cpp
One more missing "break;" in the current source.
> missing "break;"

- CMakeLists.txt
Allows setting of wxWidgets version for compile when more than one version is installed in Linux.
> Fix forcing of wxWidgets version

- CMakeLists.txt
Always bundle the crude GSHHS data -- an opencpn installation
without this would have big problems zooming in to installed
chart sets.  Higher resolutions are available using the
downloader, and there is no need bundle these in build. 
Closes: #1712
> CMakeLists: Drop OCPN_BUNDLE_GSHHS option (#1712).

- src/safe_mode.cpp
Make No the default option, so users just clicking don't are surprised
by missing plugins etc.
Add a timeout to the dialog for use-cases where it's hard/impossible to
click buttons.
The latter become messy since the standard wxMessageDialog cannot handle
timeouts. Thus the dialog is rewritten as a basic wxDialog. It certainly
looks worse than the standard dialog, but it does support timeouts.
> safe-mode: Make no default, add timeout (#1705).

- src/chart1.cpp
There seems to be no usage  of wxNO_DEFAULT related to
TimedHTMLMessageDialog besides the new safe_mode code. So it
seems safe to apply this patch.
> chart1: TimedHTMLMessageDialog: Fix timeout return (#1705).

- data/opencpn.appdata.xml
The CC0-1.0 license was an oversight from my side. I have the
copyright and is thus free to relicense this file. Using the
overall gpl-2+ license simplifies license handling downstream.
Closes: #1490
This is cleanup targeting next downstream Debian release.
> Relicense opencpn.appdata.xml CC0-1.0 -> gpl-2+ (#1490).

- src/pluginmanager.cpp
Extend the logging when loading plugins to get the data needed to verify plugin metadata including:
- Plugin's name as of GetCommonName().
- The extended semantic version available from API 117+.
Both of these items need to match the metadata file -- not logging them causes uncertainty and doubt.
Closes: OpenCPN/plugins#27
> logging: Log plugin name and extended version (plugins #27).

- .circleci/config.yml
- ci/generic-build-mingw.sh
- src/OCPNPlatform.cpp
Add part  simply missing + a bugfix affecting macos plugins.
While on it, also update the mingw builder to resurrect these builds.
With these patches, I can see that at least the radar plugin locates it's data directory.
> PluginPaths et. al.: Fix broken macos plugin datadir (#1751)

- .travis.yml
- CMakeLists.txt
- ci/control
- ci/generic-build-debian.sh
- ci/generic-upload.sh
Patches adding a new build target named bionic-gtk3. Together with #1758 this should be the last bit in the overall echosystem.
The patches adds a build to travis. Here is also some bugfixes and cleanup in the generic-upload.sh script.
As a final part, the PKG_TARGET is adjusted on wxgtk3-based builds.
Only tested to the point that bionic-gtk3 builds starts. It doesn't list any plugins (there are no bionic-gtk3 plugin builds available).
This PR will (probably) have some conflicts with #1758. Depending on which is merged first, the other will need to be rebased.
> Build a new bionic-gtk3 target linked to wxgtk3 (#1715)

- CMakeLists.txt
Fix problem with  check_debug_support() in CMakeLists, writing temporary files in source directory.
> build: Don't write in source directory.

- src/OCPNPlatform.cpp
Update to use '/etc/upstream-release/lsb-release' to find upstream distribution release number
> Update to handle Linux Mint upstream release

- include/georef.h
- src/georef.cpp
While improving the algorithm for mercator course and distance, I didn't notice the difference in sequence of arguments between the greatcircle and the mercator function. (For greatcircle it is first lat/lon departure then lat/lon destination, and for the mercator first destination then departure. Grr)
The result is a bearing/course which is 180 degrees of.
> Correct a 180 degrees bearing error.

- src/AIS_Decoder.cpp
This is a fix for a buffer overflow which can occur in the AIS_Decoder:Decode function if the NMEA sentence is malformed. For more details see issues #1738.
> Bugfix for buffer overflow in AIS_Decoder::Decode

- include/pluginmanager.h
- src/pluginmanager.cpp
Give the user a hint to update the plugin catalog at first visit to Options->Plugins for one O session.
I also decreased the border around the plugin catalog handling to give some more space for the plugins. Especially valid for small screens, e.g. RPi 7 inch.
First visit:
After update:
> Options->Plugin Plugin catalog adaptive status text

- src/ais.cpp
The core code is viewing the EU Inland blue sign also on the special message "reserved"=3. Should be on message = (1) or (2) only.
> AIS: Correct the use of blue paddel

- src/tcmgr.cpp
Just to see how it works I made some arbitrary commits for the implementation of logger.
I just searched in src for the most hits on stderr and replaced the most obvious.
Choice of replacement from fprintf(stderr, ..) with LOG_ERROR( .. ) is mostly arbitrary.
Feel free to reject / ignore
> Redirecting messages from stderr to LOG_INFO for tcmgr.cpp

- src/pluginmanager.cpp
@bdbcat 
I hope this works on all platforms.  I added a "get out of jail" step in case it should try to become an infinite loop as a defensive measure.
> Clear plugin list cleanly

- src/LLRegion.cpp
Last one of the rewrites to include Log_Info in favor of a write to stderr.
One liner, no real advantage except more consistent information to the logfile.
Only here 2 lines of code were changed to one.
> 	modified:   LLRegion.cpp

- include/options.h
- src/options.cpp
Move CM93 slider to show up on the same page as the other two. Even if the function is not exactly the same the user experience are similar.
New users find it not consequent to have the three sliders at different menu locations.
> Move CM93 Detail slider to Display->Advanced

- src/chart1.cpp
I honestly don't remember why I placed the check for  previous crash
before checking if another instance is running. This patch puts the
crash check after the duplicate instance check, solving #1797, possibly
causing other headaches which I don't foresee.
> chart1: Test for crash after checking another instance (#1797).

- src/OCPNPlatform.cpp
Create the GetPrivateDataDir() dir if it doesn't exist at startup.
Closes: #1840
> OCPNPlatform: Ensure private data dir exists (#1840)

- src/OCPNPlatform.cpp
- src/PluginHandler.cpp
The discussion in #1852 reveals three things which needs to be fixed in the flatpak builds:
- Plugin installer cannot handle a ./ prefix paths.
- Plugin installer still has some logging to stdout.
- Using the same configuration directory for "traditional" installations and flatpaked  carries too many risks.
Here is three commits trying to cope with this. The change of configuration directory is perhaps the most important one.
> Flatpak 1852

- plugins/dashboard_pi/src/baro_history.cpp
- plugins/dashboard_pi/src/compass.cpp
- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dial.cpp
- plugins/dashboard_pi/src/instrument.cpp
- plugins/dashboard_pi/src/nmea0183/sentence.cpp
- plugins/dashboard_pi/src/wind_history.cpp
This PR removes the concept that 999 or 9999 indicates invalid or missing NMEA data.  Now we exclusively use NaN to indicate data is missing or invalid.  This eliminates complaints that things like pressure and knot logs are limited to 999 or 9999.  Now there are no limits to NMEA instrument values.
Made the use of "---" to indicate missing or invalid data more consistent.
Also, apparently some old files contained CRLF instead of LF.  This PR removed the CR which makes the diff huge.  Look at the diffs ignoring whitespace to see the code changes which are minimal.
Tested on Windows and Linux.  Not tested on MacOS or Android but should nothing changed is OS dependent.
> Dashboard cleanup

- libs/garmin/jeeps/garmin_gps.h
- libs/garmin/jeeps/garminusb.h
- libs/garmin/jeeps/gpsapp.c
- libs/garmin/jeeps/gpsprot.h
Refactor the garmin lib, basically to conform with C standards. 
This is about gcc-10 being more picky about how external variables are defined and referenced.. See https://gcc.gnu.org/gcc-10/porting_to.html, the Default no-common part.
Closes: #1846
> libs/garmin: Fix GCC 10 FTBS

- flatpak/org.opencpn.OpenCPN.yaml
Add -DOCPN_CI_BUILD to flatpak builds so we get a better feeling for what we actually are running.
> flatpak: Add CI build info.

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dial.cpp
Dial is used for Speedometer, Barometer etc.
> DB: Omit residual values on Instrument_Dial at watchdog timeout.

- src/ais.cpp
The AIS realtime prediction can surprisingly be triggered off by small movements at e.g. anchor. This patch uses the value at "Suppress anchored/moored targets, speed max (kn)" as a low limit condition for the realtime prediction function. 
The "Suppress anchored/moored...." function does not need to be checked. Only the value in the speed limit field is used.
> Avoid realtime prediction from anchored targets

- src/chart1.cpp
- src/compass.cpp
When a user want to toggle Color scheme, by a tools click or F5, a common request would be:
On evening one toggle to dusk.
It's getting darker, toggle to night.
Morning to come. Toggle to leave darkest night scheme but Ooops. Day light on screen!
Would have expected dusk again until the sun is up and the last toggle for this night.
Present toggle scheme:
Init 		 : GLOBAL_COLOR_SCHEME_DAY
first click : GLOBAL_COLOR_SCHEME_DUSK
second click: GLOBAL_COLOR_SCHEME_NIGHT
third click : GLOBAL_COLOR_SCHEME_RGB  (This is a day scheme on chart but dimmed compass.)
fourth click: GLOBAL_COLOR_SCHEME_DAY  
Bug: Compass is always "one step behind"
After the patch: 
Init 		 : GLOBAL_COLOR_SCHEME_DAY
first click : GLOBAL_COLOR_SCHEME_DUSK
second click: GLOBAL_COLOR_SCHEME_NIGHT
third click : …
> Adjust color scheme toggle function

- .gitignore
- CMakeLists.txt
- cmake/dist_target.cmake
- cmake/gitcheck.cmake
- cmake/version_git.cmake
- cmake/version_git.in
- flatpak/.gitignore
This PR resolves #1872, rectifying the empty tarballs created by `make package_source`. It also adds the usual `make dist` target.  The latter warns if git status isn't  clean. It also adds some info on the git commit in the source tarball, a trick somewhat messy to do when relying on git-archive.
Closes: #1872 
EDIT: this could  be postponed to next cycle without problems, should the beta imminent.
> Fix broken source tarball generation

- CMakeLists.txt
- libs/iso8211/src/ddffield.cpp
- libs/iso8211/src/ddfsubfielddefn.cpp
- libs/libtess2/Source/CustomArray.cpp
- libs/wxservdisc/CMakeLists.txt
- plugins/dashboard_pi/src/dashboard_pi.cpp
- src/GarminProtocolHandler.cpp
- src/OCPNRegion.cpp
- src/ais.cpp
- src/bbox.cpp
- src/chart1.cpp
- src/concanv.cpp
- src/glChartCanvas.cpp
- src/tcmgr.cpp
A bunch of patches from the downstream Debian packaging. Notably linking issues as discussed in #1889 and also gshhs bundling as discussed in #1875. EDIT: #1750.
The latter drops the configuration option completely, always bundling the crude data.
EDIT: the latter just sets the defaults to bundling gshhs and tcdata.
The rest should be trivial. some bugfix and a bunch of fixed warnings -- it now builds cleanly on sid.
Note: All of these patches have been applied to the downstream packaging branch. Accepted or not, they can still be simple downstream patches. This also means that they can be cherry-picked, should you want to.
Also note: the downstream package is by no means set in stone. It can be modified, we are still on a beta cycle.
Closes: #1889
> Debian downstream packaging fixes.

- CMakeLists.txt
- ci/circleci-build-flatpak.sh
- ci/generic-build-flatpak.sh
- data/opencpn.appdata.xml.in
- flatpak/Makefile
- flatpak/org.opencpn.OpenCPN.yaml
- org.opencpn.OpenCPN.yaml
Some fixes to the flatpak toolchain + #1908 which I thought was merged when https://github.com/OpenCPN/OpenCPN/pull/1910 was merged. However, this PR contained 0 (zero) commits, so something went terribly wrong here. Probably my doing, testing the flatpak branch is a complicated mess of forced pushes.
Anyway, some polish to the flatpak toolchain and a fix for  #1908. Nothing here should affect anything but the flatpak build besides the #1908 fix.
Closes: #1908
> Flatpak fixes (again)

- src/glChartCanvas.cpp
This is a proposed fix for a scaling issue in the real scale vector ship display described in issue #1895 .  It looks like only a scaling of the x scale factor was being applied in the polygons.  This led to the ship being proportional to its breadth but not respecting its length.  Scaling is applied in this PR to each point of the polygon before polygon creation.  It also applies to the points of the line cross.
> Fix for incorrectly scaled vector ship shape

- CMakeLists.txt
This reverts commit e041ba0932c9d157e5f79e1d7b36a40cb1b4d8dd.
Renaming the appdata file to opencpn.metainfo.xml seems to break undocumented (?)
features of flatpak-builder(1), eventually ending up in file not being processed.
EDIT: Closes: #1919.
> Revert "Rename appdata.xml to metainfo.xml on linux install." (#1919).

- data/opencpn.appdata.xml.in
Two patches for the appdata metainfo from the upcoming flathub package at https://github.com/flathub/flathub/pull/1533. 
Only affects the software stores in Debian (Linux in general) and flatpak.
> flatpak: Flathub fixes.

- flatpak/README.md
- flatpak/org.opencpn.OpenCPN.yaml
- flatpak/src/0008-flatpak-Add-a-shell-wrapper.patch
- opencpn.1
- src/chart1.cpp
The main purpose is to check that the installed flatpak version is recent enough to avoid problems described in #1934. The fix is somewhat generic, opening a path for wrappers to trigger an arbitrary fatal error message using an environment variable.
While on it, fix some docs and remove large and useless gtk3 headers from installed package.
The changes on the main opencpn code  (1133692) are minimal and seems IMHO safe.
Closes: #1934.
> Flatpak: Check flatpak version >= 1.2.0 (#1934)

- src/SignalKDataStream.cpp
easywsclient doesn't directly close socket-fd on calling close() which leads to lingering
sockets if deleting the object without going through poll() to wait for the ready-state CLOSED.
---
Details:
Noticed on my idle signalk-server that the websocket connection count was constantly growing.
sockstat / lsof showed dozens of connections coming from opencpn. OpenCPN runs into a timeout
when it gets no data from SigK, closes the socket and reopens a new connection.
Unfortunately easywsclient seems to be broken. It doesn't close the socket upon destruction
of the instance. One needs to go through WebSocket::close() and then poll() and wait until the
readystate changes to CLOSED before deleting the instance.
Changed WebSocketThread::Entry accordingly.
> Changed termination of SignalKDataStream on websocket:

- libs/garmin/CMakeLists.txt
- libs/garmin/jeeps/garminusb.h
- libs/garmin/jeeps/gps_wx_logging.h
- libs/garmin/jeeps/gpsapp.c
- libs/garmin/jeeps/gpscom.c
- libs/garmin/jeeps/gpsdatum.h
- libs/garmin/jeeps/gpsmath.c
- libs/garmin/jeeps/gpsmath.h
- libs/garmin/jeeps/gpsprot.c
- libs/garmin/jeeps/gpsread.c
- libs/garmin/jeeps/gpsrqst.c
- libs/garmin/jeeps/gpssend.c
- libs/garmin/jeeps/gpssend.h
- libs/garmin/jeeps/gpsserial.c
- libs/garmin/jeeps/gpsserial.h
- libs/garmin/jeeps/gpsusbcommon.c
- libs/garmin/jeeps/gpsusbcommon.h
- libs/garmin/jeeps/gpsusbint.h
- libs/garmin/jeeps/gpsusbread.c
- libs/garmin/jeeps/gpsusbwin.c
- libs/garmin/jeeps/gpsutil.c
- libs/garmin/jeeps/gpsutil.h
- src/garmin_wrapper.cpp
Various updates to the garmin library to enhance the logging. In short:
- Enhance error messages, in particular include messages from underlying layers.
- Use the c++ compiler instead of plain C, requirement to....
- ...remap the GPS_ XXX logging calls to the regular wxWidgets logging framework.
- Fix some potentially very dangerous handling of va_list and friends.
For now, please handle this PR as an aid in handling #1495 
Please note that to enable full logging opencpn needs to be started with `--loglevel debug`
> Garmin library logging fixes (#1957).

- libs/garmin/jeeps/gpsserial.c
These are not required for things to work according to done tests.
However, seems safe and might add some leeway on other platforms not
yet tested.
See: https://stackoverflow.com/questions/13013387
> libs/garmin: Add some delays (#1957).

- src/pluginmanager.cpp
Debugging plugin installation problems is hard since the plugin manager rightfully removes all traces of failed installation attempts. Add an undocumented environment variable OCPN_KEEP_PLUGINS which makes opencpn leave the failed plugin installation in place to be examined.
> plugins manager: Add OCPN_KEEP_PLUGIN debugging.

- .travis.yml
- ci/travis-build-mingw.sh
Simple fix to handle the missing /sbin/init in the fedora 31 docker
image.
Closes: #1982
> ci: Fix mingw build (#1982)

- flatpak/org.opencpn.OpenCPN.yaml
Add portaudio to the flatpak dependencies which enables the portaudio
sound backend when configuring.
Closes: #1995
> flatpak: Add portaudio sound (#1995)

- buildosx/OpenCPN.pkgproj.in
Not just remove the file, also drop it from buildosx/OpenCPN.pkgproj.in.
Closes: #2006 
Successful build: https://travis-ci.com/github/leamas/OpenCPN/jobs/365332988
> macos: Drop bogus .svgo file (#2006).

- cmake/GetArch.cmake
Clean up current mess in cmake/GetArch, making *make install* work better one more platforms.
Closes: #1488
> build: Clean up cmake architecture detection (#1488).

- src/PluginHandler.cpp
It turns out that before sid is branched, the version identifier is
"sid" rather than "11". Without patch sid loads gtk2 plugins ->
undefined behaviour (icons disappear, cannot leave the options
menu).
Fix is applied in downstream Debian package.
This will eventually break after bullseye is branched. However, it will
not happen overnight and bullseye (11) will be ok.
See: #2033
> PluginHandler: isCompatible(): Fix Debian sid compatibility (#2033).

- include/ocpn_plugin.h
Just disable the noisy diagnostics.  This is for old parts of the API, it cannot be changed.
Closes: #2025
> ocpn_plugin.h: Mute useless clang warning.

- src/AIS_Decoder.cpp
A suggestion to solve the missing update of a changed AIS ship name.
I've no idea why and when this stopped to work but now there's no update of the non confirmed hash list and thus no update of the confirmed list. So a changed ship name is never updated in the mmsi(to)name-file.
> Add a changed AIS ship name to the not confirmed list

- src/SignalKEventHandler.cpp
A possible solution to this CF post: https://www.cruisersforum.com/forums/f134/bug-opencpn-sees-a-fix-while-gps-data-are-not-consistent-240313.html#post3243707
> SignalK Don't parse a null position lat/lon

- plugins/dashboard_pi/src/dashboard_pi.cpp
- src/SignalKEventHandler.cpp
- src/chart1.cpp
Correct SignalK GPS Watchdog to also make GPS Icon, COG and SOG not valid.
The GPS Watchdog was kept alive by "0" values for COG and SOG.
Changes:
- Don't use SOG or COG from SK when position is not valid, i.e GPS Watchdog is released. They have a all time value >= 0.
- Don't use a "0" value for number of satellites in view.
- There's no obvious reason for COG or SOG to update the GPS Watchdog.
- Correct Dashboard to not use SK values position NULL and meanwhile neither SOG nor COG.
> Sk gps watchdog

- CMakeLists.txt
- ci/generic-build-flatpak.sh
Use the appdata name instead, using the metainfo name was premature.
This should satisfy both the needs for flatpak (fully qualified name on org.opencpn.OpenCPN) as well as Debian (desktop and appdata should files should have the same basename).
Closes: #2069
> Flatpak: Install appstream metadata as appdata.xml instead of metainfo.xml (#2069)

- src/NavObjectCollection.cpp
Allows validation of GPXX tags in OpenCPN GPX files.
> Update NavObjectCollection.cpp to allow validation of GPX with Garmin extensions (GPXX) 

- libs/nmea0183/src/rmb.cpp
- plugins/dashboard_pi/src/nmea0183/rmb.cpp
This patch may fix: FS#2723 - NMEA RMB wrong waypoint IDs
The RMB fields 4) and 5) are switched at several places.
> Correct inversely positioned To and From info in NMEA0183 RMB messages

- .circleci/config.yml
- ci/travis-build-mingw.sh
Update for the decommissioned Fedora image used in the mingw builder. While on it, merge the two files used to build mingw to a single one using a bash HERE doc.
Closes: #2119
> CI: mingw updates

- libs/gdal/src/cpl_conv.cpp
There is a small typo in libs/gdal/src/cpl_conv.cpp.
Should read `introduced` rather than `introdiced`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, introdiced -> introduced

- include/chart1.h
- plugins/chartdldr_pi/src/chartdldrgui.cpp
- src/ConnectionParams.cpp
- src/chart1.cpp
- src/pluginmanager.cpp
Fixes for https://www.cruisersforum.com/forums/f134/invisible-text-in-mac-os-catalina-opencpn-5-2-a-243433.html
The colors for the dialogs are managed centrally through `GetDialogColor`, so we can work on getting rid of all the direct calls to `GetGlobalColor()` and get consistency throughout the whole application.
It also probably is a candidate for plugin API export.
> Dialog color fixes

- src/chcanv.cpp
The removed code does interfere with the afterwords implemented feature to have the ship offset in AutoFollow mode.
At zooming to large scales, 2000 - 800, the offset ship can be moved outside the screen edge since the vp is not updated when the ship is moving.
Also is the described "jitters" is no longer detected. I suppose changes implemented after that code has corrected or evened out the "jitters" effect.
> CanvasUpdate: correct large scale interference with Autofollow Offset

- .circleci/config.yml
- ci/circleci-build-flatpak.sh
- flatpak/Makefile
Fix the broken flatpak build reported in #2132. penCPN/plugins/issues/295. This was about multiple errors.
Change the nightly builds so they are installed in the new *devel* branch making it possile to install flatpak nigtly builds in parallel with official builds from flathub.
Here is also several patches which only are in effect when doing test builds. By default, the flatpak packaging builds from the sources at the github master branch. This is correct, a packaging branch like flatpak should package the master branch. However, when testing the packaging there is a need to build from the same sources as the flatpak branch. This is now possible using special environment variables.
In particular, the  "ocpn cloud" test support is conditionalized on the environment and is not used in …
> Flatpak: broken build fixes, build distribution enhancements

- libs/nmea0183/src/gsv.cpp
- libs/nmea0183/src/gsv.hpp
- plugins/dashboard_pi/src/dashboard_pi.cpp
- src/chart1.cpp
Some AirMar instruments do misuse the NMEA0183 GSV message.
The SatsInView info should have been printed in all of 1/2/3 messages in one group. Now they use only message No 1 for that and omit it in message 2 and 3. See message examples below.
The effect of this is the DB instrument Sats in view are fluctuating from 0 to actual value and the O GPS compass staples are also fluctuating.
With this patch we only read the first message of one group. No other harm with that for "normal" GPS. The SatsInView info in message 2(3) is not any new information.
Number of satellites is in field 3.  (here 10)
`12:28:02 $GPGSV,3,1,10,8,13,62,35,13,50,277,39,18,18,324,33,5,53,228,38*48<0x0D><0x0A>
12:28:02 $GPGSV,,2,,7,43,71,39,30,73,107,38,27,13,26,34,15,14,289,37*7F<0x0D><0x0A>
12:28:02 …
> Read SatsInView from GSV message #1 only

- src/CanvasOptions.cpp
@bdbcat this is my idea for harmonizing the alignment flags.  Have tested on Windows, Buster and Focal.  I tried to make the dialog as narrow as possible.  It could be made narrower if we added a \n to this phrase "Minimize less critical targets".
On Focal, the only observation is that after the slide out animation, the dialog box loses focus.  Clicking in the dialog is needed to regain focus.  This may be a GTK3 thing, not sure.
I apologize in advance for my pedantic change of verticle to vertical.  I was hampered by not being able to search for all instances of the word vertical.
> Update flags for pop-out chart options dialog

- CMakeLists.txt
The wxWidgets libraries bundled with OpenCPN are the only ones
available for plugins. Bundling all of them means that the runtime
libs matches the ones used in build time.
Closes: #2153
> macos: cmake: Bundle all of wxWidgets for plugins to use (#2153).

- src/chcanv.cpp
Although I have never seen all three conditions true it would be a typo? (& >> &&)
if(m_glcc && g_bopengl & bNewChart)
> Correct typo in chcanv

- .travis.yml
- include/chart1.h
- src/chart1.cpp
There is an option (hidden) for setting the system time from GPS already available in O. However to prevent loading bullshit times from some devices it has a build in limit of 2 hours difference between system hardware clock and GPS time.
This makes it not useable for systems without system hardware clock (eg Raspberry), where this function is most needed. 
This patch adds a check for an hw clock onboard, and if not forget about the 2 hours limit.
It is linux only, but afaik all small non clock boards are running linux.
> Datetime from gps rpi

- data/opencpn.appdata.xml.in
Fix broken link after update on opencpn.org. While on it, scale
image to recommended size and remove windows decorations.
Closes: #2179
> appdata: Fix broken screenshot link (#2179)

- CMakeLists.txt
- include/catalog_parser.h
- include/download_mgr.h
- include/plugin_cache.h
- libs/picosha2/CMakeLists.txt
- libs/picosha2/LICENSE
- libs/picosha2/README.md
- libs/picosha2/example/hasher.cpp
- libs/picosha2/example/interactive_hasher.cpp
- libs/picosha2/picosha2.h
- libs/picosha2/test/test.cpp
- src/PluginHandler.cpp
- src/catalog_parser.cpp
- src/download_mgr.cpp
- src/plugin_cache.cpp
- src/pluginmanager.cpp
Add  sha2 hash support for downloaded  plugin tarballs, the main opencpn side.
Having working hash checks implies changes both in the plugins and in opencpn. This PR is the opencpn side. It basically adds parsing of the specified but yet not used `<tarball-checksum> `xml element in the metadata and compares this with the hash computed on the actual, downloaded data. A new, header-only library is added to compute the sha2 hash.
While on it, the plugin cache is refactored into a separate object, cleaning up some complicated, duplicated code. 
Testing: attaching  ocpn-plugins.xml with checksums added, The logbook plugin has artificial checksum errors on all platforms. 
Also attaching a test  script which is able to add checksums to an existing ocpn-plugins.xml. It's still 
a bit rough, but …
> Checksum support for downloaded tarballs.

- src/s57chart.cpp
Found a bug that could interfere with proper sorting of light coordinates.
There may be more going on here still but for now this patch kills a fatal exception in DEBUG mode.  The sort function expects the comparison function to return true if (left < right) but this function was returning true if the coordinates were !=.  That could cause the sort function to misbehave.
> Make s57chart::CompareLights obey sorting rules.

- include/pluginmanager.h
- src/pluginmanager.cpp
Pluginmanager Import function now has "GetPrivateDataDir" as the initial directory. It's unlikely a user will save an imported file to a often hidden location. 
Change the default to users "Documents".
Also create a function to save the last used directory for next time import. (If found! Could be a USB stick)
> PM_Import_dialog Change init dir to Documents

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
- src/SignalKEventHandler.cpp
- src/chart1.cpp
Now while using modern GNSS receivers when several GNSS system are available the use of NMEA sentences GSV has changed in its structure. There can be about twelve GSV message every second all including counts of satellites seen for each GNSS system. So numbers of satellites in view can alter between 1 to 14 or so.  
The GGA sentence though is used to indicate satellites in use for the fix calculation. The talker is then GN, GNGGA, indicating several GNSS system are used for the fix. 
Since both OCPN core and Dashboard now use both GGA and GSV simultaneously to catch satellites used for the upper right "GPS  bar" and the instrument "GPS in view" the result is a frequent "jumping".
This patch includes:
- Added a prioritizing so if GGA is present we prefer that before GSV for "satellites in …
> GNSS. Prefer the number of satellites in use from ..GGA instead of ..GSV

- src/SignalKEventHandler.cpp
- src/chart1.cpp
The last part of this after SignalK updates. Next SK release will also include NMEA0183 GGA more reliable. This PR adjust also O's prioritization between "satellites in use" and "satellites in view".
Again; the reason for this is the new GNSS receivers message xxGSV and "Satellites in view" for each satellite system in a sequence that can make the GNSS status icon to flicker. Therefore it's better to favor "Satellites in use" from GGA when available. 
"Satellites in use" (for the fix calculation) reports the counts of the "best" satellites from all available system used for the fix calculation
> Adjust also SK-GGA-GSV prioritization to OCPN after SK's last updates

- src/multiplexer.cpp
Fix bad mistake in  e89af69, checked errno instead of return code r.
While on it, make sure we don't log perfectly valid ENOENT from readlink
when fed with non-device stuff like TCP:whatever.
Clean up a little, move declarations to where they are used since method
now is longer.
Tested in #2202
> multiplexer: bugfix, don't log non-existing link, cleanup (#2202).

- include/canvasMenu.h
- src/Route.cpp
- src/canvasMenu.cpp
The right-click context menu has a new option : Split ....
As an example let's start with a route namex with the points A;B;C;D
If we right-click on the point B, then select "split at waypoint"
the route  becomes:
first route namex-A  with A;B and  second route namex_B with B;C;D
this is exactly what does the split function in the route properties dialog
If we right-click on the leg B to C, then select "split around leg"
the route becomes:
first route namex_A with A;B and the second route namex_B with C;D
in this case the leg clicked B to C has disapeared
> Split a route by right-click on a route point or a leg

- .travis.yml
There is cruft, probably caused by at rebase, which causes a bogus
travis build to start. Nuke it.
> travis: drop cruft causing a bad build.

- src/chart1.cpp
- Remove the duplicate Enter Full Screen menu item on macOS.
- Enable native full screen method when full screen is triggered from context menu etc.
Fixes #1413
> Fix fullscreen on macOS

- src/PluginHandler.cpp
Log location of metadata file actually used for debugging purposes. The entry is `    wxLogDebug("Using metadata path: %s", metadataPath.c_str())` i. e., the logging is only done when invoked  with `--loglevel debug`.
While on it, fix a corner case for unsupported platforms (compiler warning).
Closes: #1805
> Log metadata file (#1805)

- cmake/FindLibudev.cmake
Fix bad package name to find_package_handle_standard_args().
Closes: #2290
> cmake/FindLibudev.cmake: Bugfix (#2290)

- buildosx/OpenCPN.pkgproj.in
- ci/generic-build-macos.sh
- cmake/FindPANGO.cmake
Fix  a new cmake bug which seems to have surfaced after the 69228f627 fix.
While on it, add an alternative installation path for the pango headers. Hasn't arrived to Debian yet, but will no doubt do later.
Closes: #2300
> Ci macos 2300

- include/routeman.h
- src/MarkInfo.cpp
- src/canvasMenu.cpp
- src/chcanv.cpp
- src/routeman.cpp
I propose here another solution to include a Way  Point in an existing route. Instead of creating a new insert functionality,
I propose this patch:
- The insert functionality is not changed
- When a route point is being dragged, and the drag ends near another point, it is proposed to replace it by the nearby one.
- the nearby one is inserted and the dragged one is deleted
- Assuming that an originally manually created point could be important, there is a double validation in this case
to ovoid deleting it unintentionally.
- Activated points are excluded of this functionality
The code has been tested on Linux Mint - Ubuntu and Windows 10
OSX is excluded . I have neither knowledge nor device for this platform
Added improvement for Insert and Reverse functions
Insert : add the possibility to …
> Solution to #FS2648 

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/rudder_angle.cpp
RUDDER is a valid angular transducer type for the XDR sentence (tested with B&G Zeus3).
Text display in dashboard includes sign of angle unfortunately (due to structure of dashboard_pi), but I followed the example of the other angular instrument displays and included the '> Stbd' and '< Port' unit.
I'll probably do a PR later to remove the sign from the angle display.
> Add RUDDER to XDR in dashboard_pi

- src/chart1.cpp
- src/options.cpp
If you have a compass connected (nmea $xxHDG) but no WMM plugin running the heading is not used for a heading line and rotating own ship icon. Seems logical as you want a true heading on the chart.
However it is still not drawn if there is a manual setting available for the variation.
This commit will allow to use the user setting, at least if it is not 0.0 (the 'factory' setting). 0.001 will do.
> Draw heading line without WMM PI, if userset variation is available

- .clang-format
Avoid problems with clang-format not being forward-compatible as
described in #2360. This from clang-format 1.11.
> .clang-format: Downgrade to version 11 (#2366).

- CMakeLists.txt
- src/chcanv.cpp
- src/glChartCanvas.cpp
This makes the popup come with long press,
which is usefull when using a touchscreen
without an additionnal mouse.
Tested on a Lenovo T480 with touchscreen lcd.
Signed-off-by: Thierry Bultel <tbultel@free.fr>
> Enable popup upon long press event

- src/chcanv.cpp
- src/s57chart.cpp
The Objectwuery for vector charts is well known and also use to show additional information files. However for raster charts and mbtiles this doesn't work. There are no objects offcourse but sometimes there are additional info files.
This commit wil show those additional infofiles if available. If not, then nothing will happen. If only one file is attached it will be opened right away. 
If charts are shown using a plugin then the plugin is responsible for the objectquery info.
Commit has been tested on linux using ENC, KAP CM93 , mbTiles and O-chart_plugin
An example with a mbtiles chart using public available radar scan information for the netherland
s
> Add "object query" to show additional files for rastercharts and mbtiles

- plugins/dashboard_pi/src/gps.cpp
- plugins/dashboard_pi/src/nmea0183/gsv.cpp
- From different "new" GNSS receivers I've seen GSV sentences without any satellites with a valid Signal to Noise Ratio. These messages are not valuable for our GNSS status instrument but more disturbing. This commit sort them out before being processed by the preparser function.
- Minor text adjustments.
> DB: GNSS Status instr: Omit GSV messages with all SNR fields empty.

- cmake/TargetSetup.cmake
- include/OCPNPlatform.h
- src/OCPNPlatform.cpp
- src/PluginHandler.cpp
The 5.6.0 MacOS  will use wxWidgets 3.1.5.   This requires a new ABI spec, so that old clients does not try to load the wx 3.1.5 plugins and the othwer way around.
See: https://github.com/OpenCPN/plugins/pull/452
> MacOS: use new ABI specification darwin-wx31

- src/chcanv.cpp
The new function allowing to insert or happen a route (or part of) in the new route being created works well. But there is two situations where it can create mistake or at least confusion.
1)when the user create a point  and try to use a nearby point already belonging the new route .Answering Yes to the question "Insert or happen (part of ) this route ... " means inserting  the new route into the new route...
1)when the user create a point  and try to use a nearby point which is the last point of another route. In this case, there is nothing to insert/happen. Answering yes or no is the same but it could be confusing
This patch eliminate this two situations
> Don't allow "Insert/Happen (part of) this route ..." to ovoid mistake or confusing situation

- CMakeLists.txt
Only apply nasty fix for old cmake which requires it.
Closes: #2400
> Build: Don't use nasty fix unless needed (#2400).

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/nmea0183/mda.cpp
- plugins/dashboard_pi/src/nmea0183/mda.hpp
Late change but some users with old instruments complained the air temperature was not shown in Dashboard. 
Added MDA: AirTemp although this is an obsolete sentence. 
Used the watchdog according to non navigational data.
> DB: Add $xxMDA airtemp as source

- .circleci/config.yml
- ci/circleci-build-flatpak.sh
Update the TLS certificates before use to avoid errors described in #2419.
Incorporate the flatpak build in the ones done when updating master so errors gets noticed also here.
Closes: #2419
> Ci flatpak tls 2419

- src/Track.cpp
Hi all,
I realized while sailing that sometimes the GPS receiver for some reasons has an error in the localization and put my boat 300-400 km for the current position... This does not stay for long maybe 1/10s or less but this draws a very weird track line and make the log completely wrong (I can sail a 1000 Nm in 2h...).
My suggestion is that no boat can travel as fast so this fake GPS point should be skipped in the track. 
What do you think ?
> Do not add false GPS point in the track when error

- src/S57QueryDialog.cpp
As heading says: keep the consistent clang-format style broken by #2425.  While on it, drop  useless _T() macro in the new parts. 
No manual changes besides the _T() part. Part of a missionary mission...
> Format PR 2425

- include/routemanagerdialog.h
- src/canvasMenu.cpp
- src/routemanagerdialog.cpp
Looking at https://www.cruisersforum.com/forums/f134/new-insert-waypoint-feature-260769.html there is a complaint about the question on renaming the waypoints when inserting a waypoint in an existing route. This new feature indeed gets irritating when inserting many waypoints. I would think it is better to take the question on renaming out at this point.
But as there could be a need to rename (with numbers in sequence), an additional button for renaming in the Route & Mark Manager could be useful (alternatively one could reverse a route twice).
In this PR I removed the renaming question from the insert and added a button for renaming in the Route & Mark Manager.
> No rename waypoints on insert

- include/navutil.h
- include/options.h
- src/chcanv.cpp
- src/navutil.cpp
- src/options.cpp
Add a new UI setting which handles how "fast" the zoom is when using the mouse. Avoids problems described in #2557 for those who finds the setting.
Sreenshot with new setting:
> Mouse zoom sensitivity (#2557)

- plugins/grib_pi/src/GribV2Record.cpp
MeteoFrance has changed its models definitions
CLOUD is at LV_GND_SURF and not displayed.
> Meteofrance new models definitions

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
- plugins/dashboard_pi/src/gps.cpp
- plugins/dashboard_pi/src/nmea0183/gsv.cpp
Abstract:
- The GNSS satellites in view received from Signal K, SK, previously didn't contained info about NMEA0183 Talker ID. Talker ID for sentence GSV is rare since it contains navigation info instead of only "type of talker". In this case origin satellite system like GPS and Galileo. The "Talker" is now available also from SK (NMEA0183) and the code is updated to handle that.
- What's not yet tested is GNSS info parsed from N2k PGN's via CanBus to a SK path. So far due to lack of real test data. We've to trust the SK specification will be valid also here. Let's hope for future test participating and possible correction. I've though seen some N2k->NMEA0183 converters not meeting the NMEA standard and thus we also receive limited info.
- During the SK talker update a bug in the …
> GNSS status. SK adaptation and bug fix.

- plugins/grib_pi/src/CursorData.cpp
- plugins/grib_pi/src/CustomGrid.cpp
- plugins/wmm_pi/src/wmm_pi.cpp
- src/AIS_Target_Data.cpp
- src/TCWin.cpp
- src/TrackPropDlg.cpp
- src/chart1.cpp
- src/chcanv.cpp
- src/navutil.cpp
Most "\u00B0" moved outside Format-strings. My (Buster/Bullseye)-GCC and wx3.0 wasn't happy with the "\u.." format.
> Move hex degree sign out of Format strings

- include/config_var.h
- src/config_var.cpp
- src/options.cpp
- src/pluginmanager.cpp
This is an attempt to fix #2605. 
Note:
- I cannot reproduce the bug described in #2605 and thus cannot really test this.
- The fix is somewhat dirty and will not scale well.
A better approach might be some kind of listener instance which removes itself from the ObservedVar when destroyed. However, this is substantially more  code so this might be better explored in the 5.8.0 cycle. This patch is aimed for 5.6.2, trying to keep it minimal.
> ObservedVar: Handle windows going out of scope.

- plugins/dashboard_pi/src/gps.cpp
- plugins/dashboard_pi/src/gps.h
Our Dashboard instrument GNSS Status views 12 satellites only and is of course a compromise.
When the receiver reports more than 12 satellites it uses two groups of GSV messages. The first group with up to 12 and the other with the rest. The second group is though "overwriting" the first group and what we see are the "worse" only. 
This PR is sorting the second group out. (We have to priority :)) 
Compare these GSV sequences:
```
$GPGSV,3,1,11,02,07,130,20,06,21,090,24,12,75,223,30,17,21,042,27,1*6E<0x0D><0x0A>
$GPGSV,3,2,11,19,37,056,27,22,21,317,23,24,56,151,24,25,33,248,34,1*60<0x0D><0x0A>
$GPGSV,3,3,11,32,34,300,39,03,02,018,,10,00,000,,1*52<0x0D><0x0A>
$GPGSV,2,1,06,03,02,018,,06,21,090,,10,00,000,,24,56,151,,8*6D<0x0D><0x0A>
$GPGSV,2,2,06,25,33,248,,32,34,300,,8*67<0x0D><0x0A>
``` …
> DB: GNSS status; Show the first (12) group only

- cmake/CompilerSupport.cmake
-msse flags are often silently accepted by compilers that don't
actually support SSE. This results in build failures later on
when the actual SSE intrinsics are not available.
Instead, make use of CMake's symbol-detection builtins to check
for the relevant headers and preprocessor definitions.
> Fix CMake compiler extension checking to be more reliable.

- src/ConnectionParams.cpp
The culprit is that wxStaticText for some reason does not respect the font when calculating the minimum width, at least on GTK. Issue is present also in recent GTK 3.1.5.
Work around using a new bold label class.
Tested on Windows, Flatpak, Focal, and MacOS.
Closes: #2538
> Connection parameters: unreadable data fix (#2538)

- CMakeLists.txt
- include/plugin_blacklist.h
- include/pluginmanager.h
- src/plugin_blacklist.cpp
- src/pluginmanager.cpp
Create a separate blacklist object, avoiding the plugin renaming in #2516. 
The blacklist contains both hard-coded and dynamically added entries. It provides a basic framework which could be expanded with user GUI feedback and/or configuration files blacklisting.
Closes: #2516
> Re-factor plugin blacklist (#2516)  

- include/bbox.h
- src/bbox.cpp
wxWidgets has deprecated wxTransformMatrix object used by now deprecated MapBbox() function.  So just remove MapBbox() altogether to avoid future confusion and compiler errors.
> Removed unused/deprecated function MapBbox()

- cmake/GetArch.cmake
- cmake/TargetSetup.cmake
The Debian .deb package generation requires som support variables.
These have been setup in cmake/GetArch, but this is just not logical
since they depend on the target being Ubuntu/Debian rather than
the architecture.
Move the code from GetArch to TargetSetup, re-factor and simplify
remaining code in GetArch.
Builds with a Debian/Ubuntu/Raspbian target, implicit or set
using OCPN_TARGET_TUPLE, will build a .deb package.
EDIT: This patch has been applied to the Debian Buster backports to
make it possible to build also on Raspbian.
Closes: #2549
> cmake: Refactor target-related variables setup (#2549).

- libs/wxsvg/CMakeLists.txt
The two files NSIS.template.in.in  and plugins/chartdldr_pi/src/icons.bat does not match the declared properties in .gitattributes. Use _git add --renomalize_ to create a sane tree which can be used to make PRs from
libs/wxsvg/CMakeLists.txt is written by me as visible in the git log. Claim the copyright to keep the overall wxsvg library legal status ok.
> libs/wxsvg: Claim leamas's copyright, renormalize

- data/opencpn.appdata.xml.in
Warnings from debian checks -- the GUI install is not able  start the program.
EDIT: This fix is applied to downstream Debian packaging.
Closes: #2503
> Fix wrong desktop filename in appdata (#2503).

- .circleci/config.yml
- ci/circleci-build-flatpak.sh
Cache the builds to avoid re-building wxWidgets et. al. each time. Still a slow build due to the two slow uploads to RPi-3 boxes, but shaves off some 10-15 minutes build time.
EDIT: there is more work to be done to make this faster, but we should IMHO first merge this.
Closes: #2475
> ci: Flatpak: Resurrect caching (#2475)

- include/ocpn_plugin.h
- src/s57chart.cpp
ListOfPI_S57Obj was never actually defined, nor was the destructor
for PI_S57Obj. This manifested in build errors related to typeinfo
when linking with undefined-behavior sanitizer enabled.
> Fix undefined-behavior sanitizer build.

- include/glChartCanvas.h
- include/plugin_blacklist.h
- src/plugin_blacklist.cpp
C-style types aren't supposed to have public/private declarations.
Virtual base classes need to have virtual destructors to avoid
undefined behavior where delet is called.
> Fix a few warnings reported by clang.

- include/cm93.h
- include/s57chart.h
- src/cm93.cpp
- src/s52cnsy.cpp
- src/s57chart.cpp
wxList is a std::list underneath nowadays, and we're not doing
anything wx-specific that would necessitate a wxList.
> Decommission a wxList in favor of a std::list.

- include/routeprintout.h
In the old version, the 'num > 0' check was effectively useless
when or'd with the 'num <= 1' check.
> Fix HasPage() logic to actually make sense.

- plugins/grib_pi/src/pi_ocpndc.cpp
- plugins/wmm_pi/src/pi_ocpndc.cpp
- src/Track.cpp
- src/ocpndc.cpp
This happened to work before because the underlying wx enums
happened to be compatible, but we should really be using the
correct wxPenStyle enums.
> Compare against the correct enum values.

- include/AIS_Decoder.h
- include/AIS_Target_Data.h
- src/AIS_Decoder.cpp
- src/AIS_Target_Data.cpp
Fixed a  bug in persistent track update.
Add aistarget parameter for persistent track controlled by mmsi properties to avoid confusion between that track and the one controlled by AIS Target query.
Add general mmsi properties for AIS targets from a SignalK connection.
Tested on Win and Linux-RPi but not MacOs.
> Update persistent tracks. Add all mmsi-props for SignalK

- buildwin/.directory
- include/AIS_Target_Data.h
- src/AISTargetAlertDialog.cpp
- src/AIS_Decoder.cpp
- src/AIS_Target_Data.cpp
- src/ais.cpp
This tries to fix  [FS2816](https://opencpn.org/flyspray/index.php?do=details&task_id=2816) 
Two parts
1. A DSC distress received from a VHF radio use the present AIS Alert logic and dialog.
This commit correct shown mmsi from the distress target and also if it's a relayed message the relay station's mmsi is shown. 
Also is the nature of distress shown on the alert and the rollover message if included in the DSC messages. 
A DSC alert is active a long time after the message is received. If the user want to close the alert a "Close alert" button is added to the alert dialog.
See picture 1 and 2.
2. The other part take care of the situation when a VHF-DSC alert is received from a ship also present as a AIS target, i.e. the same mmsi. 
As long the DSC alert is active the alert dialog will …
> DSC distress update

- .circleci/config.yml
- src/chart1.cpp
Current state has become hard to read and overall unmaintainable,
with duplicated includes being piled up over time.
Restore the standard language, framework and then other headers.
Sort and remove duplicates.
Part of #2689, but IMHO valuable on it's own merits.
EDIT: While on it¸ add a Bionic build which represents the oldest Linux sources we support (as a replacement for Xenial).
> chart1.cpp: Sort and clean up header mess.

- src/Downloader.cpp
- src/plugin_blacklist.cpp
- src/ser_ports.cpp
gcc 12 comes with some new warnings, generating tons of text. Mute those about regex,  they are deemed bogus. Fix an initialized variable.
> Handle some gcc 12 warnings

- CMakeLists.txt
Closes: #2698
Originally from #2689, but useful in it's  own right
> CMakeLists: Handle FTBFS when OCPN_USE_CURL=OFF

- src/multiplexer.cpp
Fixes #2705
Please check if the solution can be this simple!? 
It works on Win10 for "General" wpl output. (See shot)
Furuno output is still working.
Garmin is "working" but not finalized due to "Time out..." in the log since no Garmin is connected so probably also OK. (Let's hope for testers)
> Take out a doubled definition of the serial Datastream variable: dstr

- plugins/dashboard_pi/src/gps.cpp
Some AIS transceivers are using TalkerID "BD" instead of "GB" for satellite system BeiDou. Even though  it's not described in the NMEA standard I've seen it seems to be a common rule.
This PR add "BD" as a condition to identify the BeiDou system.
Also are some transceivers using a three digit designation for satellite ID, PRN,  especially for the BeiDou system. One mentioned rule is to subtract 100 to get a "normal" PRN number but there are other rules use by single transceivers. I've seen e.g.: "234". To get the PRN number to fit in our GNSS status instrument bottom list this PR use the last two digits instead.  (For 234 use 34)
> GNSS Add extra sat-system BeiDou TalkerID. Print only two digits PRN

- src/AIS_Decoder.cpp
AIS targets can show up using a null or 000000000 MMSI number. The reason for this "misuse" can be discussed but it's there. When one or two targets use a null MMSI number our AIS target name cache list is "screwed up" leading to unexpected behavior.
This PR omits a null MMSI to be added to the target name list.
> Print to AIS target name cache only if the MSSI numberis is valid

- src/BasePlatform.cpp
Without ocpn_plugin.h it still compiles and links seemingly without
errors on VS 2017, but with strange runtime errors on windows when loading
plugins probably caused by missing linker interface info available in
ocpn_plugin.h.
Referencing a method not defined in a header is an error on all platforms, but 
seemingly works everywhere besides windows.
The VS linker is a major trouble being unaware of polymorphism and with overall 
odd behaviour :( However, this fix is sound on all platforms.
Closes discussions in #2731
> BasePlatform: Add missing ocpn_plugin.h header

- src/ais.cpp
With the "new" AIS Class B transponders it's more common Ship Type "High speed craft" are used. This commit aims to apply to that by using the HSC icon also for such a ship.
> Add AIS Class B High speed craft symbol

- src/routeman.cpp
In a rare corner case, trying to stop the ownship track if it is not running results in infinite recursion.
> Do not try to stop a track that is not running

- CMakeLists.txt
- cmake/in-files/config.h.in
- libs/tinyxml/CMakeLists.txt
Make libs/tinyxml using the system  tinyxml library or the bundled one as appropriate. Obsoletes #2786.
> build: Clean up handling of tinyxml (#2786).

- src/glChartCanvas.cpp
Makes OpenCPN start on modern distros with Wayland (Fedora 37 in my case)
More details on the problem in https://github.com/nigels-com/glew/issues/172
> Work around glewInit problem on Wayland

- src/plugin_handler.cpp
Rebased and rewritten
This needs a careful review. 
The assumption is that we will use wx32 ABI subtypes as defined in https://github.com/OpenCPN/plugins/pull/747 on Debian 11/Ubuntu 22.04 where we will have both wx32 used by the PPA version and wx30 used by the official. All other versions is using either wx30 or wx32.
This is also modified to accept the  23.04 and 23.10 interim releases opening a path for users of the official package to use wx32 plugins from April 2023.
Here is also the final clean-up of the #2502 roadmap.  After this, hosts on Debian derivatives like Ubuntu, Mint, etc  only accepts Debian plugins besides plugins built for the host platform. This is sensitive, but is should IMHO preferably be done before the alpha so we can handle issues. All done in separate commits …
> PluginHandler: Update debian -> ubuntu compat table.

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/depth.cpp
Last fix(?). Get rid of all hard coded draw positions. Rely all on system font sizes instead. Would fit all platforms wo specials for WIN.  (Hopefully Android is happy as well.)
> DB: Scale depth graph for all platforms.

- include/ocpn_plugin.h
- include/pluginmanager.h
- src/chcanv.cpp
- src/glChartCanvas.cpp
- src/ocpn_plugin.cpp
- src/plugin_loader.cpp
- src/pluginmanager.cpp
Implement API 1.18 adding plugin overlay rendering in multiple phases of the rendering pipeline
Plugins using older API versions up to 1.17 are unaffected.
Plugins using API 1.18 get a call to `RenderOverlayMultiCanvas`/`RenderGLOverlayMultiCanvas` with a new parameter priority, letting them decide whether they want to render something in the respective overlay layer or not.
This allows plugins to render scene like bellow instead of the current behavior where the plugin overlays are always under ships and UI elements (Which makes the functionality of https://github.com/nohal/dashboardsk_pi impossible to implement properly).
> Extend the plugin API for layered rendering of plugin overlays

- .gitignore
- CMakeLists.txt
- appveyor.yml
- buildwin/win_deps.bat
- ci/appveyor.bat
- cmake/Curl.cmake
- cmake/OcpnFindCairo.cmake
- libs/mongoose/CMakeLists.txt
- plugins/chartdldr_pi/CMakeLists.txt
- plugins/grib_pi/CMakeLists.txt
- test/CMakeLists.txt
build: windows: re-factor to use separate scripts.
Create a separate script buildwin/win_deps.bat which downloads pre-built dependencies. This script can also be run when doing manual builds.
Move the downloaded stuff from buildwin to a new directory cache/. Adding files to a directory mamaged by git is just not the way to do it. Clean up .gitignore, modify paths to libs spread out over the place.
Make sure the wxWidgets libraries are installed when creating the installer.
Fix a long-standing bug when using CI_BUILDS causing a bad  multiline constant in config.h
With these changes, the process to build OpenCPN on Windows should become much simplified.
> Windows build: refactor and bugfixes.

- src/ocpn_frame.cpp
Found a bug in AIS target track deletion.  The YES/NO dialog box needs to be tested for wxID_YES not wxID_OK.
> Fix logic error in persistent track deletion.

- libs/s52plib/src/s52plib.cpp
Plugs the top of the list memory leak reported by the address sanitizer and reduces the memory usage (We were allocating 6 doubles per point, but only 3 are needed).
> Fix memory leak reported by ASAN

- CMakeLists.txt
- cmake/Utils.cmake
- data/opencpn.appdata.xml.in
The appdata.xml generation requires that VERSION_DATE always is available as a cmake variable. However, as of current this is only created when OCPN_CI_BUILD is on.  The variable is also setup in a needlessly complicated way which also seems to fail in some circimstances.
Use CMAKE's string command to set up VERSION_DATE instead of complicated code
Add a timestamp field to the appdata _Release_ section to cover up if Date for some reason is no set in a reasonable way.
This patch is applied to the Flatpak (beta) packaging.
> CMakeLists, appdata: Add required timestamp to appdata

- CMakeLists.txt
- libs/gtest/CMakeLists.txt
- test/CMakeLists.txt
If packaged version of the gtest libraries are available use them instead of downloading sources from github. Likewise, if installed gtest sources (like on Debian) are available, use these instead of downloading.
First patch is applied to pending Flatpak beta release.
> Gtest : use system libraries if available (#2799)

- libs/garmin/CMakeLists.txt
Clang complains about building the header files (and actually fails to build for Apple Silicon). Should not harm anywhere else neither.
> Do not compile jeeps headers

- .gitignore
As discussed in zulip "Master 5.8.8 (was: comms)".  The cache directory contains various temporary large files which should not be part of the git repo.
IMHO, pretty urgent to merge to avoid getting large amounts of junk in the git history.
> .gitignore: Add missing cache directory

- src/concanv.cpp
- src/styles.cpp
Adapt to wxWidgets 3.2.1 for MSW and suppress white lines (partial rectangle) visible when using big font size for values and/or legends
> Correct console display sizing

- flatpak/org.opencpn.OpenCPN.yaml
Downloading from freedesktop occasionally fails when the certificate is not in the list of trusted ones, see
https://github.com/flathub/flathub/issues/3259.
Use work around listed in the same issue i. e., download from the ftp.osuosl.org mirror instead.
Closes: #2871
> CI: Flatpak: Avoid using freedesktop glu download

- cmake/TargetSetup.cmake
The auto-computed target for macos is plain wrong,  hereby fixed.
> cmake/TargetSetup: macos: Fix illegal target darwin-wx321

- src/ais_decoder.cpp
A suggest to solve this [CF issue](https://www.cruisersforum.com/forums/f134/opencpn-version-5-7-1-beta-test-2-a-271721-2.html#post3725827) 
Hopefully LeaseOnLife can test it. I don't think we have a CanDumb available?
> N2k AIS-SART detection in PGN129038

- .gitignore
Quick fix after merging #2936 which basically excluded the _buildwin/_ directory from the git repo, I presume by accident.
> Fix broken .gitignore (#2936)

- src/ais.cpp
If an AIS target is reduced in size, also reduce the size of the prediction circle.
//TODO The line from target to pred.circle is in non OpenGL mode dotted, but in OpenGL mode it is not. I prefer the dotted line, but don't know how to set this in GL mode.
> Adjust AIS prediction circle size for less critical targets

- src/base_platform.cpp
Make sure that GetSharedDataDirPtr(), GetPluginDirPtr() and GetPrivateDataDirPtr() does not return uninitialized values.
Closes: #2619
> base_platform: Ensure valid returns from Get*DirPtr et. al (#2619)

- include/plugin_blacklist.h
- include/plugin_loader.h
- src/ocpn_frame.cpp
- src/plugin_blacklist.cpp
- src/plugin_loader.cpp
Re-factor mark_unloadable in new blacklist to return status, review and re-factor GUI messages.
Basically, restore things as they were before the failed rebase related to the plugin_manager -> plugin_loader refactoring + polish after more testing.
Closes: #2516
> plugin_loader: Drop resurrected jailing code  (#2516)

- plugins/grib_pi/src/grib_pi.cpp
Load a new Grib file added to the repository while O is opened and the Grib_pi is already activated
> Load The latest grib file without reloading OpenCPN (Issue 2773)

- src/s57chart.cpp
Improve the reading/handling of data in the ObjectQuery for tidalcurrent carrots. It seems that not all data is formatted exact the same way for different cells/country's. As far as I can test it does now. Tested with German France and Netherlands charts.
Compare between Objectquery and raster chart.
> Improve Objectquery tidalcurrent

- src/plugin_handler.cpp
Trivial fix to accept plugin abi "all".
Closes: #3020
> plugin_handler: Always accept plugin abi "all" (#3020)

- .gitignore
- flatpak/patches/0002-flatpak-Add-a-shell-wrapper.patch
- flatpak/patches/0101-Add-wxDEPRECATED_EXPORT_CORE-macro-for-wxTransformMa.patch
Adding two missing patch files related to #2992
This went under the radar because .gitignore lists .patch files, probably since old times where we had no  patches in the sources. Fix that.
> Flatpak patches (#2992 update)

- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/GribUIDialogBase.h
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
As there is no immediate solution to fix this size problem, I propose to add a slider to allow Windows users to adjust themselves the icon's size.
It should be suitable for many of the different screen scaled, the different definition etc…that could exist.
> Add  a slider for Windows users to adjust Grib_pi Icons size

- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/pi_ocpndc.cpp
- plugins/grib_pi/src/pi_ocpndc.h
- Fix crash when starting with OpenGL disabled and activating grib plugin
- Reinitialize the context when GL/non-GL mode is switched
> Fix grib plugin problems related to non-GL display

- .github/workflows/windows.yaml
The upload script is designed to allow uploading to other cloudsmith repos then the hardcoded default. This is an important test hook.
Relocating is done using the CLOUDSMITH_REPO environment variable. On GA, make sure that this is visible in the windows build script
See: #3096
> ci: GA: windows: Make CLOUDSMITH_REPO usable (#3096)

- include/conn_params.h
- src/comm_drv_n0183_net.cpp
- src/conn_params.cpp
- src/connections_dialog.cpp
As https://github.com/OpenCPN/OpenCPN/issues/2824 points out, there are use cases where the fact that no data is received over a TCP connection for long periods of time does not mean a problem on the data source side and we should simply keep the connection open and wait.
This patch allows disabling the reconnection function of the watchdog.
We might also consider progressively increasing the watchdog period to limit flooding the logfile with frequent messages.
> Make no data watchdog reconnection optional

- src/canvasMenu.cpp
I know new features would not be implemented close to 5.8 release so please reject if desired.
I was asked to add the key shortcut "W" function to the canvas menu for a non keyboard use.
To not jeopardize Crowdin translations with new strings I've only reused what's already there so gettext will find it.
This reuse of strings also made the menu slightly possible to misunderstand. I find it clear enough. If you judge it misleading I can redo, to "Toggle CPA alarms", and PR it after 5.8 instead?
Picture: The menu click will now toggle to "ON"   (Will print "OFF"  on next turn)
> Add toggle CPA alarm to canvas menu

- plugins/grib_pi/src/CustomGrid.cpp
- plugins/grib_pi/src/GribRequestDialog.cpp
- Add WAVES option to the ECMWF request. Fixes #3132
- Fix the meteotable colors on systems with dark theme
Old colors:
New colors:
> Grib plugin fixes

- src/chcanv.cpp
Implements the workaround for the *2 wrong scale displayed in the MUI bar in GL mode on Retina displays described in #3117
> Workaround the wrongly calculated scale on Retina displays

- debian/control
Changes the dependency of the Debian package to the `wx-i18n` virtual package which should pull in the correct version on every release.
https://packages.debian.org/buster/wx-i18n
https://packages.debian.org/bullseye/wx-i18n
https://packages.debian.org/bookworm/wx-i18n
https://packages.ubuntu.com/bionic/wx-i18n
https://packages.ubuntu.com/jammy/wx-i18n
https://packages.ubuntu.com/kinetic/wx-i18n
https://packages.ubuntu.com/lunar/wx-i18n
> Change dependency for wxWidgets language files. Closes #3164

- plugins/grib_pi/src/GribOverlayFactory.cpp
When The ChartBar in hidden, the "GetChartbarHeight()" return 0;
So we have to evaluate the ScaleBar height to ovoid the line to be written above it.
It would be better to can get the position and size of the ScaleBar from the API,
> Correct Info line position when ChartBar not displayed

- src/ocpn_frame.cpp
I don't particularly like this solution, but it does the job without the need of larger refactoring that could break the other platforms.
> Make the prepare all ENCs dialog window modal on macOS. Fixes #3142

- .github/workflows/MacOS.yaml
- ci/generic-build-macos.sh
- manual/modules/ROOT/pages/mac-osx.adoc
Removes the outdated information from the documentation
Slightly optimizes the CI build script logic to minimize downloads and adds inline documentation to it
> Update macOS build instructions

- app.manifest
This should activate all the state of the art DPI awareness features on all Windows versions, we should aim to require zero user configuration with this manifest and default sizing settings even on Hi-DPI and multi monitor systems.
It does not seem to break the current state on my system (which is not HiDPI and not multi monitor)
> Update the Windows application manifest to support new DPI awareness features

- src/navutil.cpp
Dark system themes nowadays make a better job than we do at saving the eyes on all the platforms.
If we want to revisit this in the future, we should use different logic at least for dark themes and only make bright colors less bright instead of using a custom palette, something like
```c++
#define LUMIMOSITY_NIGHT (-0.8)
#define LUMIMOSITY_DUSK (-0.5)
wxColor GetDimedColor(const wxColor& c, int color_scheme) const
{
switch (color_scheme) {
case NIGHT:
return (
wxColor(wxMax(0, wxMin(c.Red() + c.Red() * LUMIMOSITY_NIGHT, 255)),
wxMax(0, wxMin(c.Green() + c.Green() * LUMIMOSITY_NIGHT, 255)),
wxMax(0, wxMin(c.Blue() + c.Blue() * LUMIMOSITY_NIGHT, 255))));
case DUSK:
return (
wxColor(wxMax(0, wxMin(c.Red() + c.Red() * LUMIMOSITY_DUSK, 255)),
wxMax(0, wxMin(c.Green() + c.Green() * …
```
> Do not dime window if system theme is dark

- src/glTextureManager.cpp
This is a simple point  fix for #2696. I have had  ambitions to do something more about this code which generally certainly could be improved. However, no time, defaulting to the obvious, simple fix.
Closes: #2696
> glTextureManager: Don't delete pointer before last use (#2696)

- CMakeLists.txt
- buildosx/OpenCPN.FrameDir.pkgproj.in
- buildosx/scripts/preinstall
Serves to cleanup possible leftover wx dylibs from the installation target. Fixes #3197
Should be also backported to 5.8.4
> Add preinstall script to the macOS package

- src/MarkInfo.cpp
- src/console.cpp
- src/route_point.cpp
- test/tests.cpp
- Fixes #3209 
- Fixes the related problem with persistence of name visibility settings and it's application on new waypoints
Both should be backported to 5.8.4
> Fix default settings for waypoints

- src/MarkInfo.cpp
- src/console.cpp
- src/route_point.cpp
- test/tests.cpp
> [5.8 backport] Fix waypoint default settings

- CMakeLists.txt
- buildosx/OpenCPN.FrameDir.pkgproj.in
- buildosx/scripts/preinstall
Backport from master, cleanup possible leftover wx dylibs from the installation target. Fixes #3197
> [5.8 backport] Add preinstall script to the macOS package

- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
Satellites in view was sometimes mixed up with Satellites in use.
> Correct GNSS Status instr: satellites in view

- include/comm_drv_signalk_net.h
- include/ocpn_plugin.h
- include/shaders.h
- libs/s52plib/src/Cs52_shaders.cpp
- libs/s52plib/src/Cs52_shaders.h
- libs/s52plib/src/TexFont.cpp
- libs/s52plib/src/s52shaders.cpp
- plugins/grib_pi/src/GribRequestDialog.cpp
- src/TCWin.cpp
- src/chcanv.cpp
- src/cm93.cpp
- src/comm_drv_n0183_serial.cpp
- src/comm_drv_n2k_serial.cpp
- src/comm_drv_signalk_net.cpp
- src/glChartCanvas.cpp
- src/piano.cpp
- src/svg_utils.cpp
The number of warnings has become too large to be able to work with these sources in a sane way. It's time to take care of them.
One set of warnings is non-trivial. in ocpn_plugin.h plugin_118 did hide some methods from plugin_116. The signatures are diffferent, but as the code was written ti did hide the old definitions. The fixes here makes the old 116 methods visible in 118+.
> Fix noisy and mostly trivial warnings

- src/gshhs.cpp
> Get rid of atrifact next to IDL on the GSHHG basemap. Fixes #3288

- src/ocpndc.cpp
This memory corruption has been observed when following a track point by point in the 'Track details' dialog, but it can probably occur in many scenarios, as long as a rounded rectangle is drawn somewhere.
This fixes my issue reported initially here:
https://www.cruisersforum.com/forums/f134/opencpn-version-5-8-2-released-275428-11.html#post3787568
> Fix a memory corruption due to incorrect buffer size calculation

- src/ais_decoder.cpp
Converting an AIVDM to an AIVDO sentence for targets in the mmsi-properties was broken. This will fix it if the original sentence was a 0183.
> fix mmsi-properties convert AIVDM to AIVDO (only 0183)

- src/chcanv.cpp
- src/route.cpp
1) Crash when merging two routes and click on the resulting route. (process appending)
2) Legs not selectable after merging (process inserting)
3) First point of the second route after a "split at waypoint" not selectable as "nearby point"
4) Delete the unuseful  "tail" part of the route after  merge
> Correct Split merge routes processes

- src/plugin_loader.cpp
More clean up after #3258
This reverts commit d2ce0c583d7320828d2266a9cb93ce0930f21efb. This was a misconception from my side leading to that the chartdownloader tab disappears as discussed in #3374
> Revert "plugin_loader: Fix bad typo leading to crash."

- include/plugin_loader.h
- src/plugin_loader.cpp
More clean up after #3258
As discussed in https://github.com/OpenCPN/OpenCPN/issues/3374#issuecomment-1663856174, new code invokes `PluginLoader::NotifySetupOptionsPlugin(...)` multiple times which plugins are are not prepared to handle. Add a simple check ensuring that only the first call is actually executed.
This is one of many things which not are defined. With  NotifySetupOptionsPlugin() calls spread all over the place it's IMHO just luck that this has not happened before.
> Only run notify_setup_options() once.

- buildwin/winConfig.bat
Fixes: https://github.com/OpenCPN/OpenCPN/issues/3388
Also, allows buildwin\winConfig.bat to be called multiple times to build (or rebuild) O.  No longer any need to remember msbuild commands for general build/rebuild case.
> Fix usage instructions and do not append to configdev.bat

- src/plugin_loader.cpp
More cleanup after #3103, as discussed in
https://github.com/OpenCPN/OpenCPN/issues/3374#issuecomment-1666539373
We cannot reliably match available metadata to an existing plugin pre API 117 since plugin only carries major + minor. This means that a metadata change like 1.1.1 -> 1.1.2 is not reflected in what's available from the plugin.
Eventually, this means that if metadata is updated (catalog update) the metadata will not match the plugin if it's not updated.
So: just just plugin major + minor for installed plugins which don't have any more info i. e., is <= API 116.
> plugin_loader: Don't use metadata version (#3374).

- src/plugin_loader.cpp
- src/pluginmanager.cpp
More clean  up after #3258 as discussed in #3374. 
- Use the installation data version.  That this was not used is what's in Swedish is called a "brain drop". 
- Hide the Action (typically Reinstall) button for imported plugins.
- Take care handling versions like v3.2.1  or r1.2.3
> Fixes for plugins. 

- include/ocpn_plugin.h
As discussed in zulip https://shorturl.at/sF238 current version of ocpn_plugin.h generates a large amount of warnings when used in plugins. This PR fixes some  of them. It should be safe, basically exposing the same interface to both clients and implementing code.
> ocpn_plugin.h: Fix some  warnings

- include/ocpn_plugin.h
- src/chcanv.cpp
- src/ocpn_plugin.cpp
- src/pluginmanager.cpp
As discussed in  https://shorturl.at/sF238 last part of silencing the compiler warnings for ocpn_plugin.h when compiling plugins.
Theoretically, this might break both API and  ABI for plugins using an API level < 1.16. However, I don't  think we have such plugins around, and even if the changes "should" work.
While on it, fix an annoying uninitialized variable.
> ocpn_plugin.h warnings, part 2

- include/ocpn_plugin.h
As discussed on zulip. Resolves the MSVC linkage error reported in https://github.com/Rasbats/shipdriver_pi/issues/552.
While on it, re-format some long comment lines.
> ocpn_plugin.h: Handle MSVC linkage errors

- cmake/in-files/config.h.in
- include/macutils.h
- src/base_platform.cpp
- src/macutils.c
- src/plugin_handler.cpp
Detect architecture at runtime and check plugin compatibility based on `target-arch` metadata.
The plugin can provide either a single platform (`x86_64` or `arm64`) or a list in case of universal build (`x86_64;arm64`)
The plugin side counterpart may look like https://github.com/nohal/nsk_pi/commit/7b3512e250f02e0af0874dbb6e06e147c5e0c03b
> macOS - support for multi architecture plugins

- include/comm_navmsg.h
- include/ocpn_plugin.h
- manual/modules/ROOT/pages/plugin-messaging.adoc
- manual/site.yml
- src/comm_plugin_api.cpp
- test/tests.cpp
Tentative fix for #3381. This is raw code which needs review and testing.
One open issue I'm aware of is the `context_self` and `context` strings in the internal signalK message defined in *comm_navmg.h*. Should these be visible in the API? As of  this PR they are not.
> Signalk comm API getter function (#3381)

- cmake/CompilerSupport.cmake
- libs/mipmap/CMakeLists.txt
- libs/mipmap/src/mipmap.c
- libs/mipmap/src/mipmap_ssse3.c
The detection was mistakenly broken a few years ago.
> fix optimized mipmap support using ssse3

- libs/observable/include/observable.h
- libs/observable/include/observable_evtvar.h
- manual/modules/ROOT/pages/plugin-messaging.adoc
Currently, listening to an Observable item is a but messy involving defining an event type, start listening to this event and define how to handle the event.
The goal for this PR is to simplify this process. The first step is the new class EvtVarListener which completely hides details about event types, Bind() and listening when listening to an EventVar. User just defines an action to be performed when a given EventVar is notified, and that's it.
It should be possible to generalize this to other contexts like message listening. 
EDIT:
Closes: #3467
The initial PR is updated so it can be applied to anything which can be listened to, more exactly anything implementing the dead simple KeyProvider interface. This includes NavMsg (messages common denominator), EvtVar, ConfigVar and GlobalVar.
> libs: observable: Add EvtVarListener interface class

- src/chcanv.cpp
ChartCanvas should not attempt to build a canvas view when one of the window size parameters is zero. Eventually, when the canvas has an area > 0 then we will rebuild it.
> Do not attempt to resize zero area canvas

- src/plugin_handler.cpp
If PKG_TARGET did not contain 2 substrings separated by '-' then O could crash.
> Check ubuntu PKG_TARGET contains 2 substrings

- CMakeLists.txt
- include/cmdline.h
- include/config_vars.h
- libs/sound/src/PortAudioSound.cpp
- libs/wxservdisc/CMakeLists.txt
- src/ConfigMgr.cpp
- src/OCPNPlatform.cpp
- src/ais_decoder.cpp
- src/androidUTIL.cpp
- src/base_platform.cpp
- src/chcanv.cpp
- src/config_vars.cpp
- src/console.cpp
- src/navutil.cpp
- src/navutil_base.cpp
- src/ocpn_app.cpp
- src/ocpn_frame.cpp
- src/options.cpp
- src/plugin_handler.cpp
- src/pluginmanager.cpp
- test/n2k_tests.cpp
- test/tests.cpp
Still preparations for  #3409 and #3349. Here is
- The fix described in #3497. This breaks the current CLI interface.
- A fix needed to make an "early exit" from cli commands: add51a3f1. Scary stuff, see below.
- Some clean up: misplaced #include,  disable noisy cli debug logging on linux, missing #include guards, handling of  UserColorTableArray in ocpn_frame The latter probably results of the split ocpn_frame and ocpn_app. 
- Some really boring work reducing the number of extern declarations using config_vars
Regarding  add51a3f:
- It is the right thing to do. Closing the top window should also exit the main loop.
- I have made smoke tests on Linux, Windows and MacOS without noticing anything peculiar.
> Miscellanour, notably 3497

- include/meteo_points.h
- src/ais_decoder.cpp
- src/ais_target_data.cpp
Update the logic to change mmsi-ID for received ais8dac001fi3 Meteo stations.
Initially we changed the mmsi when the same mmsi was used for all station from one country.
We tried to check if the mmsi was unique and thus keep it.
After helpful tests from Irish users it turned out Ireland used the same mmsi for Meteo and a nearby AtoN. Leading to clashes.
Since IMO lack of rules for mmsi assignment for these targets it can happen similar assignments are used also by other countries.
The logic is hereby changed so every Meteo station get a met-mmsi to avoid clashes. It also implies code simplification with less conditions.
Also a small edit of AIS Target query to show both the origin MMSI and the used meteo ID.
> Ais meteo update

- include/meteo_points.h
- src/AISTargetQueryDialog.cpp
- src/ais_decoder.cpp
- src/ais_target_data.cpp
- According to spec. "DAC367_FI33_em_version_release_3-23mar15_0." 
- Some adjustments to the overall Meteo handling including resize of Target query dialog after a data update from another station.  -> Q - commit: "Adjust size after updated Ais query dialog"  does add "AdjustBestSize()" commented out above by df0dcd6 back in 2015. Are there some obstacle I don't understand implementing it again?
> Meteo;  Include  data from (US) AIS 8 Dac 367 Fi 33 and other adjustments

- include/gui_lib.h
Fix a (sort of ) typo. 
Is there a use case for private superclasses?  Strange that this has been with us for so long.
> gui_lib: bugfix

- .circleci/config.yml
- ci/control
- ci/generic-build-debian.sh
- Update ci/control to meet more modern standards (bookworm seems overall more picky about the format). Closes: #3507.
-  Update the focal build to build jammy instead. The idea is that we build the newest and oldest supported ubuntu version.
-  Add a bookworm build -- we should really build debian stable, this is what's used directly or indirectly on most RPis
-  Some  general CI housekeeping.
> CI: Housekeeping, fix bookworm build (#3507)

- ci/generic-build-macos.sh
- include/rest_server.h
Handle MacOS ci build errors, not detected since the ci jobs seemd to be OK although they are not
> macos: ci: Handle std::filesystem missing on 10.13

- CMakeLists.txt
- ci/universal-build-macos.sh
- include/rest_server.h
Fixes for std:.filesystem MacOS CI build errors. 
Builds still fails on unrelated include paths problems leading to the use of /usr/local/include/geodesic.h instead of ./geodesic.h
> Macos ci; Fixes for std::filesystem

- include/ais_target_data.h
- src/ais_decoder.cpp
- src/ais_target_data.cpp
Temporary "hack" to solve the bug from #3541. The issue is left until a SK response if or not implementing meteo data.
> Meteo SignalK. Sort out Ais8_Dac001_Fi31 creating false class A targets

- .github/workflows/windows.yaml
- buildwin/win_deps.bat
- ci/appveyor.bat
- test/n2k_tests.cpp
- test/rest-tests.cpp
- test/tests.cpp
- Make sure that failing builds are actually vissible as such
- Add tests to the default build target
- Fix errors in tests and a missing library in the build
> c: windows: clean up

- libs/SQLiteCpp/CMakeLists.txt
- libs/SQLiteCpp/include/SQLiteCpp/Assertion.h
- libs/SQLiteCpp/include/SQLiteCpp/Backup.h
- libs/SQLiteCpp/include/SQLiteCpp/Column.h
- libs/SQLiteCpp/include/SQLiteCpp/Database.h
- libs/SQLiteCpp/include/SQLiteCpp/Exception.h
- libs/SQLiteCpp/include/SQLiteCpp/ExecuteMany.h
- libs/SQLiteCpp/include/SQLiteCpp/SQLiteCpp.h
- libs/SQLiteCpp/include/SQLiteCpp/SQLiteCppExport.h
- libs/SQLiteCpp/include/SQLiteCpp/Savepoint.h
- libs/SQLiteCpp/include/SQLiteCpp/Statement.h
- libs/SQLiteCpp/include/SQLiteCpp/Transaction.h
- libs/SQLiteCpp/include/SQLiteCpp/Utils.h
- libs/SQLiteCpp/include/SQLiteCpp/VariadicBind.h
- libs/SQLiteCpp/src/Backup.cpp
- libs/SQLiteCpp/src/Column.cpp
- libs/SQLiteCpp/src/Database.cpp
- libs/SQLiteCpp/src/Exception.cpp
- libs/SQLiteCpp/src/Savepoint.cpp
- libs/SQLiteCpp/src/Statement.cpp
- libs/SQLiteCpp/src/Transaction.cpp
- libs/sqlite/include/sqlite3.h
Updates the bundled SQLite related libraries to latest releases. SQLite 3.44.2 is already available in current `opencpn-libs` so we bring the core to the same level
> Update SQLite and SQLiteCPP

- include/conn_params.h
- src/conn_params.cpp
- src/multiplexer.cpp
If I understand the discussions correctly, this addresses the issue raised in https://github.com/OpenCPN/OpenCPN/issues/2954 and again in https://github.com/OpenCPN/OpenCPN/issues/3516
There is no GUI change as there wasn't for other similar changes allowing to tune the connection parameters. But we probably need to have a look at the way connections are configured as at 20+ parameters the current CSV format is probably way over the limit of its convenient usability. TOML/YAML/JSON?
> Allow control of 'echo to self' for serial ports

- plugins/dashboard_pi/src/altitude.cpp
- plugins/dashboard_pi/src/altitude.h
- plugins/dashboard_pi/src/baro_history.cpp
- plugins/dashboard_pi/src/baro_history.h
- plugins/dashboard_pi/src/clock.cpp
- plugins/dashboard_pi/src/clock.h
- plugins/dashboard_pi/src/compass.cpp
- plugins/dashboard_pi/src/compass.h
- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
- plugins/dashboard_pi/src/depth.cpp
- plugins/dashboard_pi/src/depth.h
- plugins/dashboard_pi/src/dial.cpp
- plugins/dashboard_pi/src/dial.h
- plugins/dashboard_pi/src/from_ownship.cpp
- plugins/dashboard_pi/src/from_ownship.h
- plugins/dashboard_pi/src/gps.cpp
- plugins/dashboard_pi/src/gps.h
- plugins/dashboard_pi/src/instrument.cpp
- plugins/dashboard_pi/src/instrument.h
- plugins/dashboard_pi/src/rudder_angle.cpp
- plugins/dashboard_pi/src/rudder_angle.h
- plugins/dashboard_pi/src/speedometer.cpp
- plugins/dashboard_pi/src/speedometer.h
- plugins/dashboard_pi/src/wind.cpp
- plugins/dashboard_pi/src/wind.h
- plugins/dashboard_pi/src/wind_history.cpp
- plugins/dashboard_pi/src/wind_history.h
Replaced the dashboard code with the fork mentioned in https://github.com/OpenCPN/OpenCPN/discussions/3547 and fixed it to actually build with `-fpermissive` not enabled
> Dashboard UI configuration

- src/MarkInfo.cpp
The show name checkbox is located next to the name input field. Latitude and longitude aligned horizontally
> MarkInfo Improvements in item layout in waypoint properties dialog

- src/mbtiles.cpp
A few month ago, I implemented the zoom modifier setting for MBTILES, reading the raster zoom modifier and changing the MBTILE map level accordingly. But I did two errors :
1 - I inverted the silder : positive values where actually reducing details while it should have been the opposite.
2 - I did not take into account the modifier when returning the current map scale, leading to incorrect over/underzoom flags being raised.
Both problems are fixed in this pull request.
> Fix mbtiles zoom modifier bug

- plugins/dashboard_pi/src/dashboard_pi.cpp
Output is only 3 characters - but was formatted to 5. Causes values to be pushed right, possible off screen.
> Update formatting for true/app wind direction for dashboard instrument

- model/src/rest_server.cpp
rest_server.cpp invokes methods affecting wxWindows data structures from the server thread. Fix by moving to main thread.
This is a long standing issue which seems to be present also in 5.8.4 but for some reason does not trigger anything there.
Kudos to @hakansv which found the nasty #3588 bug while working with #3584. And of course also to @bdbcat who found the basic problem.
Closes: #3588
> rest_server: Avoid wxWin data in worker thread (#3588)

- CMakeLists.txt
- gui/include/gui/SendToPeerDlg.h
- gui/include/gui/ocpn_app.h
- gui/include/gui/ocpn_frame.h
- gui/include/gui/peer_client.h
- gui/include/gui/peer_client_dlg.h
- gui/include/gui/route_ctx_factory.h
- gui/include/gui/routemanagerdialog.h
- gui/src/SendToPeerDlg.cpp
- gui/src/canvasMenu.cpp
- gui/src/ocpn_app.cpp
- gui/src/ocpn_frame.cpp
- gui/src/peer_client.cpp
- gui/src/peer_client_dlg.cpp
- gui/src/routemanagerdialog.cpp
- model/CMakeLists.txt
- model/include/model/peer_client.h
- model/include/model/rest_server.h
- model/include/model/routeman.h
- model/src/peer_client.cpp
- model/src/plugin_loader.cpp
- model/src/rest_server.cpp
- model/src/routeman.cpp
- test/rest-tests.cpp
Client side of the peer transfer code.
- Refactor peer_client into somewhat proper model + gui parts.
- Fix the "Ok to overwrite dialog" so it occurs on the originating peer rather than the server. This requires that both client and server is updated.
- Fix bug leading to duplicated waypoints on the receiving side. This is a server only fix not requiring an updated client.
All sorts of code clean up and GUI polish. Some memory leaks was detected and plugged.
Closes: #3121
Closes: #3522 
EDIT: Added new commits handling activation of a transferred route (#3406). This is only the initial part of issue which is left open.
:
> Peer transfers: client overhaul.

- model/src/peer_client.cpp
The problem reported in #3596 turns out to apply to all 5.8.4 servers. Make sure the client does not override old keys unless the server is known to be 5.9+.
Closes: #3596
> Fix repeated Android peer transfers  (#3596)

- cmake/StdFilesystem.cmake
- libs/ghc/README.md
- libs/ghc/include/ghc/filesystem.hpp
- model/include/model/rest_server.h
Boost dependency causes the usual trouble at runtime on machines older than the builder. As we need only `filesystem` and for that we have a trivial alternative in `ghc::filesystem`, it is not worth the trouble to build Boost and include it in the dependency bundle.
Closes #3625.
> Replace boost::filesysten dependency on legacy macOS with ghc::filesystem

- gui/include/gui/navutil.h
- gui/src/navutil.cpp
- gui/src/ocpn_frame.cpp
- gui/src/routemanagerdialog.cpp
- libs/pugixml/pugiconfig.hpp
- libs/pugixml/pugixml.cpp
- libs/pugixml/pugixml.hpp
- model/include/model/nav_object_database.h
- model/include/model/routeman.h
- model/src/nav_object_database.cpp
- model/src/route.cpp
- model/src/route_point.cpp
- model/src/routeman.cpp
- Make saving navobj.xml atomic (save to temporary file, then rename it)
- Reject XML that does not load correctly, we did create it, so it has to validate while we load it
- Improve logging
- Automatically use latest backup if navobj.xml is clearly corrupted
- Do not rotate the backups if navobj.xml is corrupted
- Fix multiple crashes and memory leaks in navobj.xml handling
- Fix layer route addition to navobj.xml.changes when changing it's visibility
- Update the bundled copy of pugixml library to 1.14
> Improve navobject file handling safety

- model/include/model/comm_drv_n0183_net.h
- model/src/comm_drv_n0183_net.cpp
Refactor OnTimerSocket to avoid the silly need to create a wxTimerEvent.
Closes: #3643
> comm_drv_n0183_net: Avoid creating wxTimerEvent (#3643)

- gui/include/gui/ocpn_app.h
- gui/src/ocpn_app.cpp
- include/ocpn_plugin.h
- model/include/model/comm_navmsg.h
- model/include/model/rest_server.h
- model/src/comm_navmsg.cpp
- model/src/comm_plugin_api.cpp
- model/src/rest_server.cpp
- test/rest-tests.cpp
Add the missing parts described in #3648
As for @nohal's request for a general JSON relay to plugins this is generalized to a sending an arbitrary string. The message has an id similar to communication messages, so plugins listens to a specific kind  of plugin message.
The plugin message service is yet not exported in the plugin interface. ~Will do before merge~ (done)
Closes: #3648
Besides using a remote client testing can also be done using curl. This requires a working api key. How to set up this is described in the [manual](https://opencpn-manuals.github.io/main/opencpn-dev/rest-interface.html#_headless_pairing). I just pushed a bugfix to this chapter, manual needs to be rebuilt before used.
With a correct `source` and `apikey` as of above testing could be done according to the specs …
> REST server update (#3648)

- gui/include/gui/TCWin.h
- gui/src/TCWin.cpp
This pull request is linked to #3562 and improves Tide/Current window rendering with dark color themes :
> Improve Tide/Current windows colors for dark themes

- gui/include/gui/ocpn_frame.h
- gui/src/ocpn_frame.cpp
- model/include/model/ipc_api.h
- model/include/model/local_api.h
- model/src/ipc_api.cpp
- model/src/ipc_factories.cpp
- Add `ReleaseInstance()` method in various classes
- Add 'ReleaseApiListner()' method in various classes
- Add `ReleaseApiListeners()` method in the 'MyFrame` class
- Move static pointer 'factory' into local file scope
These methods are designed to do nothing when running on non-wxMSW
systems. On wxMSW systems, 'MyFrame' will use existing and the new
methods to create one 'wxDDEserver' object at startup and release
it before closing the main window thus eliminating a wxDebug assert.
See discussion: [IPC](https://opencpn.zulipchat.com/#narrow/stream/332168-Master---5.2E8.2E0--.28was.3A-comms.29/topic/IPC.20feature)
> IPC - Release the wxDDEserver object before exit

- gui/src/chcanv.cpp
- gui/src/options.cpp
This pull request fixes two minor color problems :
- The current value drawn below the current arrow is using Tide font color instead of current font color -> Fixed
- Colors of chart directories in chart group panel of option window are not changed in case of dark color theme -> fixed
> Fix minor color issues

- CMakeLists.txt
- android/androidUTIL.cpp
- gui/include/gui/OCPNPlatform.h
- gui/include/gui/displays.h
- gui/include/gui/ocpn_frame.h
- gui/src/ConfigMgr.cpp
- gui/src/OCPNPlatform.cpp
- gui/src/TrackPropDlg.cpp
- gui/src/chcanv.cpp
- gui/src/displays.cpp
- gui/src/gui_lib.cpp
- gui/src/navutil.cpp
- gui/src/ocpn_app.cpp
- gui/src/ocpn_frame.cpp
- gui/src/options.cpp
- libs/s52plib/src/s52plib.cpp
- libs/s52plib/src/s52plib.h
- model/CMakeLists.txt
- model/include/model/base_platform.h
- model/src/base_platform.cpp
- Implement platform specific logic to obtain geometry of all connected displays
- Replace all calls to wxDisplaySize in core applicationwith access to our multi-monitor implementation
This is ground work for real multi monitor awareness
Identifies physical size of my displays correctly on all platforms, but certainly needs testing on more hardware I don't have access to like the RPi touchscreen  monitors, real HiDPI screens etc.
Closes #3683
> Implement improved support for multi monitor systems

- gui/include/gui/pluginmanager.h
- gui/src/pluginmanager.cpp
- model/include/model/plugin_handler.h
- model/src/plugin_handler.cpp
Rewrite the safe mode plugin handling so it only offers a single operation "uninstall". This is based on installation data which should cover all "normal" installations including imports. 
This does **not** handle the case when a user manually drops a library file in a plugin directory, such files are not listed in the GUI and must still be removed manually.
There is an unrelated build error on Android, currently being fixed.
There is another unrelated build error on the Gtihub windows build.  However, manual smoke tests on Linux and and Windows builds and looks OK.
Closes: #3685
> Rewrite safe mode plugin handling (#3685)

- gui/src/ocpn_app.cpp
- model/include/model/base_platform.h
- model/include/model/cmdline.h
- model/src/base_platform.cpp
- model/src/cmdline.cpp
- model/src/plugin_handler.cpp
- opencpn.1
- test/CMakeLists.txt
- test/dbus_tests.cpp
- test/ipc-srv-tests.cpp
- test/std_instance.cpp
- test/wx_instance.cpp
Add a new command line option which uses an alternative configuration directory instead of the linux default ~/.opencn
Closes: #1022
> Add a new -c --configdir command line switch

- CMakeLists.txt
- NSIS.template.in.in
- glutil/CMakeLists.txt
- glutil/console.cpp
- gui/src/OCPNPlatform.cpp
- gui/src/chcanv.cpp
- gui/src/navutil.cpp
- Add command line utility `opencpn-glutil` for testing OpenGL capabilities, producing JSON output
- Replace the in-process GL capability test with call to the utility to prevent main application crash in case of fatal problems
- Make the logic handle the `-G` command line switch correctly (really disable OpenGL for the session, but do not modify the user's saved configuration)
The `opencpn-glutil` executable has to be in the same directory as the running `opencpn` on Unix platforms and in `<opencpn.exe location>\bin` (next to `opencpn-cmd.exe`) on Windows. This works out of the box for installed application, but for local ad hoc builds not being installed the developer needs to place or symlink the binary to correct location for the test to be able to work.
Closes #3649
> Refactor OpenGL capability test

- gui/src/pluginmanager.cpp
Current code uses a specific, custom grey background for  disabled plugins.  This leads to #3707 since these bacgrounds does not follow the overall theme.
Use the standard colour and use an italic font instead as visual feedback for disabled plugins besides the _Enabled_ checkbox.
Closes #3707
> Plugin manager: Don't use custom background

- gui/src/mbtiles/mbtiles.cpp
**Description of the bug :** 
MBTiles Charts are flickering when moving the map at very high zoom levels.
**Explanation of the bug :**
MBTiles cache size is dynamically defined by counting the number of tiles which have to be rendered on the current display. The way tiles were being count was buggy, leading to very low values in some specific conditions. The cache was then almost flushed and this was leading to a flickery rendering of the chart (drawn a first time without any tile and then a second time with all tiles once the cache was filled again).
**Fix :**
One line fix to properly count the tiles to be rendered.
> Fix MBTILES cache bug

- CMakeLists.txt
- gui/src/connection_edit.cpp
- libs/wxservdisc/mdnsd.c
- model/CMakeLists.txt
- model/src/comm_drv_signalk_net.cpp
Restores the mDNS discovery of local Signal K server.
Tested on macOS and Linux
I have not restored and actually completely disabled even in the UI the option to discover the server dynamically at startup as it never was reliable enough anyway and made the startup take way too long in case the server was actually not available. I do not think there is much use case for it where the SK server has dynamic address that changes, but if someone sees any, am open to hear it.
Fixes #3757
> Restore the Signal K server mDNS discovery

- libs/IXWebSocket/CMakeLists.txt
- Explicitly disables `BUILD_SHARED_LIBS` in `IXWebSocket`
- Prevent installing it's build artifacts
> Force IXWebSocket static build and disable install

- CMakeLists.txt
- cmake/in-files/config.h.in
- gui/include/gui/comm_overflow_dlg.h
- gui/include/gui/ocpn_frame.h
- gui/src/chcanv.cpp
- gui/src/comm_overflow_dlg.cpp
- gui/src/ocpn_frame.cpp
- gui/src/options.cpp
- gui/src/udev_rule_mgr.cpp
- model/CMakeLists.txt
- model/include/model/comm_drv_n0183_serial.h
- model/include/model/comm_drv_registry.h
- model/include/model/comm_out_queue.h
- model/src/comm_drv_n0183_serial.cpp
- model/src/comm_out_queue.cpp
- test/CMakeLists.txt
- test/buffer_tests.cpp
- test/tests.cpp
Fixes problems described in #3815 and  #3391:
- Make sure all data is actually written
- If overflowing, apply a sane strategy rather than just silently dropping messages at random.
- Remove the static variable which makes it impossible to have more than one instance.
Closes: #3815
Closes: #3391
Current state: Works for me, including the test case described in #3391
> Serial driver: Fix high load problems

- gui/include/gui/AdapterInfo.h
- gui/include/gui/connection_edit.h
- gui/src/AdapterInfo.cpp
- gui/src/connection_edit.cpp
Some ideas related to issue #3700
https://github.com/OpenCPN/OpenCPN/issues/3700#issuecomment-2041211103
Everything I have done should be considered experimental just to see some ideas. The networking code in AdapterInfo.cpp is pretty rough and targets windows, so that should be completely rewritten.
> expereimental changes to connection edit dialog

- gui/src/connection_edit.cpp
Remove small screen limitation, allow more/less to work on Android. Remove GRMN mode checkbox from network connections. Remove SignalK server discovery controls. When selecting UDP, if both Input and Output are checked, uncheck output. Do not allow both Input/Output at same time.
> Changes to connection edit dialog.

- gui/src/connections_dialog.cpp
For the option "Use magnetic bearings in output sentence ECAPB, no need to prepend the "EC" talker id, as the talker Id can now be changed and persisted.
Per user guidelines, both "Add Connection" and "Edit Connection" raise a dialog so they should be appended with "..." to indicate this.
> Connection Dialog UI fixes

- gui/src/chcanv.cpp
- gui/src/options.cpp
As it was very simple, and I realy like the idea. Range ring(s) depending on time and speed over ground. See picture, where each ring is 24Hours of sailing at current speed.
> Add range ring(s) around own ship based on time (and SOG)

- gui/src/mbtiles/TileQueue.hpp
- gui/src/mbtiles/WorkerThread.hpp
- gui/src/mbtiles/mbtiles.cpp
Several problems were fixed in this pull request : 
- In case of heavily loaded system, OpenCPN was freezing and needed to be killed
- Sometimes, OpenCPN was freezing when exiting
- There was a small error in the scale table in mbtiles.cpp leading to incorect zoom level to be selected (almost unoticeable practically)
The fixes : 
- Mbtiles worker thread was using the WxWidgets *Render()*  API to force redrawing the map after all tiles were successfully decompressed. However this API is not thread safe and this was leading to very strange and ultimately crashing behaviors. This has been replaced by a call to *CallAfter* which is thread safe.
- There was a bad usage of mutexes and conditions to kill the thread on exit which was leading to deadlocks : mutex and conditions have been removed …
> Fix various problems in mbtiles

- gui/src/options.cpp
The color controls are to big on a scaled Windows screen. I suppose the bitmaps ground for these controls need adjustments.
Tweaked:
> Options color picker controls. Tweak hight to Windows screen scaling

- gui/src/mbtiles/mbtiles.cpp
Problem : 
An error of scale calculation was introduced by #3860 : scale was incorrect by a factor ~7 leading to incorrect mbtile selection in some conditions.
Solution : 
I used scale & MPP initial constants provided by OSM on this page : https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
instead of my own calculation which were incorrect.
> Fix mbtiles scale calculation introduced by #3860

- gui/include/gui/gui_lib.h
- gui/src/connection_edit.cpp
- gui/src/gui_lib.cpp
- gui/src/udev_rule_mgr.cpp
- model/include/model/ocpn_utils.h
- model/src/linux_devices.cpp
- model/src/ocpn_utils.cpp
- model/src/ser_ports.cpp
Don't create links for stable device names ttyS*, avoid displaying multiple links to the same device and add some GUI polish. 
Also add a hopefully generally useful  CopyableText class, used as wxStaticText but based on wxTextCtrl and thus copyable.
Closes: #3868
> Links: Clean up linux links handling - #3868

- glutil/console.cpp
The copyright obviously belongs mostly to Pavel. While on it, replace the legacy file header with one which Doxygen can parse.  Linux distros are picky about copyrights, better get this right.
For legal reasons, this should be stamped by both Alec and Pavel.
@pavel: could you please review and eventually merge?
> glutil: Update copyright and description [skip ci]

- gui/include/gui/NMEALogWindow.h
- gui/include/gui/TTYWindow.h
- gui/include/gui/connection_edit.h
- gui/include/gui/connections_dialog.h
- gui/include/gui/ocpn_frame.h
- gui/include/gui/options.h
- gui/src/NMEALogWindow.cpp
- gui/src/TTYWindow.cpp
- gui/src/connection_edit.cpp
- gui/src/connections_dialog.cpp
- gui/src/navutil.cpp
- gui/src/ocpn_app.cpp
- gui/src/ocpn_frame.cpp
- gui/src/options.cpp
- Make options to sort of a "semi-modal" dialog which allows for the NMEA log window to process events.
- Hook up the NMEA log window close event  so  the "Show NMEA Debug window" is updated when user closes window.
- While on it: some general clean up i affected files.
Closes: #3923
> Fix NMEA log window event handling (#3923)

- gui/include/gui/udev_rule_mgr.h
- gui/src/ocpn_frame.cpp
- gui/src/udev_rule_mgr.cpp
Instead of a modal dialog which blocks the startup use a modeless frame. Track the open instances to make it possible to destroy them if they still exists whne exiting opencpn.
Closes: #3922
> udev_rule_mgr: Make "device not found" dialog modeless  (#3922).

- plugins/dashboard_pi/src/dashboard_pi.cpp
In Dashboard searching for the satellite info prioritized by OCPN.
Since an IP address can contain equal text as a Protocol we may get a false positive.
Example: My IP "nmea2000 TCP:signalk.stupan.se:1455:127" was identified as a signalk protocol instead of N2k.
Maybe not so common but can happen to others too.
> D-board: Prevent IP address from being misinterpreted as Protocol

- gui/src/chcanv.cpp
- gui/src/navutil.cpp
- gui/src/ocpn_app.cpp
Added new COG and HDT predictor options, which can be configured by opencpn.ini: OwnshipCOGPredictorStyle (default 105 dash)
OwnshipCOGPredictorColor (default red)
OwnshipCOGPredictorEndmarker (default 1)
OwnshipHDTPredictorStyle (default 105 dash)
OwnshipHDTPredictorColor (default red)
OwnshipHDTPredictorEndmarker (default 1)
OwnshipHDTPredictorWidth (default 0=use COG width)
> New COG and HDT predictor options

- libs/s52plib/src/s52plib.cpp
e.g., test ( 12 != 10 * 1.25 ) caused image to be always dumped and recreated.
> Fix image dump test

- plugins/grib_pi/src/GribUIDialog.cpp
Dave,
As per email exchange, this solution works for me. The Gribdialog does have a local copy of the *PluginViewpPort. At init this was set to zero. The local copy is only updated on a Render(GL)Overlay(..) call.
> Set PluginViewport at Gribdialog init.

- plugins/dashboard_pi/src/dial.cpp
Found a copy-pasta error in DB dial object.
> DB: Correct the position of secondary text data in dials.

- plugins/dashboard_pi/src/gps.cpp
Don't call SetTextForeground() after calling SelectObject(wxNullBitmap) on a wxMemoryDC, as the latter makes the DC unusable -- and changing the text colour here seems completely unnecessary anyhow, as the DC is not used any longer.
This prevents each frame redraw from resulting in an assert, which made the plugin unusable when the asserts were active.
----
I've run into this while just playing the program and wanted to fix it as getting asserts all the time made the plugin unusable. AFAICS, this call isn't needed at all, I thought the intention might have been to call `SetTextForeground()` on `dc` instead, but this call is already present above in the same function, so I've just removed it.
> Fix assert failure due to using uninitialized wxMemoryDC

- gui/src/connections_dialog.cpp
> Postpone binding ConnectionsDialog::OnSize event after the dialog is initialized

- gui/src/AISTargetQueryDialog.cpp
Intend to resolve this [CF post](https://www.cruisersforum.com/forums/f134/opencpn-v5-9-2-beta-test-released-287456-5.html#post3917096) issue.
Works on Win10 and hopefully on W11 as well.
Tested on Debian but not MacOS. Parent: "gFrame" is though used elsewhere wo Mac issues reported?
> Adjust parent for AIS pers.track message box

- model/src/plugin_loader.cpp
- plugins/demo_pi_sample/CMakeLists.txt
- plugins/demo_pi_sample/src/nmea0183/response.cpp
I wanted to experiment with OpenCPN plugins, so I've started by building the demo plugin but this didn't work out of the box and I had to make the changes in this PR to fix it.
According to #1939 it might still not build under Windows, but this shouldn't make things worse there and at least it builds under Linux now.
> Fix demo plugin build and loading

- gui/src/SendToPeerDlg.cpp
- gui/src/canvasMenu.cpp
- gui/src/routemanagerdialog.cpp
- model/CMakeLists.txt
- model/include/model/mdns_cache.h
- model/src/mDNS_query.cpp
- model/src/mdns_cache.cpp
An  attempt  to handle #4071. Here is:
- The caching is refactored to a proper  singleton instance.
- Added mutexes to cope with possible collisions between the timer and main threads.
- New strategy, see below
- Manual entries are also cached.
The strategy is to keep all discovered hosts without time based checks. Instead, the cache is validated before use: All hosts are checked for connectivity and removed if they cannot be accessed.
The net result is that once a host is discovered it will be kept in cache as long as it is there. This also means that to detect new hosts which becomes available after the initial scan user must push the "Scan Again" button.
Closes: #4071
> mDNS cache reimplementation

- gui/src/chcanv.cpp
Follow up to dee14e78f
- Simplify a somewhat convoluted expression.
- Fix typos and spelling errors in ui string.
- Make a constant variable const.
- Run clang-format.
@Hakansv : any objections or thoughts?
> dee14e78f: follow up fixes

- gui/src/OCPNPlatform.cpp
When debugging under linux it can be useful to have the language files in the same location as all the other runtime files, i.e. a build directory. This change uses the '-p' flag to change the language base directory from '/usr/local' to '{build/runtime directory}'
> Update to allow '-p' flag to apply for language file locations.

- libs/N2KParser/src/N2KParser.cpp
- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
- plugins/dashboard_pi/src/instrument.h
This PR implements the instrument discussed here: #3427 
- NMEA0183 reads XDR type D name WINDLASS or WINDLASS#0. Tested
- N2k PGN 128777 reads "RodeCounterValue" . Not tested. We hope for testers during alpha.
- No Windlass rode count in SignalK. It has been discussed but not implemented.
> Add Dashboard instrument Windlass rode count

- manual/package-lock.json
- manual/package.json
This PR fixes 5 npm vulnerabilities that were found while running `npm audit fix`:
```bash
$ cd manual
$ npm audit fix
npm warn audit fix http-cache-semantics@4.1.0 node_modules/npm/node_modules/http-cache-semantics
npm warn audit fix http-cache-semantics@4.1.0 is a bundled dependency of
npm warn audit fix http-cache-semantics@4.1.0 npm@8.11.0 at node_modules/npm
npm warn audit fix http-cache-semantics@4.1.0 It cannot be fixed automatically.
npm warn audit fix http-cache-semantics@4.1.0 Check for updates to the npm package.
npm warn audit fix ip@1.1.8 node_modules/npm/node_modules/ip
npm warn audit fix ip@1.1.8 is a bundled dependency of
npm warn audit fix ip@1.1.8 npm@8.11.0 at node_modules/npm
npm warn audit fix ip@1.1.8 It cannot be fixed automatically.
npm warn audit fix ip@1.1.8 …
```
> 5 npm vulnerabilities (1 moderate, 4 high) in manual

- model/include/model/comm_buffers.h
- model/include/model/comm_drv_n0183.h
- model/include/model/comm_drv_n0183_net.h
- model/include/model/conn_params.h
- model/include/model/garmin_protocol_mgr.h
- model/include/model/ocpn_utils.h
- model/src/comm_buffers.cpp
- model/src/comm_drv_n0183_android_bt.cpp
- model/src/comm_drv_n0183_android_int.cpp
- model/src/comm_drv_n0183_net.cpp
- model/src/comm_drv_n0183_serial.cpp
- model/src/comm_drv_n2k_net.cpp
- model/src/comm_drv_n2k_serial.cpp
- model/src/comm_drv_n2k_socketcan.cpp
- model/src/comm_drv_signalk_net.cpp
- model/src/conn_params.cpp
- model/src/ocpn_utils.cpp
- test/buffer_tests.cpp
General  cleanup of the 0183 network driver reflecting the serial driver update in #4160.
Here is:
- Fix hacks caused by missing `const` in `GetStrippedDSPort()` declaration
- Clean up of comments and logging.
- Move checksum utility to ocpn_utils, clearing a FIXME
- Clean up public interface making it  much smaller.
- Clean up the resulting private interface by removing all private Get/Set accessors which just adds complexity.
- Update some variable and function names to match Google GL.
- Fix some clang-tidy diagnostics,  notably making sure that everything is initialized in the constructor.
- Fix  a strange typo error in [fbb7558](https://github.com/OpenCPN/OpenCPN/pull/4189/commits/fbb7558e4d99de727b64292f135105c78d6495ee) (has this ever worked?)
- Avoid an extra message passing and …
> N0183 net work driver cleanup.

- model/CMakeLists.txt
- model/src/comm_drv_n0183_android_bt.cpp
- model/src/comm_drv_n0183_android_int.cpp
- model/src/comm_drv_n0183_net.cpp
- model/src/comm_drv_n0183_serial.cpp
- model/src/ds_porttype.cpp
Make sure the ioDirection attribute  is correct. While on it, centralize the textual dsPortType representation to make things more robust.
Closes: #4192
> Fix bad ioDirection driver attribute (#4192)

- model/include/model/logger.h
- model/include/model/serial_io.h
- model/src/logger.cpp
- model/src/std_serial_io.cpp
- plugins/demo_pi_sample/CMakeLists.txt
Stop serial io from flooding log when the port is not available.
Add new infrastructure to logger.h  with filters which only logs every n message or only once in a time interval. Should be generally useful.
> Serial logging update

- gui/src/ocpn_frame.cpp
- model/include/model/comm_drv_n0183_net.h
- model/src/comm_drv_n0183_net.cpp
- Fix the strange message box reported in #4195 
- Add  GUI messages like "Cannot connect to server at ...",  similar to the serial and N2K driver when server is unavailable on upstart.
- More driver clean up: shrink the public interface, replace wxDateTime with chrono.
> NMEA 0183 network driver update

- libs/ShapefileCpp/lib/src/Point.cpp
- libs/wxservdisc/1035.c
- libs/wxservdisc/mdnsd.c
Most of this is pointer casts. It doesn't look like this code is being updated regularly, so having it compile cleanly seems like a win.
> Fix OSX warnings in libs

- gui/src/navutil.cpp
- gui/src/s57chart.cpp
Some ENC charts have a discrepancy between filenames used in the chartdata, and the attached files. Window is not case-sensitive with filenames but linux does care. 
This will check if an attached file is available using case on-sensitve compare with chart data. If found then the filename as attached is used for the link in the object-query.
I did use the i_f(file.IsCaseSensitive())_ function from wxFilname, but might be as well a #ifndef __MSVC__  .
Attached a Belgium inland chart for testing.
[Archive.zip](https://github.com/user-attachments/files/17980821/Archive.zip)
> S57 Objectquery, check and correct for wrong filename upper/lower case.

- gui/include/gui/pluginmanager.h
- gui/src/TrackPropDlg.cpp
- gui/src/canvasMenu.cpp
- gui/src/chcanv.cpp
- gui/src/cm93.cpp
- gui/src/glChartCanvas.cpp
- gui/src/ocpn_frame.cpp
- gui/src/ocpn_plugin_gui.cpp
- gui/src/pluginmanager.cpp
- gui/src/s57chart.cpp
- include/ocpn_plugin.h
- model/CMakeLists.txt
- model/include/model/comm_drv_internal.h
- model/include/model/plugin_comm.h
- model/src/comm_drv_internal.cpp
- model/src/plugin_api.cpp
- model/src/plugin_comm.cpp
- test/tests.cpp
- Modify SendMessageToAllPlugins() so it sends the message also on the new message bus.
- Add support in WriteCommPort for sending PluginMsg i. e., a message ti the internal message bus.
Whichever way a message is sent, WriteCommPort(),  SendPluginMessage() or SendMessageToAllPlugins(), it is now possible for plugins to just listen for selected messages using the new API.
While on it refactor pluginmanager  moving lots of non-gui stuff to a new plugin_comm module. Less use of the dreaded g_pi_manager, and some more focus for the pluginmanager jack of all trades.
Closes: #4255
EDIT: This is basically about plugging a hole in the original implementation where we made a major effort to make anything injected by the new API available also in the old. This PR is about the opposite: making …
> Handle also internal messages in new API (#4255)

- gui/src/ocpn_app.cpp
- manual/modules/ROOT/pages/coding-guidelines.adoc
- po/POTFILES.in
Fix two build failures when invoking `make pot-update`.
1. These files do not exist:
```
gui/src/mbtiles/TileCache.hpp
gui/src/mbtiles/TileDescriptor.hpp
gui/src/mbtiles/TileQueue.hpp
gui/src/mbtiles/WorkerThread.hpp
```
2. The `kUsage` variable value was causing a `xgettext` failure.
In addition:
1. Change `BUOY` label to 'Buoy' such that label is the same for short and long labels. Previously the short label was 'Buoy' and the long label was 'BUOY' all uppercase. This caused one more i18n message to be created in the `.pot` file and was inconsistent with the labeling conventions for the other labels.
2. Add coding instructions for localization.
> Fix build failure when executing `make pot-udpate`

- gui/include/gui/dychart.h
- gui/src/chcanv.cpp
- gui/src/cm93.cpp
- gui/src/ocpn_app.cpp
- gui/src/ocpn_frame.cpp
- gui/src/s57chart.cpp
- gui/src/s57obj.cpp
- gui/src/viewport.cpp
Replaced `__MSVC__` with `__VISUALC__` because some compilers define __MSVC__. Included `wx/msw/msvcrt.h` from wxWidgets library instead of manually creating 'new' macro. Changes applied to: dychart.h, chcanv.cpp, cm93.cpp, ocpn_app.cpp, ocpn_frame.cpp, s57chart.cpp, s57obj.cpp, and viewport.cpp.
Simplifies and potentially improves memory leak detection by leveraging wxWidgets utilities.
> Update memory leak detection for MSVC using wxWidgets

- gui/src/options.cpp
- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/grib_pi/src/GribRequestDialog.cpp
- plugins/grib_pi/src/GribUIDialogBase.cpp
Standardize the spelling of British English words ("color" and "licence") to US English for translatable strings in the source code.
Fix #4213
> Change translatable strings to use US English instead of British English

- gui/src/ocpn_frame.cpp
- gui/src/pluginmanager.cpp
- model/include/model/comm_navmsg_bus.h
- model/src/comm_navmsg_bus.cpp
- test/tests.cpp
Add a new, internal API which makes it possible to list currently available message types.
Closes: #4266
> Add get available message types API

- plugins/grib_pi/src/pi_TexFont.cpp
> Fix UTF-8 character

- gui/src/TTYScroll.cpp
Remove unused colors in the NMEA debug window (GOLD, BROWN, SIENNA).
> Remove unused colors in NMEA0183 debug window

- gui/include/gui/TTYScroll.h
- gui/include/gui/TTYWindow.h
- gui/src/TTYScroll.cpp
- gui/src/TTYWindow.cpp
Closes #4243
Insert a new function in NMEA Debug Window to copy only N0183 sentences without date and source info as discussed [here](https://github.com/OpenCPN/OpenCPN/discussions/4243).
> Add tool Copy N0183 to NMEA Debug Window

- plugins/grib_pi/src/CursorData.cpp
- plugins/grib_pi/src/CustomGrid.cpp
- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/GribOverlayFactory.h
- plugins/grib_pi/src/GribReader.cpp
- plugins/grib_pi/src/GribRecord.cpp
- plugins/grib_pi/src/GribRequestDialog.cpp
- plugins/grib_pi/src/GribSettingsDialog.cpp
- plugins/grib_pi/src/GribTable.cpp
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribUIDialog.h
- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/GribV1Record.cpp
- plugins/grib_pi/src/GribV2Record.cpp
- plugins/grib_pi/src/IsoLine.cpp
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/jsonreader.cpp
- plugins/grib_pi/src/jsonval.cpp
- plugins/grib_pi/src/jsonval.h
- plugins/grib_pi/src/jsonwriter.cpp
- plugins/grib_pi/src/pi_ocpndc.cpp
- plugins/grib_pi/src/pi_ocpndc.h
- plugins/grib_pi/src/pi_shaders.cpp
- plugins/grib_pi/src/pi_shaders.h
- plugins/grib_pi/src/smapi.cpp
- plugins/grib_pi/src/smapi.h
- plugins/grib_pi/src/zuFile.cpp
Modernize code to use `nullptr` instead of `NULL` and `0`.
1. Replace all instances of `NULL` and `0` with `nullptr`, except in bzlib2 dependent library.
2. Use `nullptr` to initialize pointers. Previously some statements were using the int value `0` to initialize the pointers.
```diff
-  if (writeBuff == 0) {
+  if (writeBuff == nullptr) {
```
**Context:**
I started investigating a memory leak in the grib plugin, for which I will submit a PR later. Meanwhile, I thought it would be helpful to document the code, do some cleanup and modernize the code with modern C++ constructs.
> Replace NULL with nullptr

- gui/include/gui/FontMgr.h
- gui/include/gui/concanv.h
- gui/include/gui/gui_lib.h
- gui/src/FontMgr.cpp
- gui/src/ocpn_app.cpp
- include/ocpn_plugin.h
Document APIs for fonts:
1. Plugin font APIs (ocpn_plugin.h)
2. Internal APIs
The proposed code comments could be improved with feedback from the original authors. it would be helpful to clearly document the specific use cases for each of the 4 plugin functions that return a `wxFont` or `wxFont*`. It's not very obvious which function should be used for what purpose.
- `wxFont* OCPNGetFont`
- `wxFont* GetOCPNScaledFont_PlugIn`
- `wxFont GetOCPNGUIScaledFont_PlugIn`
- `wxFont* FindOrCreateFont_PlugIn`
It seems new code should always use `GetOCPNScaledFont_PlugIn` rather than `OCPNGetFont`, but I'm not sure.
I'm working on https://github.com/rgleason/vdr_pi/pull/67, and I find it's not very clear what is the best plugin API to invoke.
Is it intentional that `GetOCPNGUIScaledFont_PlugIn` …
> Add code comments for font manager, locale, and font APIs for plugins.

- gui/include/gui/CanvasConfig.h
- gui/include/gui/OCPNPlatform.h
- gui/include/gui/chartimg.h
- gui/include/gui/chcanv.h
- gui/include/gui/viewport.h
- gui/src/CanvasConfig.cpp
- gui/src/chcanv.cpp
- gui/src/glChartCanvas.cpp
- gui/src/ocpn_app.cpp
- gui/src/viewport.cpp
- libs/s52plib/src/s52plib.h
- model/include/model/base_platform.h
This is WIP
Fix for #4218 
Changes in this PR:
1. Add code comments to document whether some pixel coordinates are in physical pixels or logical pixels. It can be confusing when navigating through the code because physical pixels are used in the canvas, whereas WX widgets tend to use logical pixels.
1. I've documented a subtle difference between `GetDoubleCanvasPointPix` which truncates pixels, versus  `GetCanvasPointPix`, which rounds pixels. This can cause a one-pixel difference depending on which function is invoked.
1. I found this while investigating another issue: https://github.com/OpenCPN/OpenCPN/issues/4229#issuecomment-2524578926
2. I didn't change the logic: I've merely documented the differences, but it seems the code should be changed such that we can eliminate this one-pixel …
> Lat/Lon coordinates at cursor are wrong when the scale factor != 1 and OpenGL is disabled

- gui/include/gui/ocpndc.h
- gui/src/TTYWindow.cpp
- gui/src/ocpn_frame.cpp
- libs/nmea0183/src/nmea0183.cpp
- libs/nmea0183/src/nmea0183.hpp
- model/include/model/comm_util.h
- model/include/model/multiplexer.h
- model/src/comm_util.cpp
- model/src/multiplexer.cpp
Partial fix for https://github.com/OpenCPN/OpenCPN/issues/3882
1. Add arrow character to show direction of NMEA message (input vs output).
1. Add character to show accepted vs error vs filtered vs dropped.
1. Changed "Information Message or Message with errors" to "Message with error". I don't see an actual use case where red is used to represent "information".
1. Add code comments.
> Improve logging of NMEA0183 messages in debug window

- gui/src/svg_utils.cpp
- gui/src/waypointman_gui.cpp
Fix #4230 
Useful references:
1. https://www.izitru.com/image-file/svg/what-is-svg-width-and-height/
2. https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox
3. https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width#svg
4. https://svgwg.org/specs/integration/#svg-css-sizing
> Fix crash with floating point exception when width attribute is not present in SVG image

- gui/include/gui/ocpn_frame.h
- gui/src/ocpn_frame.cpp
- include/ocpn_plugin.h
- plugins/dashboard_pi/src/clock.h
- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/dashboard_pi/src/dashboard_pi.h
- plugins/dashboard_pi/src/instrument.h
Fix for #4082 
Problem: when there is a GPS watchdog timeout, the fixtime is set to `0`, which has a code comment state the date will be invalid. However, the `0` value is valid, i.e. `IsValid()` returns true. There are other parts of the code that were written with the `IsValid()` check.
The dashboard plugin was not checking for the special `0` value.
I considered the alternative to use `wxInvalidDateTime` when no GNSS data is available, but the `time_t FixTime` field is present in the plugin API, hence it cannot be changed to `wxDateTime`.
This PR fixes the following problems in the dashboard plugins. When no GNSS data is available:
1. The GNSS local time is set to "---". Previously, a fixed time such as "16:00:00" was displayed. It was misleading because the widget was displaying …
> Dashboard: fix problem with date invalidation after GPS watchdog timeout

- gui/src/MarkInfo.cpp
- model/src/route.cpp
Improve route way-point re-sequencing to renumber all way-points that start with a dynamic sub-string. Also including way-point names that have a longer customized name (e.g. 004-Dover). The custom part of the name is appended to the new sequence number.
> Improve route waypoint resequencing

- CMakeLists.txt
- gui/include/gui/gui_lib.h
- gui/include/gui/route_gui.h
- gui/src/canvasMenu.cpp
- gui/src/route_gui.cpp
- gui/src/routemanagerdialog.cpp
- libs/gui/CMakeLists.txt
- libs/gui/include/dialog_alert.h
- libs/gui/include/dialog_base.h
- libs/gui/include/dialog_footer.h
- libs/gui/src/dialog_alert.cpp
- libs/gui/src/dialog_base.cpp
Implement AlertDialog UI component following Gnome HIG standards (#4329).
This is a PoC UI component following the introduction of UI guidelines (Gnome HIG). By using re-usable UI component from a library it will be easier to adhere to the standard. The UI component implements and encapsulates the UI specifications.
AlertDialog is implemented with `wxStdDialogButtonSizer` to handle the button placement for the target platforms. The dialog padding is set as recommended in the [Layout guidelines](https://wiki.gnome.org/Design(2f)HIG(2f)Planning(2f)Layout.html), with density-independant pixels (DIP). 
This PR adds a `CMakeList` for UI library in folder `/lib/gui`.
> UI component AlertDialog.

- gui/src/connections_dlg.cpp
The word "Port" must not be used lonely as discussed here: https://github.com/OpenCPN/OpenCPN/discussions/4078#discussioncomment-11928018
> Connections; Change words to correct translation

- libs/s52plib/src/s52cnsy.cpp
Some (inland) ENC come with DRVAL1 and DRVAL2 both programmed 0.0. The result is a green filled area.
The difference for and after this commit.
> Improve the DEPARE color for bad chartdata

- gui/src/printtable.cpp
Fix tokenizer to adjust the output line. It was skipping each word when the line gets too long.
> Fix missing words in route print.

- gui/include/gui/RoutePropDlgImpl.h
- gui/include/gui/navutil.h
- gui/src/RoutePropDlgImpl.cpp
- gui/src/TrackPropDlg.cpp
- gui/src/navutil.cpp
Move user datetime conversion functions to `navutils` to be available for re-use. This PR resolves #4352.
The format definitions are included in the header and a duplicate format definition is removed.
The refactoring revealed a bug that the input parameter `format` was not used, but the code used the selection in the dialog instead.
> Move user datetime func to navutils

- gui/include/gui/FontDesc.h
- gui/src/FontMgr.cpp
This is a fix for #4288 
Font Matching Logic Improvements:
Added explicit size matching logic with four scenarios:
1. Default font size (when requested_font_size is 0)
2. User-customized default font size (g_default_font_size)
3. System default font size
4. Exact requested font size matching
> FontMgr::GetFont should honor the requested font size

- gui/include/gui/chcanv.h
- gui/include/gui/compass.h
- gui/src/chcanv.cpp
- gui/src/compass.cpp
- model/include/model/comm_vars.h
- model/include/model/own_ship.h
> Clicking on the compass widget causes map to pan to the right instead of changing compass mode

- CMakeLists.txt
- gui/include/gui/TTYWindow.h
- gui/include/gui/tty_scroll.h
- gui/src/TTYWindow.cpp
- gui/src/ocpn_plugin_gui.cpp
- gui/src/tty_scroll.cpp
- libs/observable/include/observable.h
- model/include/model/comm_drv_n2k.h
- model/include/model/comm_navmsg.h
- model/include/model/ocpn_utils.h
- model/src/comm_drv_n2k.cpp
- model/src/comm_n0183_output.cpp
- model/src/comm_navmsg.cpp
- model/src/multiplexer.cpp
- model/src/ocpn_utils.cpp
- model/src/plugin_api.cpp
- po/POTFILES.in
- test/tests.cpp
Various preparatory works related to #4324 but useful for it's own sake.
The PR does not contain any user visible changes. Under the hood:
- navmsg: Add missing constructors and operators required by standard STL containers.
- navmsg: Fix to_string() so it does the right thing for all message types.
- navmsg: Clean up source address. This is (should be) unused when sending, made available when receiving data.
- observable: Add missing ObsListener std::move assignment semantics. 
- ocpn_plugin_gui.cpp: Sort header mess, file level comments
- TTYScroll: Rename (Google GL), clean up, optimize.
> Communications clean up

- CMakeLists.txt
- gui/include/gui/MarkInfo.h
- gui/include/gui/route_validator.h
- gui/src/MarkInfo.cpp
- libs/gui/CMakeLists.txt
- libs/gui/include/dialog_base.h
- libs/gui/include/field_text.h
- libs/gui/include/form_grid.h
- libs/gui/include/ui_utils.h
- libs/gui/src/dialog_alert.cpp
- libs/gui/src/dialog_base.cpp
- libs/gui/src/field_text.cpp
- libs/gui/src/form_grid.cpp
- libs/gui/src/ui_utils.cpp
- model/include/model/gui.h
UI library TextField implementation (#4338).
The PR first moves the existing code to the UI library. Secondly spacing variable and method are refactored from the `BaseDialog` to the UI library utils to also support spacing with DIP in other classes. In compliance with the UI guidelines using 6px as base for spacing.
The PR introduces a `FormGrid` class in the UI library to layout multiple `TextField`s in a form with proper spacing. The grid has two columns; one for the label and one for the actual field.
The text field class interface is simplified to encapsulate layout and spacing within the class, including error handling. This simplifies the usage of this UI component.
> Implement TextField in UI library

- model/include/model/comm_drv_n0183_serial.h
Fix following compilation warnings:
```bash
ttype.cpp
In file included from /Users/serosset/git/OpenCPN/model/src/comm_drv_factory.cpp:41:
/Users/serosset/git/OpenCPN/model/include/model/comm_drv_n0183_serial.h:61:15: warning: 'GetDriverStats' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
61 |   DriverStats GetDriverStats() const { return m_serial_io->GetStats(); }
|               ^
/Users/serosset/git/OpenCPN/model/include/model/comm_drv_stats.h:56:23: note: overridden virtual function is here
56 |   virtual DriverStats GetDriverStats() const = 0;
|                       ^
In file included from /Users/serosset/git/OpenCPN/model/src/comm_drv_n0183_serial.cpp:42:
/Users/serosset/git/OpenCPN/model/include/model/comm_drv_n0183_serial.h:61:15: …
```
> Fix compiler warning: add missing override keyword

- gui/include/gui/chcanv.h
- gui/include/gui/glChartCanvas.h
- gui/src/ocpn_app.cpp
1. Add code comments for chart panning fields and functions. I'm looking at improvements of mouse click and drag selection in the GRIB plugin, and I wanted to understand better how OpenCPN core does panning.
2. Add a few curly braces to ensure code comments in `gui/src/ocpn_app.cpp` are properly indented. The CI uses a slightly older version of `clang-format` that incorrectly indents code comments. Specifically this happens after a `if` statement followed by a single statement without curly braces. For example:
```c++
if (!g_Platform->GetLargeLogMessage().IsEmpty())
wxLogMessage(g_Platform->GetLargeLogMessage());
-  // Validate OpenGL functionality, if selected
+    // Validate OpenGL functionality, if selected
```
A more recent version of clang-format (e.g. 19.1.7) properly indents code …
> Add code comments for chart panning

- gui/include/gui/FontDesc.h
- gui/include/gui/FontMgr.h
- gui/include/gui/options.h
- gui/src/FontDesc.cpp
- gui/src/FontMgr.cpp
- gui/src/options.cpp
This is a follow-up to #4359 and #4296 
Specifically the issue reported by @Hakansv at https://github.com/OpenCPN/OpenCPN/pull/4296#issuecomment-2644203597
Two regressions have been introduced by #4359:
1. Methods that don't take a font size parameter (like `GetFontColor()`) were inconsistently handling default fonts. They would return properties from the first matching font entry in the cache, even if it wasn't the default font entry for that text element.
2. In the UI, the drop-down list of fonts in Options -> User Interface -> Fonts may have duplicates.
This regression was introduced after attempting to fix this problem: In the font manager, the `GetFont()` function completely ignored `user_default_size`. While it seems to handle `user_default_size`, it actually doesn't use it when …
> Fix regressions in Font Manager, support reset to system font

- model/src/ais_decoder.cpp
The intent is to resolve the MMSI-properties bug refereed to in issue #4379
I have only been able to test the new function using comparable SignalK data.
> Update N2k AIS targets to be ignore according to MMSI properties list

- gui/src/options.cpp
Defer Sizer Layout until after checkbox list is fully created. Early out on loops when searching for item.  Tested on intel macOS 15.3.1.  In the future the checkbox list could be just refreshed rather than fully rebuilt every time, TBD.
> Optimizations for opening Settings menu

- manual/modules/ROOT/pages/mac-osx.adoc
1. After getting a Macbook M4 with Apple Silicon, I followed the usual [MacOS build instructions](https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/compile_mac_osx.html)
2. When I try to run the application, it fails with a code signing issue. The program is stopped immediately after launching OpenCPN.
I applied this workaround:
```bash
codesign --force --deep --sign - ~/OpenCPN/bin/OpenCPN.app
```
I have updated the manual to show the `codesign` command. It's also what the `ci/generic-build-macos.sh` script does, but it wasn't documented in the build instructions.
> Updated build instructions for MacOS

- gui/include/gui/gshhs.h
- gui/include/gui/shapefile_basemap.h
- gui/src/shapefile_basemap.cpp
- libs/ShapefileCpp/lib/include/ShapefileReader.hpp
1. Fix min/max calculations of cells that are used to find polygons in tiled charts.
2. Normalize longitude of input values in the range [-180, 180]. The tiled cells assume the longitude are in the range [-180, 180], but the `CrossesLand ` function makes no such assumption, e.g. it could be in the range [0, 360].
4. Add code comments to clarify some points raised in #4040
5. Issues in `LineLineIntersect`:
- Added early bounding box check to quickly reject non-intersecting segments before the more expensive calculations.
- Added proper handling for collinear segments that may overlap.
- Introduced an epsilon constant for comparing floating-point values.
6. Issues in `PolygonLineIntersect`:
- Missing closing edge check: The function doesn't check for intersection with the edge connecting …
> Fix min/max lat/lon for ShapeBaseChart::CrossesLand. Add code comments

- gui/src/chartdbs.cpp
- gui/src/gshhs.cpp
- gui/src/ocpn_frame.cpp
- gui/src/ocpn_plugin_gui.cpp
Fix for #4040 and https://github.com/seandepagnier/weather_routing_pi/issues/301
1. When the user configures chart data, selects "rescan" or "rebuild the database": recursively look for a `GSHHG` directory containing GSHHG data.
2. If add/rescan/rebuild operation finds GSHHG data, reload the GSHGG data from files on disk. The data is loaded into the singleton GSHHG reader. That singleton reader is used by the weather routing plugin to detect land. Internally, `gshhsCrossesLandReset` is invoked.
1. Rename static `reader` variable to `gshhs_singleton`. The variable had the same name as the `GSHHSChart::reader` private member, which was confusing.
4. Add code comments.
1. Validate the  `<shared data dir>/GSHHS/` directory contains the crude quality GSHHG files that ship with OpenCPN …
> Reload GSHHS files from disk when user adds GSHHS files or rescans/rebuilds the chart database

- model/src/ais_decoder.cpp
Handles the case where the user has just entered their own MMSI for an AIS target that already exists in the list. Without this, it takes "remove lost time" before deletion and possible user confusion.
> Check if own mmsi is recently been set and delete it from target list

- model/src/comm_drv_signalk_net.cpp
When Signal K server terminates the connection after changing it's security settings, a message like `{message: \"Connection disconnected by security constraint\"}` is received, which is not a JSON object and leads to an assertion in RapidJSON while calling `HasMember` on it. Closes #4394
> Prevent asserts on Signal K server originated disconnection when security settings change

- android/androidUTIL.cpp
- gui/include/gui/TrackPropDlg.h
- gui/include/gui/navutil.h
- gui/include/gui/options.h
- gui/src/ConfigMgr.cpp
- gui/src/RoutePropDlg.cpp
- gui/src/RoutePropDlgImpl.cpp
- gui/src/TrackPropDlg.cpp
- gui/src/navutil.cpp
- gui/src/ocpn_frame.cpp
- gui/src/options.cpp
- gui/src/pluginmanager.cpp
- gui/src/routemanagerdialog.cpp
- include/ocpn_plugin.h
- model/CMakeLists.txt
- model/include/model/config_vars.h
- model/include/model/datetime.h
- model/include/model/route.h
- model/include/model/track.h
- model/src/config_vars.cpp
- model/src/datetime.cpp
- model/src/track.cpp
- plugins/grib_pi/src/GribTable.cpp
- plugins/grib_pi/src/GribTable.h
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
- test/CMakeLists.txt
- test/tests.cpp
This PR introduces a consistent approach to date/time formatting throughout OpenCPN. It adds a global configuration parameter for selecting between UTC and local timezone display, accessible through the Options dialog.
Consistent date/time formatting reduces cognitive load and provides a better first-time experience. Users can set the global setting once and all timestamps are formatted accordingly. When users need to switch between UTC and "Local Time", then can easily do so by changing the date/time format in one place.
The date/time format and labels are more consistent and less ambiguous:
- Use abbreviated time zone like "PST" instead of "LOC" or "LC" or "PC"
- Ensure labels are consistent across dialogs.
A new `toUsrDateTimeFormat()` function centralizes formatting logic both for …
> Global config parameter for selecting local time or UTC

- android/androidUTIL.cpp
- gui/include/gui/FontMgr.h
- gui/src/FontMgr.cpp
- gui/src/RoutePropDlgImpl.cpp
- gui/src/SendToPeerDlg.cpp
- gui/src/priority_gui.cpp
- include/ocpn_plugin.h
- libs/s52plib/src/s52plib.cpp
- plugins/chartdldr_pi/src/chartdldr_pi.cpp
- plugins/chartdldr_pi/src/chartdldrgui.cpp
- plugins/dashboard_pi/src/dashboard_pi.cpp
- plugins/grib_pi/src/CursorData.cpp
- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/GribRequestDialog.cpp
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
- plugins/wmm_pi/src/wmm_pi.cpp
Improve chart text sizing with monotonic font transformation.
Replace non-monotonic piecewise font size adjustment with a linear transformation that maps S52 chart text sizes to a consistent range. This ensures larger input values always result in proportionally larger output sizes while still preventing 
excessively large fonts from NOAA ENC files.
- Map input font sizes [0-20] to a normalized range [0-4]
- Add normalized value to user's configured font size
- Maintain minimum readable size of 10 points
- Improve code readability with clear comments and constants
In addition, respect the user font customization (font color, face and font size). For example, if the user selects a font size of 12, then this is considered to be the base font size. The normalized value in the range [0, 4] is …
> Chart font size

- gui/include/gui/viewport.h
- gui/src/viewport.cpp
- include/ocpn_plugin.h
- libs/geoprim/src/bbox.h
- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/GribOverlayFactory.h
- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/GribUIDialogBase.h
Fix for #4405
When panning charts with the GRIB plugin enabled, wind barbs and other graphical elements (direction arrows and numbers) do not move with the chart. Instead, they remain fixed at their screen positions, creating a confusing visualization where the chart moves but the weather elements stay in place.
This PR changes how the fixed-spacing grids for GRIB elements (wind barbs, direction arrows, and numerical values) are calculated and rendered:
1. Instead of creating a layout grid in screen coordinates, we now:
- Convert the user-configured pixel spacing to geographic spacing based on the current zoom level
- Create a grid of elements in geographic coordinates (lat/lon)
- Convert these geographic positions to screen coordinates only during rendering
2. With this approach, GRIB …
> Fix wind barbs and elements not moving with chart when panning

- gui/src/chcanv.cpp
- include/ocpn_plugin.h
- plugins/grib_pi/GRIB.fbp
- plugins/grib_pi/src/GribOverlayFactory.cpp
- plugins/grib_pi/src/GribRequestDialog.cpp
- plugins/grib_pi/src/GribRequestDialog.h
- plugins/grib_pi/src/GribSettingsDialog.cpp
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribUIDialog.h
- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/GribUIDialogBase.h
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
1. Manual GRIB area selection is currently broken because it conflicts with OpenCPN's core chart panning behavior, resulting in unintended panning when trying to select a download area with the GRIB plugin. The user is supposed to do left-click and drag. However, this behavior is overridden by the OpenCPN core chart panning, which also uses Left click + drag, so as a result, mouse area selection does not work.
2. Users are required to click "manual" mode before being able to select a download area. This extra step is unintuitive and can be eliminated. It's not intuitive because the user must:
- Click the download button.
- Click the "email" tab (which is the third tab)
- Click "Manual Selection".
- When the user clicks "Manual Selection", spinners are displayed, making the user believe …
> Fix manual selection of download area for GRIB files

- ci/generic-build-debian.sh
- model/include/model/comm_appmsg.h
- model/include/model/comm_appmsg_bus.h
- model/include/model/comm_navmsg.h
- model/include/model/comm_navmsg_bus.h
- model/include/model/ocpn_utils.h
- model/src/comm_appmsg.cpp
- model/src/comm_appmsg_bus.cpp
- model/src/comm_navmsg.cpp
- model/src/comm_navmsg_bus.cpp
- model/src/ocpn_utils.cpp
- model/src/win_usb_watch.cpp
- plugins/demo_pi_sample/CMakeLists.txt
- plugins/demo_pi_sample/cmake/PluginConfigure.cmake
- plugins/demo_pi_sample/cmake/PluginPackage.cmake
- test/dbus_tests.cpp
Some general updates of build and com_navmsg_bus required and used by  #4400 but also useful as in their own right.  Part of making #4400 somewhat smaller and more manageable.
Not expected to change anything in current behaviour.
> Data monitor basic updates

- gui/include/gui/printout_base.h
- gui/include/gui/printout_chart.h
- gui/include/gui/routeprintout.h
- gui/include/gui/trackprintout.h
- gui/src/ocpn_plugin_gui.cpp
- include/ocpn_plugin.h
1. Add missing plugin APIs for unit conversion:
1. fromDMM_PlugIn
2. getUsrWindSpeedUnit_Plugin
3. toUsrWindSpeed_Plugin
4. fromUsrWindSpeed_Plugin
5. toUsrDepth_Plugin
6. fromUsrDepth_Plugin
37. getUsrDepthUnit_Plugin
1. Update code comments in `getUsrTempUnit_Plugin` to show Kelvin are supported. I'm not sure why anybody would use Kelvin while sailing, but it's supported by the implementation. That made me chuckle.
9. Fix compilation warnings that were introduced by https://github.com/OpenCPN/OpenCPN/pull/4374
> Add missing plugin APIs for unit conversion

- gui/src/route_gui.cpp
- gui/src/route_point_gui.cpp
- model/include/model/comm_n0183_output.h
- model/src/comm_n0183_output.cpp
Fix #4433
With this change, OpenCPN displays an error message if route/waypoint export fails because no device is connected.
I'm not very familiar with this part of the code. I see the error message states "Garmin". Is this the only supported brand?
@leamas, could you take a look?
> Fix crash when exporting route/waypoint to GPS.

- gui/include/gui/MarkInfo.h
- gui/include/gui/RoutePropDlg.h
- gui/include/gui/RoutePropDlgImpl.h
- gui/include/gui/navutil.h
- gui/src/MarkInfo.cpp
- gui/src/RoutePropDlg.cpp
- gui/src/RoutePropDlgImpl.cpp
- gui/src/TCWin.cpp
- gui/src/TrackPropDlg.cpp
- gui/src/canvasMenu.cpp
- gui/src/chcanv.cpp
- gui/src/ocpn_frame.cpp
- gui/src/route_point_gui.cpp
- include/ocpn_plugin.h
- model/include/model/datetime.h
- model/include/model/navutil_base.h
- model/include/model/route.h
- model/include/model/route_point.h
- model/include/model/routeman.h
- model/include/model/track.h
- model/src/datetime.cpp
- model/src/nav_object_database.cpp
- model/src/navutil_base.cpp
- model/src/route_point.cpp
- model/src/routeman.cpp
- model/src/track.cpp
- plugins/grib_pi/src/GribRecordSet.h
- plugins/grib_pi/src/GribTable.cpp
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribUIDialog.h
This PR:
1. Addresses issues related to centralized configuration of date/time format. Because of a regression introduced by #4052, the ETD/ETA fields in route properties were incorrect, and the tide events were also incorrect.
2. Fix inconsistencies in the `toUsrDateTimeFormat` function and `toUsrDateTimeFormat_Plugin` API: The implementation did not properly handle conversion from input date/time argument to target timezone (local time, LMT, UTC).
3. Fix crashes when removing waypoints from routes
4. Fix memory leaks in GetRouteArrayContaining calls.
5. Disable ETD for final waypoints
6. Add tooltips
7. Add/improve code comments
1. In the "Waypoint properties" dialog, the speed units (e.g. "knts") are not updated after the user changes the speed units in global Options.
1. Click …
> Fix bugs in route and waypoint properties

- .circleci/config.yml
- ci/circleci-build-flatpak.sh
- flatpak/Makefile
- flatpak/manifest.patch
Handles FTBFS on the circleci build host.
> ci: Flatpak: Build wxWidgets using cmake

- cli/api_shim.cpp
- gui/src/ocpn_plugin_gui.cpp
- include/ocpn_plugin.h
- manual/modules/ROOT/nav.adoc
- manual/modules/ROOT/pages/plugin-api.adoc
- manual/modules/ROOT/pages/plugin-messaging.adoc
- model/include/model/route_point.h
Plugins can create/update waypoints and set new properties like planned speed, ETD, arrival radius, range rings, scamax.
This PR extends the plugin API by creating a new `PlugIn_Waypoint_ExV2` class that inherits from `PlugIn_Waypoint_Ex` to add support for additional route waypoint properties including:
1. `scamax`: Maximum display scale for waypoint visibility
2. `m_PlannedSpeed`: Planned speed for next leg (knots)
3. `m_ETD`: Estimated departure time
4. `m_WaypointArrivalRadius`: Arrival radius in nautical miles
5. `m_bShowWaypointRangeRings`: Flag for showing range rings adds several new fields:
Add proper handling of these fields in:
1. `PlugInExFromRoutePoint`: For transferring data between core RoutePoint and plugin API objects
2. `CreateNewPoint`: For creating new waypoints from …
> Add route planned speed and ETD fields in plugin API

- gui/include/gui/options.h
- gui/src/options.cpp
- model/include/model/ais_decoder.h
- model/src/ais_decoder.cpp
1. When a user enters a valid MMSI number (9 digits), the dialog automatically looks up the vessel name from:
1. First, the `mmsitoname.csv` file (persistent custom names)
2. If not found, from active AIS target data if available
2. When a user manually sets a vessel name, the name is automatically saved to the `mmsitoname.csv` file, making it persistent across sessions.
3. Add tooltips in the "Edit MMSI Properties" dialog.
4. Added two new methods to the AIS decoder class:
- `UpdateMMSItoNameFile()`: Writes MMSI-to-name mappings to the CSV file
- `GetMMSItoNameEntry()`: Retrieves a name from the CSV file for a given MMSI
This enhancement is particularly useful for MOB (Man Overboard) devices, such as personal MOB beacons worn inside PFDs (Personal Flotation Devices). These safety …
> MMSI property dialog: Add tooltips and "Name" field

- gui/src/concanv.cpp
I can't see that the visibility of ETA should be affected by the change from using SOG to VMG or the other way around. The bug is caused by this, triggered by a @VMG -> @SOG change every second time.
Closes: #4439
> concanv: Don't toggle ETA visibility - #4439

- plugins/grib_pi/src/GribRecordSet.h
1. Document the units of the GRIB parameters.
2. Write better code comments.
There are no code changes.
The reason I did this is because in I am adding a weather routing table in the weather routing plugin. I found out it was unclear whether temperature was in Celsius, percentage in range 0...1 or 0...100, etc. That initially led me to display values like 284 degrees Celsius, which I'm going to fix in the WR plugin.
> Document units of GRIB parameters, improve code comments of GRIB indices

- libs/gui/include/dialog_base.h
- libs/gui/src/dialog_base.cpp
Add font tag with color to support dark mode HTML (#4458).
> HTML dark mode fix.

- cli/api_shim.cpp
- gui/src/ocpn_plugin_gui.cpp
- include/ocpn_plugin.h
- model/include/model/route_point.h
When copying a waypoint to the plugin API structure, the function was checking if the source waypoint had no hyperlinks, and if true, it would immediately return from the function. The consequence of this early return statement is that if a waypoint had no hyperlinks, none of the other properties would be copied to the plugin API structure. This means plugins would receive incomplete waypoint information for any waypoint without hyperlinks, missing data such as:
1. Range ring information
2. Waypoint visibility settings
3. Scale minimums (scamin)
4. Active status flags
1. Removed the return statement after checking `if src->m_HyperlinkList == nullptr`
2. This ensures that even when a waypoint has no hyperlinks, other essential properties (range rings, visibility settings, etc.) are still …
> Fix bug in waypoint property transfer to plugins

- gui/src/options.cpp
- plugins/grib_pi/src/GribOverlayFactory.h
- plugins/grib_pi/src/GribTable.cpp
- plugins/grib_pi/src/GribTable.h
- plugins/grib_pi/src/GribUIDialog.cpp
- plugins/grib_pi/src/GribUIDialog.h
- plugins/grib_pi/src/GribUIDialogBase.cpp
- plugins/grib_pi/src/GribUIDialogBase.h
- plugins/grib_pi/src/grib_pi.cpp
- plugins/grib_pi/src/grib_pi.h
This PR addresses some issues raised in #2453
1. GRIB plugin honors global options, without having to specify "Local Time" or "UTC" in the GRIB plugin preferences. Remove option to specify timezone in GRIB preferences.
2. Move "Date and Time" options to the "Units" panel. Previously it was in the "General" tab.
When the user clicks "Options", then "Units", there is an option to specify whether date/time should be printed in local time or UTC. When the user selects a date/time format, the date/time items in the GRIB drop-down list are updated. Note it may take up to 5 seconds for the date/time items to be reformatted.
Removed date/time format preferences in the GRIB plugin:
> Remove option to specify timezone option in GRIB preferences.

- cli/api_shim.cpp
- gui/src/ocpn_plugin_gui.cpp
- gui/src/route_point_gui.cpp
- include/ocpn_plugin.h
- model/include/model/route_point.h
This PR adds new waypoint and route management APIs that improve the plugin interface for navigation features. It introduces a new `PlugIn_Waypoint_ExV2` class.
- Created `PlugIn_Waypoint_ExV2` as a standalone class (not derived from `PlugIn_Waypoint_Ex`)
- Created `PlugIn_Route_ExV2` to work with the new waypoint class
- Implemented matching API functions for these new classes
- Maximum display scale control (`scamax`)
- Planned speed for route legs
- Arrival radius control
- Configurable range ring visibility
- Estimated departure time support
- Added functions to add, update, and retrieve waypoints/routes using the new classes
- Implemented proper memory management using standard C++ smart pointers
- Preserved backward compatibility with existing API functions
- Improve code comments …
> Add plugin APIs for waypoint and route management

- gui/src/chcanv.cpp
A route can also be used to draw a bearing on the chart. But you have to start drawing from the object and draw towards your own position. This means the bearing shown in the popup are opposite from your actual bearing towards the object.
This commit also add the opposite bearing. For the first leg of a route only, and only during start of a new 'route'.
Picture as is now.
and a screenshot as proposed.
> Route bearing reverse

- gui/src/TCWin.cpp
Error in the HM & LW showed in the tide window.
You can see that for the stations CONCARNEAU   at 9th December 2024, 1st January 2025 and BREST 1st February 2025 with the French HARMONIC_V10 tide database. 
In fact, "GetTideFlowSens()" & "GetHightOrLowTide()" need to have the same entry time to be coherent.
JP
> Correct LW & HW calculation in Tide window

- gui/src/data_monitor.cpp
- model/include/model/comm_navmsg.h
Use system_clock to resolve #4522. Marks log lines with current time which resolves the reported problem. However, the price is quite high:
- Using system_clock means per definition that the relative time between messages is inconsistent/buggy.
- Logs spanning over more than 24 hours are also inconsistent.
Closes: #4522
> data monitor: Use system_clock - #4522

- gui/include/gui/route_printout.h
- gui/include/gui/tcmgr.h
- gui/src/RoutePropDlgImpl.cpp
- gui/src/route_printout.cpp
- gui/src/tcmgr.cpp
Fix #4294 to improve route printing for passage planning and briefing. The main purpose is to include currently missing information in the printout.
Changes to improve route printing:
- Added way-point elements to print selection.
- Increased font size of title with route name and distance.
- Added subtitle with route start and destination.
- Added route description.
- Added speed to the way-points table.
- Added ETA and ETD to the way-point table.
- Added tide information to the way-point table.
> Improve route printing: include missing information.

- gui/include/gui/connections_dlg.h
- gui/src/connections_dlg.cpp
- gui/src/options.cpp
- model/include/model/filters_on_disk.h
- model/src/filters_on_disk.cpp
Remove current scrollbars attached to the connection grid in the connections page, add scrollbars to overall page instead.
Fixes problems described in   https://www.cruisersforum.com/forums/f134/opencpn-v5-11-1-beta-test-starting-now-294554.html#post3998040
> Add scrolling to overall  connections dialog - CF beta feedback

- gui/src/connections_dlg.cpp
- model/src/navobj_db.cpp
If a route is created where the same waypoint is used multiple times, eg. multiple legs around a regatta course, the route is incorrectly saved. This is because of the primary key constraint on routepoints_link.
Creating the route on screen:
The route properties:
After restarting OpenCPN, the last legs are missing.
This PR fixes the problem for new users, but for beta testers who have upgraded, they will; find their existing routes which may have included the same waypoint multiple times in the route are now incorrect.
I fear that I may have caused this problem with the issue I raised previously  #4567
A fix could also be applied offline, but I doubt you want users to run SQLie queries, drop the route_link table and create it with the new schema definition.
Also I'm not sure when the …
> Cannot create a route where a routepoint is used multiple times

- .github/workflows/linux.yml
To partially help with #4582 and based on @leamas feedback to open this PR:
- The Linux workflow is updated to a) fail in case the tests don't succeed and b) keep the verbose output for failing tests
- A test against the Swedish locale fails because this isn't available on GitHub Runners by default. This makes sure that the needed test prereqs are met
This can be split in two PRs if needed. Depends on how these fixes/changes will be handled..
> Allow Linux tests to fail pipeline and fix Swedish locale test

- model/src/ais_decoder.cpp
This is actually a small 3-line fix (if you ignore whitespace).
Starting at line 2006, DecodeN0183() parses the incoming sentence as a xxVDx sentence, even in cases where it is not. A number of bad things can happen, including a crash, as the sentence_accumulator can become very large. The proposed fix is to put the xxVDx parsing under an if().
> Fix for potential crash in DecodeN0183()

- model/include/model/comm_drv_n0183.h
- model/src/comm_drv_n0183.cpp
Make sure that messages which are too long (> 128 chars) are not forwarded to plugins and upper layers where they can make things crash.
While on it, update docs and use the complete input when generating "garbage" messages which only are used in the Data Monitor.
Closes: #4703
> NMEA0183 driver: Updates, notably remove too long messages from input stream

- libs/nmea0183/CMakeLists.txt
- libs/nmea0183/src/nmea0183.cpp
- libs/nmea0183/src/nmea0183.hpp
- libs/nmea0183/src/ths.cpp
- libs/nmea0183/src/ths.hpp
- model/include/model/comm_bridge.h
- model/include/model/comm_decoder.h
- model/src/comm_bridge.cpp
- model/src/comm_decoder.cpp
- model/src/navobj_db.cpp
Note: Only O core. I assume the following:
Dashboard gets heading, pfix.Hdt by SetPositionFixEx(), so there is no need to parse N0183 THS also there.
> Add N0183 sentence $xxTHS for true heading to OCPN core. ref: #4714

- gui/include/gui/TCWin.h
- gui/include/gui/chcanv.h
- gui/src/TCWin.cpp
- gui/src/chcanv.cpp
This is a follow up to #4664 , specifically to address https://github.com/OpenCPN/OpenCPN/issues/4663#issuecomment-3118000622
**Problem**
The current `pCwin` field design in `ChartCanvas` allows multiple tide dialogs to be opened simultaneously, causing memory leaks and inconsistent state.
**Solution**
Implement single-instance management that ensures only one tide dialog can be open at a time while providing enhanced user experience:
1. Same-station detection: Clicking the same tide station brings existing dialog to front instead of recreating it.
2. Station switching: Clicking different stations cleanly transitions between dialogs
3. Context preservation: User's scroll position and view state maintained
**Tests**
✅ Single station click (creates dialog)
✅ Same station re-click (brings to …
> Ensure single instance of tide dialog

- gui/include/gui/TCWin.h
- gui/src/TCWin.cpp
- Fix #4666
- Modernize TCWin layout with sizer-based layout.
- Replace hardcoded positioning calculations with automatic layout management.
- Eliminates text spillover and overlapping panels when resizing the window.
- Create custom TideChartPanel class for self-contained chart rendering.
- Fix #4741
When the user resizes the tide dialog, the dialog uses responsive UI to properly render and resize the sub-elements. Previously, some of the text areas were spilling into the chart.
1. Resize tide window smaller → verify no text overlap with chart
2. Open tide window with GRIB plugin active → verify no crashes
3. Responsive Layout: Test various window sizes and aspect ratios
4. Chart Functionality: Verify all chart interactions still work (rollover, time indicators)
5. Control Panel: Test …
> Bug fix: Tide dialog station text overlaps chart area when window is resized smaller

- gui/src/ocpn_app.cpp
As discussed in bug, calling g_Platform->Initialize_3() before defining g_pauimgr's managed window might lead to a crash. Thus, move the call to a point where g_pauumgr is fully initialized-
Closes: #4796
> ocpn_app: Fix g_platform initialization order -- #4796

- CMakeLists.txt
- gui/include/gui/chcanv.h
- gui/include/gui/compass.h
- gui/include/gui/navutil.h
- gui/include/gui/toolbar.h
- gui/include/gui/tooltip.h
- gui/src/TCWin.cpp
- gui/src/chcanv.cpp
- gui/src/compass.cpp
- gui/src/mui_bar.cpp
- gui/src/navutil.cpp
- gui/src/ocpn_frame.cpp
- gui/src/toolbar.cpp
- gui/src/tooltip.cpp
- include/ocpn_plugin.h
1. Display a tooltip when the user mouses over the compass/gnss widget (after the standard ~1.5s delay). It wasn't very obvious what the blue/red/pink colors mean, especially when the user is trying OpenCPN without being connected to a GPS receiver.
2. Fix #4211.
**North up:**
Tooltip screenshot with two different color schemes:
**Course up:**
**Heading up:**
**Dual canvas layout:**
**MUIBar:**
The tooltips are rendered using a customer `Tooltip` class, which is a refactor of the preexisting `ToolTipWin` class. The `Tooltip` class has been generalized to support regular widgets and the canvas. It supports color schemes (day, night, dawn, dusk) and high visibility. The tooltip rendering is consistent across all platforms (mac, linux, windows)
> Add tooltip for the compass widget and MUIBar

- gui/src/concanv.cpp
Use the same Android's code for others platforms.
This is good for W11
> Console Sizing for all platforms the way it's done for Android
