plugins/grib_pi/src/GribRequestDialog.cpp

improve grib email request logic to allow dateline cross

improvements to grib plugin

---

include/chart1.h
include/navutil.h
src/NavObjectCollection.cpp
src/chart1.cpp
src/chartdb.cpp
src/chcanv.cpp
src/glChartCanvas.cpp
src/navutil.cpp
src/routeman.cpp

speed up startup and shutdown speed of opencpn

Startup optimizations

---

include/cm93.h
src/chart1.cpp
src/cm93.cpp

This fixes some serious cm93 panning issues in single chart mode with opengl, but also corrects issues toggling quilting

Hardware panning

---

src/concanv.cpp

Also optimizes the calculations a little bit
Will port it to master in a different pull request

FS#1732 - Correct the console display of distance and VMG

---

include/georef.h
include/viewport.h
src/chart1.cpp
src/chcanv.cpp
src/cm93.cpp
src/georef.cpp
src/viewport.cpp

several small changes
the optimization to georef is significant

Misc optimizations fixes

---

src/glTexCache.cpp
src/options.cpp

Hi,
small corrections for cache rebuild and wx 3.0.2 
I think it also needs to purge pool queue before starting a cache rebuild as the job list isn't protect against concurrent update.
Regards
Didier

small Cache rebuild stuff

---

src/PositionParser.cpp

wxStringTokenizer does not have a copy constructor.  It will be fixed in wx3.1.

Fix Assert on wxStringTokenizer copy

---

plugins/dashboard_pi/src/dashboard_pi.cpp

the dashboard MWV sentence for the AWA value showed values >180° instead of  0...180° per side.

bugfix MWV sentence for AWA value, see flyspray #1793

---

src/IDX_entry.cpp
src/TCDS_Ascii_Harmonic.cpp

Hi,
Trivial errors from valgrind 
Regards
Didier

tide, uninitialised value and small leak

---

plugins/dashboard_pi/CMakeLists.txt
plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/instrument.h
plugins/dashboard_pi/src/nmea0183/nmea0183.cpp
plugins/dashboard_pi/src/nmea0183/nmea0183.hpp
plugins/dashboard_pi/src/nmea0183/xdr.cpp
plugins/dashboard_pi/src/nmea0183/xdr.hpp

* NKE's Heel / Pitch (Regatta Compass) / Airtemp (new HR Wind sensor)
Heel/Pitch incl. standard single numeric instruments
* NASA Air- and Watertemp (see Flyspray #967)

Implements the XDR sentence for dashboard_pi

---

src/chartdbs.cpp
src/chartimg.cpp
src/mygdal/s57.h
src/mygdal/s57reader.cpp
src/mygeom.cpp
src/s57chart.cpp

This is just scratching the surface, but it is now significantly faster (7 seconds instead of 60 seconds) to update the chart database with thousands of raster charts, and about twice as fast to build the SENC files (which even at this speed is still incredibly annoying when panning for the first time)

Optimized chart parsing

---

src/s57chart.cpp

Hi,
I'm not sure about the kt abbreviation for knot but it's used elsewhere. 
Regards
Didier

S57: attribute CURVEL is in knots not meters

---

src/chartimg.cpp
src/cm93.cpp
src/s57chart.cpp

Hi
Use WxFFile in more places.
Regards
Didier

Buffered io2

---

src/chartimg.cpp
src/s52plib.cpp
src/s57chart.cpp

Hi,
Some trivial speedup .
2d16ca5 is also in Sean pull though.
Regards
Didier

Trivial speedup

---

src/OCPNPlatform.cpp

Fix no matching wxBeginBusyCursor Assert

busy cursor fix

---

src/chart1.cpp
src/s52plib.cpp

Hi,
Try to deal with the slow linux functions GetMemoryStatus and fonts.
Regards
Didier

Speedup linux

---

include/cm93.h
src/chart1.cpp
src/cm93.cpp

Cm93 offset fix

---

plugins/grib_pi/src/GribOverlayFactory.h
plugins/grib_pi/src/GribRecord.cpp
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/TexFont.h

Hi,
TexFont fix as in main source code and small  stuffs from valgrind output.
Regards
Didier

Grib fix (valgrind)

---

plugins/grib_pi/src/IsoLine.cpp

Hi,
It's not using the right logic but it's good enough, at least for me.
Regards
Didier

de clutter Grib isoline label when zoom out

---

include/glTexCache.h
src/glTexCache.cpp

Hi
It was leaking every tickets
Regards
Didier

Texture spooler memory leak.

---

src/glChartCanvas.cpp

Hi
MyApp::OnInit is calling Yield before creating g_compass.
Regards
Didier

protect against trying to display compass before it has been created

---

plugins/grib_pi/src/GribOverlayFactory.cpp
plugins/grib_pi/src/GribOverlayFactory.h

Hi,
Initialise few stuff before use.
Regards
Didier

Unitialised values in grib 

---

src/chart1.cpp
src/chartbarwin.cpp
src/navutil.cpp

Hi,
Valgrind errors.
Regards
Didier

initialise stuff before use

---

src/compass.cpp
src/ocpndc.cpp

Hi,
tested with 3 styles on linux with and without opengl mode, it seems to do the job.
Regards,
Didier

try to get compass mask right

---

src/chartdb.cpp

Hi,
When concurrently accession the chart chart we want to wait on the mutex not giving up.
Regards,
Didier

replace m_cache_mutex.TryLock with m_cache_mutex.Lock

---

src/glChartCanvas.cpp

Authored by seandepagnier tested by nahanniv

Fix Race Condition with Cairo

---

plugins/grib_pi/CMakeLists.txt
plugins/grib_pi/src/GribOverlayFactory.cpp
plugins/grib_pi/src/GribOverlayFactory.h
plugins/grib_pi/src/GribSettingsDialog.cpp

make the particle map use less than half as much cpu as before

Grib optimizations

---

include/about.h
src/about.cpp
src/chart1.cpp

Just a few code suggestions/improvements for the about dialog.
I'd be willing to apply them to the rest of the code if they are accepted.

Update/Modernize OpenCPN

---

src/chartdbs.cpp

Hi,
Matter of taste...
Regards
Didier

piano mouse over, if a chart is not cached don't display all these white lines

---

src/about.cpp

This will allow string concatenating of wide and non-wide strings.
As noted here:
http://www.cruisersforum.com/forums/f134/beta-test-technical-30929-100.html#post1895323

Wrap all of authors multiline text in the wxT macro

---

src/NavObjectCollection.cpp

The main change is to detect and change existing route in "GPXLoadRoute1" function instead of in "InsertRouteA"
The rule is :
If the route to be loaded exists, change the route and route points GUIDs except for "isolated" (permanent) way points who keep all the GUID and values already in the way points base.
The result after loading is two different routes with different route points,but eventually common "isolated" way points.
Jean Pierre

Change logic to load already existing route to ovoid guid conflict( #FS 1834 )

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/wind.cpp
plugins/dashboard_pi/src/wind.h

requested in FS#1687
Shows  one needle for AWA and one for TWA in different colours.
Additional data shown :
Top left corner     : AWA
Top right corner    : AWS
Bottom left corner  : TWA
Bottom right corner : TWS

implementation of combined apparent- / true wind dial instrument.

---

plugins/dashboard_pi/src/wind_history.cpp
plugins/dashboard_pi/src/wind_history.h

fixes FS#1185
Units in Windhistory are now displaying the "global" dashboard units

Bugfix Windhistory units

---

src/chartdbs.cpp

I believe this fixes F.S. 1060.

Prevent grouping charts with similar folder names

---

src/glChartCanvas.cpp

Hi,
Speed up by sleeping less and sending fewer messages to the UI.
Only tested with a 2 cores CPU though.
Regards
Didier

Cache rebuild wall time speed up

---

src/s57chart.cpp

Authored by did-g tested by NahanniV.
Fixes a buserror (alignment?) when loading s57 charts on ARM.

Fix ARM alignment issue

---

include/s52plib.h
include/viewport.h
src/LLRegion.cpp
src/chart1.cpp
src/cm93.cpp
src/glChartCanvas.cpp
src/navutil.cpp
src/options.cpp
src/s52plib.cpp
src/s57chart.cpp
src/viewport.cpp

move cm93 to -180 to 180 coordinates

cm93 fixes

---

plugins/chartdldr_pi/src/chartdldr_pi.cpp

Tag log file entries with plugin name.

Added plugin name tags to log messages.

---

plugins/grib_pi/GRIB.fbp
plugins/grib_pi/po/POTFILES.in
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribUIDialogBase.cpp

Sorry for the mistake; Here without .pot file
JP

Correct grib_pi internationalization

---

include/ocpn_plugin.h
src/pluginmanager.cpp

Set CreateTime on NewSinglewaypoint.
Updates Createtime and IsVisible on UpdateSingleWaypoint.
Removes parameter by reference on &GUID in GetSingleWaypoint (it was being reset by the function).
Get IsVisible and CreateTime on GetSingleWaypoint.
Added IsVisible to PlugIn_Waypoint class.

Plugin Waypoint maintenance

---

src/chart1.cpp
src/toolbar.cpp

The recoverwin was lost when a submerged toolbar was upated or rebuilt.

Recover submerged toolbar

---

include/AIS_Decoder.h
include/options.h
src/AIS_Decoder.cpp
src/options.cpp

This commit add a new option to MMSI properties - Follower. When checked the AIS alert is not activated for that MMSI.
I choose to call it "Follower" instead of "Buddy" to avoid conflicts with GPS-GATE-BUDDY
Please check code and change where appropriate.
Håkan

Add Follower/Buddy to MMSIEditDialog in MMSI properties. Hinder CPA alert

---

src/chart1.cpp

The did not work unless SBDARE was actually displayed.  This patch fixes that and
also simplifies the code.

Fixed ToggleAnchor

---

src/chcanv.cpp

Hi,
Or when panning current arrows and tide scales partially visible
aren't redrawn.
Regards
Didier

Add a marge to the box when selecting which tide and current to draw

---

include/AIS_Target_Data.h
src/AIS_Decoder.cpp
src/AIS_Target_Data.cpp
src/OCPNListCtrl.cpp

- MMSI properties like "No track" is working but AIS-list don't reflects that, still Track = Yes
- Changes in MMSI prop "persistent track" or "VDO ->VDM" wasn't reflected until OCPN closure.
- In AIS-list don't show tracks for BASE or ATON
Please as usual check my coding and correct where appr. 
Thanks.

correct inconsistency between MMSI Properties and AIS list

---

src/compass.cpp
src/glChartCanvas.cpp

Skewed charts shown in chart-up mode had problems. See FS #1904.

Fix uncompensated skewed chart display.

---

include/chcanv.h
src/chcanv.cpp
src/cm93.cpp
src/compass.cpp
src/glChartCanvas.cpp
src/s57chart.cpp

Hi,
Changes to light windows behaviour (compass and piano) may need more testing on windows and with a touch screen,
I have only tested them with linux.
Regards
Didier

fix for some UI glitches

---

include/LLRegion.h
include/ocpn_plugin.h
src/LLRegion.cpp
src/cm93.cpp

Cm93 rendering fixes2

---

src/cm93.cpp
src/s52plib.cpp

Hi,
trivial speedup.
Regards
Didier

Small speedup

---

src/chartimg.cpp
src/s57chart.cpp

Hi,
S57 COVR tables were not freed.
Regards
Didier

Memory leaks in S57

---

src/s57chart.cpp

Hi,
Display S57 object attribute in the dialogue box.
Most of the code was already there.
Regards
Didier

S57 Debug add objects attribute to obj info

---

include/ocpn_plugin.h
src/chart1.cpp
src/pluginmanager.cpp

Add default size to defintion to make consistent with mainline

Continue to work on plugin access to fonts and font colours

---

include/chart1.h
include/options.h
src/chart1.cpp
src/navutil.cpp
src/options.cpp

Implement daily track rotation at configurable time

---

src/glTexCache.cpp

Hi,
lean up a little, remove unreachable code and so on.
Regards
Didier

Load chart cleanup

---

src/chart1.cpp
src/chartimg.cpp
src/glTextureDescriptor.cpp
src/routeprop.cpp
src/s52plib.cpp

Hi,
Small memory leaks and use of unitialised values.
for 777578e I set the pen width to 1 by default, I'm not sure it's the right thing to do.
Regards
Didier

Unitialised and leak

---

include/AIS_Decoder.h
include/options.h
src/AIS_Decoder.cpp
src/options.cpp

First trial to add Ship name to mProp list
Add lookup missed shipname from file
Finalized Lookup MMSI_Prop_ShipName
MMSIprop correct to satisfy Linux

MMSI_prop Add Ships Name to the list

---

plugins/chartdldr_pi/src/chartcatalog.cpp
plugins/chartdldr_pi/src/chartdldr_pi.cpp

Hi,
some patches for improving chartdlr a little.
I don't know if they are worth it.
Regards
Didier

Chartdlr testing

---

plugins/chartdldr_pi/src/chartdldr_pi.cpp

Hi,
We can't edit a not selected catalogue entry, disable the button, same as delete.
Regards
Didier

Disable Edit button if there's no selected catalogue

---

src/s57chart.cpp

There was a memory leak when doing Object Query and sometimes a crash.

Fix rare crash and plug a leak.

---

src/glTexCache.cpp

Hi,
I'm not sure in 100% correct but in my understanding 
if IsCompressedArrayComplete is true and nothing was written in UpdateCacheAllLevels then the cache was already up to date and in the GPU and there's no reason to delete and reload it. ( nCache_Color is not set when reading texture from file).
44cec29 try to queue every uncompressed texture, before they were kept and building the texture cache was taking forever.
Regards
Didier

Raster cache2

---

include/s52s57.h
src/Osenc.cpp
src/s52plib.cpp
src/s57chart.cpp

Hi,
Improve s57 load time:
before (callgrind) Osenc:Ingest
1 000 0000 0000
after
750 000 000
FindBestLUP
before
600 000 000
after
400 000 000
Regards
Didier

S57 speedup

---

src/styles.cpp

Hi,
Fix trivial wx2.8 compilation errors.
Regards
Didier

correct build wx 2.8

---

include/FontMgr.h
src/styles.cpp

This replaces the last pull I put up based on didier's input.

Fix for wxWidgets 2.8 compatability. Needed for ARM

---

src/s57chart.cpp

Hi
This looks like a WiP, there's a debug printf and it doesn't work for cm93 depcnt, ifdef and revert to the old code.
Regards
Didier

DoesLatLonSelectObject if def WIP

---

include/pluginmanager.h
src/pluginmanager.cpp
src/styles.cpp
src/toolbar.cpp

Fix to make PlugIn SVG dim along with rest of toolbar

Fixes to make rollovers work

---

plugins/dashboard_pi/src/dashboard_pi.cpp

hi,
add a missing include for wx2.8
Regards
Didier

wx2.8 compile fix

---

src/chart1.cpp

Hi,
Must not increment index after removing an array element.
Regards
Didier

entry is gone, recheck this index for next entry

---

src/ConnectionParams.cpp

Hi,
these values weren't set for disable connections.
Regards
Didier

Connection unitialised values

---

src/chart1.cpp

Hi,
Apply the selected color scheme to options dialog box. 
Doesn't seem to work very well here, pane background aren't updated but it's not new.
Regards
Didier

options dialog apply color scheme

---

CMakeLists.txt

Beware that I am not very familiar with CMake and therefore doubt that my solution is correct, especially regarding that “BLAH” substitute for unset values; I just post the solution that worked for me.

Add BUNDLE_* to CMake cache (FS#1839).

---

plugins/grib_pi/src/GribOverlayFactory.cpp

Hi
The small texture size doesn't work well with current and wave, example with current  
With the new size (max 1024)
Regards
Didier

increase the size of overlay opengl texture

---

plugins/grib_pi/src/GribReader.cpp
plugins/grib_pi/src/GribUIDialog.cpp

Hi,
make GRB_PRECIP_RATE a synonym of GRB_PRECIP_TOT. 
Regards
Didier

add grib PRECIP_RATE cf FS#1838

---

src/chart1.cpp
src/chcanv.cpp

Hi,
Remove redundant  tests or cc1 usage
Regards
Didier

clean up cc1 usage

---

plugins/grib_pi/src/grib_pi.cpp
src/routemanagerdialog.cpp
src/routeprop.cpp

hi,
always destroy/delete dialog boxes after use or use the stack.
Regards
Didier

Minor dialog box leaks 

---

src/Route.cpp
src/TrackPropDlg.cpp
src/routeprop.cpp

Hi
cf:
[Track width and maybe colour is not changed properly](http://www.cruisersforum.com/forums/f134/opencpn-beta-test-4-2-1706-release-165757-4.html#post2119933)
Need to comb all Refresh(false) calls, if it always needs InvalidGL in openGL mode it'd be factorize in a new function.
Regards
Didier

OpenGL Redraw routes and tracks after user modifications

---

plugins/grib_pi/src/GribV2Record.cpp

hi,
for GRIB2 accumulation record like rain there's a double free error, cleanup and remove it
Regards
Didier

grib2 double free error

---

plugins/grib_pi/src/GribOverlayFactory.cpp
plugins/grib_pi/src/GribRequestDialog.cpp
plugins/grib_pi/src/GribTable.cpp

1)When a zone is drawn, a simple click anywhere in the canvas allow to redraw a new zone
but the current code do not always erase the old zone which can lead to confusion
2) Directions arrows are currently not displayed if no GL mode and "use hight definition graphic" are selected.
3) Files with one time step each hour are not correctly handled in both (Rooiedirk threat in the forum)
Jean Pierre

Correct manual grib zone selection logic & direction arrows display & grib "weather table" date/time logic

---

plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribV1Record.cpp
plugins/grib_pi/src/GribV1Record.h

1) Add .gz in manual file selection and .grib2 & .grb2 in newest file selection
2) Some current files from weather4d/myocean seems to be malformed, with the "GRIB" header starting not at the first, but at the following position. 
I propose here a solution to read successfully these files
Jean Pierre

Complete loading file selection & change logic to read some current files 

---

plugins/grib_pi/src/GribV2Record.cpp

Hi,
Do some bitmaps init only once.
This stuff should be done at compile time though.
Regards
Didier

grib2 speedup getBits

---

plugins/grib_pi/src/GribRecordSet.h
plugins/grib_pi/src/GribRequestDialog.cpp
plugins/grib_pi/src/GribRequestDialog.h
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribV2Record.cpp

Hi
Get ride of small leaks.
Regards
Didier

Grib leaks

---

plugins/grib_pi/src/GribUIDialog.cpp

Hi
If there's no usable record in a file it kill opencpn. 
cf. http://www.cruisersforum.com/forums/f134/open-cpn-4-4-grib2-not-working-for-me-168197.html
with sample grib at:
http://dd.meteo.gc.ca/model_gem_regional/coupled/gulf_st-lawrence/grib2/00/002
the atmosphere files are wind at level 0 not 10 meters and it's not displayed.
Regards
Didier

Grib nodata

---

src/Track.cpp

Hi,
Add a missing initialization.
Regards
Didier

Track uninitialised value

---

src/Track.cpp
src/TrackPropDlg.cpp

Hi,
Fix some regressions with new track code:
- endless loop in route from track function
- a previous fix for an assert was lost.
- compute bearing and speed in tracks properties dialogue box.
Regards
Didier

Track vector

---

src/gshhs.cpp

correct format string

---

plugins/grib_pi/src/GribV2Record.cpp

Hi,
copy and paste from from ucar unpackgrib2.c
Regards
Didier

grib2 add complex packing and spatial differencing

---

include/cm93.h
src/cm93.cpp

This really speeds up cm93 outline rendering a lot.

cm93 outlines2

---

include/chart1.h
src/chart1.cpp

this improves the internal filters quite a bit

Nmea processing2

---

src/AIS_Target_Data.cpp

One new entry in the MID table according to ITU

Update AIS MID table

---

src/s57chart.cpp

Hi,
Each time bCS_Added was set back to 0 it was leaking MPS  memory.
Regards
Didier

free MPS memory when resetting LUPS

---

src/AIS_Decoder.cpp

This patch follow on discussions here:
http://www.cruisersforum.com/forums/f134/ais-not-showing-vessel-names-179617-2.html#post2324612
Short: 
A user claimed some vessels name and more wasn't visible in OCPN but in the transceiver's info box.  We found the vessel was transmitting message ID 19 and only that. The normal would have been 18 and 24-A/B. But no harm to OCPN to decode also mess 19 if this happen again.

Add Class B message ID 19 to AIS decoder

---

plugins/grib_pi/src/GribOverlayFactory.cpp
plugins/grib_pi/src/GribReader.cpp
plugins/grib_pi/src/GribRecord.cpp
plugins/grib_pi/src/GribRecord.h
plugins/grib_pi/src/GribTable.cpp
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribV1Record.cpp
plugins/grib_pi/src/GribV2Record.cpp
plugins/grib_pi/src/TexFont.cpp

Hi,
trivial grib code clean up
Regards
Didier

Grib cleanup

---

include/chcanv.h
src/chcanv.cpp

Hi,
Open popup menu with wx WXK_MENU key, the right menu key on a PC. 
Regards 
Didier

use WXK_MENU for popup menu keyboard shortcut

---

src/AIS_Decoder.cpp

WPL decoding don't work for South and West. "S" or "W" wasn't recognized.

Fix hemisphere S and W decoding for WPL message

---

src/Quilt.cpp

Hi,
For charts in grid like Zeeland S57 it makes the piano nice and tidy rather than random.
Regards.
Didier

sort the piano charts with the same scale top to bottom, left to right

---

src/AIS_Decoder.cpp

Fix ARPA deletion bug at InlandECDIS

---

src/s52plib.cpp

Hi,
Most of them are already displayed as texta object.
Regards
Didier

don't display LNDARE OBJNAM for cm93

---

plugins/grib_pi/src/GribReader.cpp
plugins/grib_pi/src/GribV1Record.cpp
plugins/grib_pi/src/GribV2Record.cpp
plugins/grib_pi/src/grib_pi.cpp

Hi,
need for opening grib files like theses at:
http://nomads.ncep.noaa.gov/pub/data/nccf/com/nam/prod/
Still can't decode multi-grids records so you have to use something like
grib_copy in.grib out.grib
first but it doesn't kill opencpn anymore.
Regards
Didier

various Grib v2 fixes

---

plugins/dashboard_pi/src/clock.cpp
plugins/dashboard_pi/src/clock.h
plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h

Renamed old dashboard clock to "GPS Clock".
Sunrise/Sunset times now are displayed based on local time zone,
but still calculated from GPS data same as always.

Added new dashboard clocks based on GPS local time and CPU local time.

---

plugins/grib_pi/src/GribV2Record.cpp

Hi
This parameter is used by Ocpn grib version 1 decoder, use it with grib version 2 
Regards
Didier

add grib2 wind wave period

---

plugins/dashboard_pi/src/baro_history.cpp
plugins/dashboard_pi/src/baro_history.h
plugins/dashboard_pi/src/clock.cpp
plugins/dashboard_pi/src/clock.h
plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h
plugins/dashboard_pi/src/depth.cpp
plugins/dashboard_pi/src/depth.h
plugins/dashboard_pi/src/dial.cpp
plugins/dashboard_pi/src/dial.h
plugins/dashboard_pi/src/from_ownship.cpp
plugins/dashboard_pi/src/from_ownship.h
plugins/dashboard_pi/src/gps.cpp
plugins/dashboard_pi/src/gps.h
plugins/dashboard_pi/src/instrument.cpp
plugins/dashboard_pi/src/instrument.h
plugins/dashboard_pi/src/rudder_angle.cpp
plugins/dashboard_pi/src/rudder_angle.h
plugins/dashboard_pi/src/wind_history.cpp
plugins/dashboard_pi/src/wind_history.h

It is now possible to have smaller gauges, and the logic is more
efficient and improved when resizing.
Conflicts:
plugins/dashboard_pi/src/clock.cpp

Simplify resize logic, and improve behavior.

---

plugins/grib_pi/src/GribOverlayFactory.cpp

Makes things simpler and fixes the warning and fixes the suspect conditional.

Fix warning and take out the check for clear skies to a helper method + small cleanup

---

include/chcanv.h
src/ais.cpp
src/chcanv.cpp
src/glChartCanvas.cpp

This fixes a previously introduced bug in the predictors rendering, as well as optimizing and simplifying the rendering logic.

Fix predictors

---

plugins/grib_pi/src/jasper/base/jas_cm.c
plugins/grib_pi/src/jasper/base/jas_icc.c
plugins/grib_pi/src/jasper/base/jas_image.c
plugins/grib_pi/src/jasper/base/jas_malloc.c
plugins/grib_pi/src/jasper/base/jas_seq.c
plugins/grib_pi/src/jasper/base/jas_stream.c
plugins/grib_pi/src/jasper/include/jasper/jas_malloc.h
plugins/grib_pi/src/jasper/include/jasper/jas_math.h
plugins/grib_pi/src/jasper/include/jasper/jas_stream.h
plugins/grib_pi/src/jasper/jp2/jp2_cod.c
plugins/grib_pi/src/jasper/jp2/jp2_cod.h
plugins/grib_pi/src/jasper/jp2/jp2_dec.c
plugins/grib_pi/src/jasper/jp2/jp2_enc.c
plugins/grib_pi/src/jasper/jpc/jpc_cs.c
plugins/grib_pi/src/jasper/jpc/jpc_dec.c
plugins/grib_pi/src/jasper/jpc/jpc_enc.c
plugins/grib_pi/src/jasper/jpc/jpc_mqdec.c
plugins/grib_pi/src/jasper/jpc/jpc_mqenc.c
plugins/grib_pi/src/jasper/jpc/jpc_qmfb.c
plugins/grib_pi/src/jasper/jpc/jpc_t1enc.c
plugins/grib_pi/src/jasper/jpc/jpc_t2cod.c
plugins/grib_pi/src/jasper/jpc/jpc_t2cod.h
plugins/grib_pi/src/jasper/jpc/jpc_t2dec.c
plugins/grib_pi/src/jasper/jpc/jpc_t2enc.c
plugins/grib_pi/src/jasper/jpc/jpc_tagtree.c
plugins/grib_pi/src/jasper/jpc/jpc_util.c

Hi,
Backport jpeg2000 Jasper changes from Debian, mostly dealing with corner cases and bogus memory allocation.
Regards
Didier

merge from latest debian code

---

include/s57chart.h
src/s52plib.cpp
src/s57chart.cpp

hi,
lazy load s57 thumb data, make loading vector charts a little faster .
Regards
Didier

S57 thumbnail

---

src/AIS_Bitstring.cpp
src/chart1.cpp
src/glTextureManager.cpp
src/routemanagerdialog.cpp
src/s52plib.cpp

Hi,
Speed stuff a little.
Regards
Didier

Trivial cleanup

---

plugins/grib_pi/src/jasper/base/jas_stream.c
plugins/grib_pi/src/jasper/include/jasper/jas_image.h
plugins/grib_pi/src/jasper/include/jasper/jas_math.h

Hi,
Missing inline definition for Windows.
May be wait for a SIZE_MAX fix before merging.
Regards
Didier

C __inline def for MSC

---

include/options.h
src/chart1.cpp
src/navutil.cpp
src/options.cpp

Came to a boat here with only GGA sentences available in the system (And not brave enough to even touch the cabling around the multiplexer). This patch should provide a reasonable calculated replacement for the missing COG/SOG data in such situations.

Implement user selectable SOG/COG calculation from position data.

---

include/chcanv.h
src/Select.cpp
src/chcanv.cpp
src/glChartCanvas.cpp

This is behaving like the existing rollover windows for routes.
I am working on a "fleet tracking" module for which I originally developed this feature.  But I think that having a popup window for tracks is useful on it's own.

Added rollover window for tracks

---

src/chcanv.cpp

Reasonably accurate for medium and longer track segments.

added SOG to track rollover window

---

vagrant/README
vagrant/Vagrantfile

To help having more developers, I've created a simple Vagrantfile which allow newcomers to automatically spawn a VM with all dependencies set.

Added Vagrantfile (debian/jessie64) which builds and run opencpn.

---

.travis.yml

Hi
Add libarchive for gshhs download to travis configuration file
Regards
Didier

add libarchive to travis

---

.travis.yml

Hi,
add LibLZMA & Libexif in Travis CI
Regards
free-x

fix for Travis CI

---

src/chart1.cpp
src/chcanv.cpp

Hi,
It needs more testing on Mac and Windows but on my Linux box the new ETA was truncated and opengl FPS wasn't displayed anymore.
Regards
Didier

right size for status bar fields

---

include/concanv.h
src/concanv.cpp

Would make the Route dlg like this:

Show ETA date and TTG days to route dlg if TTG > 24h

---

include/chcanv.h
include/gshhs.h
include/ocpn_plugin.h
src/gshhs.cpp
src/pluginmanager.cpp

Implements http://www.cruisersforum.com/forums/f134/weather-routing-100060-85.html#post2556866

Extend the plugin API with functions providing min/max available basemap quality

---

include/Osenc.h
src/Osenc.cpp

Hi
speedup osenc reading by not doing small temporary allocations.
Regards
Didier

Osenc speedup

---

include/options.h
src/DetailSlider.cpp
src/chcanv.cpp
src/options.cpp

Improve the UI tab in Toolbox

---

plugins/grib_pi/src/GribTable.cpp
plugins/grib_pi/src/GribTable.h

Hi 
small leak fix lost after pull request #976
Regards
Didier

Gribtable Memory leak

---

include/options.h
src/AISTargetQueryDialog.cpp
src/TrackPropDlg.cpp
src/about.cpp
src/chart1.cpp
src/options.cpp
src/routemanagerdialog.cpp
src/routeprop.cpp

Freeing my buffer, filling the O5 one...
Fixes asserts produced by wx3.1 in several dialogs.

Fix several sizer related asserts

---

src/chart1.cpp

Before didn't report guid, and reported errors for all the routes that were not the right one!

correct route and track messages so they can actually be used by plugins

---

include/glChartCanvas.h
src/AIS_Decoder.cpp
src/NavObjectCollection.cpp
src/Osenc.cpp
src/chart1.cpp
src/chartdb.cpp
src/chartimg.cpp
src/chcanv.cpp
src/glChartCanvas.cpp
src/options.cpp
src/routeman.cpp
src/viewport.cpp

Hi,
trivial cleanup and make some assumptions  explicit, mostly from coverity report.
Should change nothing to code behavior, but there's true corner case bugs. 
Regards
Didier

Coverity cleanup

---

plugins/dashboard_pi/src/dashboard_pi.cpp

This change should allow closing this task.
Signed-off-by: Rasbats

FS#2094 - True Wind Dir. & Speed does not indicate above 199 degrees TWD

---

plugins/dashboard_pi/src/dashboard_pi.cpp

App and True wind angle in Dashboard now shows the correct TWA (again!).

FS#2094 - True Wind Dir. Return code to state prior to pull request 993.

---

.travis.yml
vagrant/Vagrantfile

Hi,
here a small fix for building mbtiles support at Travis and Vagrant
Regards
free-x

Fix deps for compiling mbtiles support

---

CMakeLists.txt
include/mbtiles.h
src/mbtiles.cpp

and fix build on macOS by using the embedded copy of sqlite3

Improve handling of mbtiles with missing or wrong metadata

---

src/SQLiteCpp/include/SQLiteCpp/Database.h
src/SQLiteCpp/src/Backup.cpp
src/SQLiteCpp/src/Database.cpp
src/SQLiteCpp/src/Statement.cpp
src/mbtiles.cpp

Reorder includes so Database.h can tell if the define is needed

---

src/canvasMenu.cpp

Hi,
cf  https://opencpn.org/flyspray/index.php?do=details&task_id=2366
try to display menu of displayed rollover windows, AID, route, track and so on.
Regards
Didier

display AIS menu first, fs #2366

---

src/chcanv.cpp

Hi,
Trivial but i % 1 always returns 0.
Don't know if it matters just draw a slightly different  circle.
Regards
Didier

typo in ChartCanvas::JaggyCircle

---

src/NavObjectCollection.cpp
src/canvasMenu.cpp
src/routeman.cpp

Hi,
You can kill Opencpn by deleting a track or a route if its property dialog box is open.
Regards
Didier

Trk rte dialog

---

include/chartbase.h
src/chartimg.cpp
src/glChartCanvas.cpp
src/glTextureManager.cpp

Fixes the issue reported by phiggins in http://www.cruisersforum.com/forums/f134/opengl-dooes-not-work-199603.html

Fix the texture cache purge logic to correctly identify charts.

---

plugins/dashboard_pi/src/dashboard_pi.cpp
src/chart1.cpp

Confine heading to 0-360 after application of magnetic variance.

---

include/s52plib.h
src/s52plib.cpp

Hi,
Textures memory  is a finite resource, O or the computer eventually hang if they aren't freed
Regards
Didier

s52plib factorization and memory leak

---

src/chart1.cpp

Fixes an invalid memory access revealed by address sanitizer.
Xlib API is confusing - it returns 8/16/32 for sizes - which
means "byte", "sizeof(short)" and "sizeof(long)". The last
one was treated a 32-bits and pointers were copied into a
5 byte buffer.
However the whole copy was unnecessary because xlib already
zero-terminates strings for us. Refactor code a little bit
while fixing this.

chart1.cpp: Fix get_X11_property

---

src/glTexCache.cpp
src/glTextureManager.cpp

Hi,
this is https://github.com/OpenCPN/OpenCPN/pull/1084 for 4.99
Regards
Didier

Gl texture

---

plugins/grib_pi/src/GribV1Record.cpp

Hi
with a free account you have access to 0.5 EMCWF grib but it's grib v1 with bogus parameters, adjusted them to values expected by grib record. 
Regards
Didier

add free predictwind EMCWF grib

---

include/Layer.h
include/Route.h
include/Track.h
include/routemanagerdialog.h
src/AISTargetQueryDialog.cpp
src/AIS_Decoder.cpp
src/NavObjectCollection.cpp
src/Track.cpp
src/TrackPropDlg.cpp
src/chart1.cpp
src/chcanv.cpp
src/kml.cpp
src/navutil.cpp
src/pluginmanager.cpp
src/routemanagerdialog.cpp
src/trackprintout.cpp

Implement filtering in the route and waypoint manager

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h

Note, the inches/centimeters selection has been reversed as compared to the core understanding of units for a long time. Fixed in this PR. Probably this has never been noticed since almost no one uses these units in anger.

Add depth offset feature to Dashboard

---

include/chart1.h
src/chart1.cpp
src/chcanv.cpp

Hi,
- only test charts in the active group (help when there's a lot of charts).
- add  'p' as a toggling test pause key.
add a unit_test_2 parameter, test_1 display a small viewport, test_2 try to display the whole chart, it's brutal, currently oesenc charts pass test_1 but fail test_2 on opengl leak.
Regards
Didier

Unit test 2

---

src/glChartCanvas.cpp
src/glTextureManager.cpp
src/options.cpp
src/pluginmanager.cpp

Hi
backport stuff from 4.8.4
I folded some patches.
I don't understand  0c1f1c3 anymore...
Translation updates not included. (never look at translation workflow and I don't understand it either)/
Regards
Didier

V4.8.4 backport

---

include/TexFont.h
plugins/chartdldr_pi/src/chartdldr_pi.cpp
plugins/grib_pi/src/GribReader.cpp
plugins/grib_pi/src/GribUIDialog.cpp
src/Quilt.cpp
src/Track.cpp
src/chart1.cpp
src/chartimg.cpp
src/chcanv.cpp
src/pluginmanager.cpp
src/routemanagerdialog.cpp

Hi,
a bunch  of small fixes  (mostly from coverity), most visible is TexFont ie it's not in O plugins contract but sometimes  it could be declared public and used by plugins.
Regards
Didier

Small fixes

---

plugins/grib_pi/GRIB.fbp
plugins/grib_pi/src/CursorData.cpp
plugins/grib_pi/src/GribOverlayFactory.cpp
plugins/grib_pi/src/GribSettingsDialog.cpp
plugins/grib_pi/src/GribSettingsDialog.h
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribUIDialogBase.cpp
plugins/grib_pi/src/GribUIDialogBase.h

Hi,
- Display one decimal digit.
- Add an option for displaying abbreviated pressure number (last two digits).
- GRIB.fbp is out of sync with generated file but it's still useful so try to reduce a little diff between what it generates and what's actually in tree.
output sample:
Regards
Didier

Grib pressure

---

appveyor.yml

Hi,
re enable appveyor after they changed something.
no idea if poedit actually works though.
Regards
Didier

appveyor peoedit install

---

data/svg/MUI_flat/MUI_follow_active.svg

Change MUI Auto follow icon to green symbol

---

src/ConfigMgr.cpp
src/cm93.cpp
src/options.cpp
src/routeman.cpp
src/wxsvg/src/svgxml/svgxml.cpp

No functions are changed. The main goal is to get proper log file readings.

Correct/harmonize file path separators.

---

src/multiplexer.cpp

See also http://www.cruisersforum.com/forums/f134/trying-to-hookup-gps-st60-s3g-st6002-icom-m234g-and-brookhouse-208139.html

Allow VHF with onboard GPS to send a position nmea sentence

---

include/ocpn_plugin.h
include/pluginmanager.h
src/canvasMenu.cpp
src/pluginmanager.cpp

Hi,
Currently plugins can only add entries  to O main context menu, do it for all menus. waypoint, route and track.
Bump API version to 16 with.
Regards
Didier

Plugins menu

---

include/chcanv.h
include/ocpn_plugin.h
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribUIDialog.h
plugins/grib_pi/src/grib_pi.cpp
src/pluginmanager.cpp

Hi,
- Ability for plugins to request routes, tracks and waypoints by GUID.
- Json message for requesting grib data at time/lat/lon.
Regards
Didier

Plugins export route

---

include/NavObjectCollection.h
include/RoutePoint.h
include/routeprop.h
src/NavObjectCollection.cpp
src/RoutePoint.cpp
src/Select.cpp
src/canvasMenu.cpp
src/chart1.cpp
src/chcanv.cpp
src/navutil.cpp
src/routemanagerdialog.cpp
src/routeprop.cpp
src/undo.cpp

Adding a Scamin property to waypoints. Also add it to the property dialog and do a cleanup of this dialog.
(Sorry Dave my git refuses to join those commits to 1)

Up ma scamin

---

src/navutil.cpp

Add ° for degrees, ' for minutes, " for seconds.

FIX coordinates print in status bar

---

plugins/grib_pi/src/GribRecord.cpp
src/RolloverWin.cpp

No functional charges, one tiny step for less warnings.

Fix misleading indentation pointed out by gcc

---

src/AIS_Decoder.cpp

There has been a bug in the mmsi_properties implementation. In all versions up to now a deletion or change of a mmsi number in the list, did not effect the corresponding ais_data_objects. (Data was only set for numbers IN the list, but not reset again if mmsi was removed from list)

Let mmsi-props also reset settings if mmsi-no changed or deleted.

---

src/options.cpp

Moved the checkboxes on how to handle waypoint routes to routes panel

Move wpt control from Options-Display to Options->Routes/Waypoints

---

include/RoutePoint.h
src/RoutePoint.cpp
src/Select.cpp

Fixing bug in selecting of waypoints. 
Waypoints where not added to selectable points list if ScaMin was < chartscale.
Logic error in my own code:-)

Correct selecting waypoints at < scamin

---

src/AIS_Decoder.cpp
src/AboutFrame.cpp
src/RoutePropDlgImpl.cpp
src/chart1.cpp
src/navutil.cpp

I came across some strings in the Pot file that to my opinion should NOT be translated.
Please do double check.

Some Strings that should Not be translated altered

---

include/TCDS_Ascii_Harmonic.h
include/TCDS_Binary_Harmonic.h
include/TCDataFactory.h
src/TCDS_Ascii_Harmonic.cpp
src/TCDataFactory.cpp

+ Get rid of one old wx style vector
+ Change known_units from per-instance mutable to const static and initialize in a nicer fashion
+ Result is shorter and cleaner

Clean up some tide&current code removing spurious allocations etc

---

src/canvasMenu.cpp
src/chart1.cpp
src/chcanv.cpp

Preventing the popup warning for making an invisible new waypoint if not needed.
(See email Hakan)

Prevent ScaMin warningmessage if new waypoint IS visible

---

CMakeLists.txt
include/MswSound.h
src/MswSound.cpp
src/SoundFactory.cpp
src/SystemCmdSound.cpp

Some conflicts in CMakeLists, see my notes in top on how my thinking is (for better or worse...)
Otherwise a new MswSound, by default enabled on WIN32

Sound: Add new windows sound backend, cleanup.

---

plugins/grib_pi/src/GribV2Record.cpp

Hi,
Grib format is baroque, it's not mandatory that forecast time and interval time are using the same unit, actual time used being forecast + interval.
Convert them to the same unit if in hour or minute.
We need to fix time handling though. O is using grib1 semantic for historical reason but you can't map 100% grib2 semantic to grib1.
Regards
Didier

decode more valid Grib file.

---

include/RoutePoint.h
src/MarkInfo.cpp
src/NavObjectCollection.cpp
src/RoutePoint.cpp
src/RoutePropDlg.cpp
src/navutil.cpp
src/pluginmanager.cpp

Hi,
Trivial errors, valgrind, rendering glitches and trying to propose a somewhat valid file name on export, weather routing is using date in name track,  locale dependent but  ':' or '/' are likely.
Regards
Didier

Route track

---

src/Select.cpp

Hi
You can kill Opencpn by hiding tracks/routes/waypoints with the V key and right clicking next to an isolated waypoints.
Regards
Didier

Isolated waypoint are not associated with a route

---

include/s57RegistrarMgr.h
include/s57chart.h
src/chart1.cpp
src/s57RegistrarMgr.cpp
src/s57chart.cpp
src/s57mgr.cpp

Was going through the S57 code trying to understand it for new feature development. 
Ended up cleaning things a little bit. This has no functional changes

s57chart mini cleanup

---

CMakeLists.txt
config.h.in
include/ChartDataInputStream.h
src/ChartDataInputStream.cpp
src/chartimg.cpp
src/glTexCache.cpp
src/options.cpp

optimizations and fixes

---

include/NavObjectCollection.h
include/chart1.h
src/NavObjectCollection.cpp
src/chart1.cpp
src/routemanagerdialog.cpp

Hi,
This is 
FS#2083 - GPX easy import with a double click on the file, commabd line parameter or drag & drop
If there's 
- a single wpt don't change zoom factor center the view.
- multiple wpt or routes zoom to the bounding box and center view.
Implementation side effect: make opencpn a single instance (pipe is in opencpn directory)
Regards
Didier

Snsm load file

---

plugins/grib_pi/src/GribReader.cpp
plugins/grib_pi/src/GribRecord.cpp
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribV2Record.cpp

Hi,
and use them if there's no UOGRD, VOGRD records.
you can get sample files at:
http://176.31.74.196/POLAR
Regards
Didier

Grib add current polar record type.

---

include/chartdbs.h
src/chart1.cpp
src/chartdbs.cpp
src/chcanv.cpp
src/navutil.cpp
src/options.cpp

Convert ChartGroup m_elem_array to stdlib

---

src/s52cnsy.cpp

Hi,
Use the right test as defined in S52 3.2 and 4.0 
Regards
Didier

OBSTRN Area conditional symbology

---

CMakeLists.txt
ci/docker-build-mingw.sh
mingw/fedora/README.md

While we are on it: Delete leftover message from dropped RPM generation.
Closes: #1380

build: mingw: Adjust compiler flags.

---

CMakeLists.txt
ci/travis-build-osx.sh
src/pluginmanager.cpp
src/toolbar.cpp

Fix FTBS as reported in #1396. While we are on it, fix the last warnings in the linux/gcc build (with current flags).

Issue 1396

---

ci/travis-build-mingw.sh
ci/travis-build-osx.sh
libs/sound/src/PortAudioSound.cpp
src/options.cpp

Sound: Fix memory leak + portaudio close issue (#1441)

---

ci/appveyor-upload.sh
ci/generic-upload.sh

Also: Remove some unused sourceforge upload cruft.

ci: Update to new cloudsmith deployment repo

---

CMakeLists.txt

Fix: https://github.com/OpenCPN/OpenCPN/issues/1524#issue-538498833

Add extra lib dir for armhf-stretch to CmakeList

---

src/download_mgr.cpp

Some basics before going into bug-hunt mode...
- Lock the width of the description widget after failed attempts
to make the wrapping work when resizable.
- Add missing Sizer
- Move buttons out of the scrolling window
Closes: #1516

download_mgr: Bugfixes and clean up 

---

libs/mipmap/src/mipmap.c
libs/wxcurl/src/base.cpp
plugins/grib_pi/src/GribReader.cpp
plugins/grib_pi/src/GribRecord.h
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/GribV2Record.cpp
src/RoutePropDlgImpl.cpp
src/pluginmanager.cpp
src/printtable.cpp
src/routeprintout.cpp

hi,
Backport patches from V5.0.x
Regards,
Didier

V5.0.x backport

---

src/MarkInfo.cpp
src/chart1.cpp

Remove some stuff from heap at exit

Remove wxAssert warning

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h
plugins/dashboard_pi/src/depth.cpp
plugins/dashboard_pi/src/dial.cpp

Dashb. Add watchdog to Wind, Depth and STW data.

---

src/pluginmanager.cpp

pluginmanager: Don't display required plugin API level.

---

src/pluginmanager.cpp
src/semantic_vers.cpp

Try to solve #1530  Prints version  major.minor and if API >= 117: version major.minor.patch

Print plugin version instead of API in Options Plugins

---

include/PluginHandler.h
src/PluginHandler.cpp
src/download_mgr.cpp

- Make a better job reporting errors from download/install
- Clean up after failed installs.

Error fixes

---

CMakeLists.txt
cmake/uninstall.cmake.in

Build: cmake: Add uninstall target (#1531).

---

src/catalog_mgr.cpp
src/download_mgr.cpp

Update plugin list after catalog update.

---

plugins/dashboard_pi/src/dashboard_pi.cpp

Prevent XDR "C" ENV_WATER_T to infect "C" AirTemp

DB: Correct $++XDR AirTemp logic

---

CMakeLists.txt
cmake/CompilerSupport.cmake
cmake/dummy.c
libs/mipmap/CMakeLists.txt
libs/texcmp/CMakeLists.txt

Closes: #1657 
While we are on it: Some cleanup in CMakelists after the big Android merge.

Issue 1657: Fix fragile optimization flags, CMakeLists cleanup

---

INSTALL

typos in INSTALL

---

src/chart1.cpp

Addresses https://opencpn.org/flyspray/index.php?do=details&task_id=2647

Make status bar font match user UI options selected font and color

---

src/AIS_Decoder.cpp
src/ais.cpp

SignK AtoN data: 
Add Nav status Aton Real and Virtual.
Add value altitude (for Aircraft)

SK: AtoN completions

---

src/chcanv.cpp

Previously was allowed only on left or "main" canvas

Allow track rollover on any canvas

---

.travis.yml

Fix a glitch caused by #1758 and #1759 both were based
on master.

ci: travis.yml: Fix merge glitch.

---

src/SignalKEventHandler.cpp

It seems somehow some incomplete update was merged into OpenCPN.
Apologies.

Use LOG_DEBUG for SignalKEventHandler

---

flatpak/org.opencpn.OpenCPN.yaml

Fix leftover from merging of logging branch. Too simple PR to justify filing an issue.

flatpak: Build master branch, not log.

---

src/OCPNPlatform.cpp

My bad: I checked the regular build instead of the flatpak one
before making the PR. This should clean up the situation.

Flatpak: fix FTBS caused by 5b74a16bf.

---

include/SignalKDataStream.h
include/SignalKEventHandler.h
src/AIS_Decoder.cpp
src/SignalKDataStream.cpp
src/SignalKEventHandler.cpp

SK: Delete double pTargetData hash update
Signalk, add connection query string to avoid cached data at init.

SK: Update query string. Include GPL to new SignalK files

---

src/ais.cpp

Oops. Another false trigg detected. An undefined SOG has a value.

AIS realtime prediction. Do not activate at no reported SOG

---

src/chcanv.cpp

1) add data (RNG, TTG, ETA) to the end point of the selected leg when the route is active in the routeleginforollover
2) correct typo

Improve leginfo rollover

---

src/AIS_Decoder.cpp

Added a new case for AIS message 27.
AIS message 27 i a long range AIS position report.

Added support for AIS message 27. Long range position report.

---

src/ais.cpp

Would solve issue: https://github.com/OpenCPN/OpenCPN/issues/1915#

AIS realtimePred SOG limit decreased

---

plugins/chartdldr_pi/src/chartdldr_pi.cpp
plugins/chartdldr_pi/src/chartdldr_pi.h
plugins/chartdldr_pi/src/chartdldrgui.cpp
plugins/chartdldr_pi/src/chartdldrgui.h

Consider this a draft PR that improves performance when a single catalog has large (hundreds) of chart titles.  All comments welcome.  Testing on Linux (RPi 4) & Windows 10.

Chart downloader optimization

---

src/pluginmanager.cpp

As heading says: since #1971 has shown that the magic calculation is a possible problem, add som debug logging.

pluginmanager: Add host/plugin magic logging (#1971).

---

plugins/dashboard_pi/src/compass.cpp

Another GPS compass style at watchdog timeout

Edit of Dashb; Blank GPS compass at Watchdog timeout

---

.circleci/config.yml

Fix flatpak nightly builds (#2000).

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/depth.cpp

Would solve this bug report:
https://www.cruisersforum.com/forums/f134/dashboard-bug-with-signalk-237695.html#post3196677

Dashboard - SignalK: Depth double value check and add depth from surface

---

src/PluginHandler.cpp

modified:   src/PluginHandler.cpp

Fix broken compile for arm64 (check on plugin arch)

---

src/chcanv.cpp

Simplify code and correct chart selection at AutoFollow zoom function

---

ci/generic-build-macos.sh

Basically fixes for problems described in #2049 
XCode is updated to 11.0, modern enough to avoid the python2 dep (but still not that modern that it exposes CPack bugs when using for example 11.3).
The dependencies are cached, and the build now completes in about 15 minutes instead of 25. Still not "fast", but better. The cache ins invalidated when ci/generic-build-macos.sh is changed.
Libraries used are properly linked to the executable so that CPack can pick them up.
Remove various hacks for library inclusion and chmod.
EDIT: Drop the travis macos builder, use circleci instead. Circleci builds in about half the time, 15 minutes vs 30. 
Closes: #2049

Macos builder: Performance , bugfixes.

---

src/mbtiles.cpp

Prevents crash with some mbtiles charts.

Initialize local zoom level variables.

---

plugins/dashboard_pi/src/dashboard_pi.cpp

May not make a big impact on optimization but why do things in vain.

DB-Don't parse NMEA sentenses if not used by prioritization

---

src/multiplexer.cpp

There should be no errors reading device links besides when we
try to read what's actually not a link. At a minimum, such situations
should be logged se we can get a hint what's going on.
While on it, simplify the fix for the terrible bug where  target isn't null-terminated.

Be a little conservative multiplexer::do_readlink() -- follow up to  a22a89f 

---

plugins/dashboard_pi/src/nmea0183/dpt.cpp
plugins/dashboard_pi/src/nmea0183/sentence.cpp

Handle case where minus '-' is buried in the float string

Move Navico bug fix to all doubles in NMEA message

---

src/s57chart.cpp

Simplify S57 chart boundaries by ignoring points too close

---

plugins/dashboard_pi/src/clock.cpp
plugins/dashboard_pi/src/dashboard_pi.cpp
src/chart1.cpp

Fixes issue https://github.com/OpenCPN/OpenCPN/issues/1961

Dashboard: No GNSS time display if no GNSS fix available

---

plugins/dashboard_pi/src/dashboard_pi.cpp

A new PR instead of rebase the old one.

DB: Correct calculated wind direction.  True wind unit fix.

---

plugins/grib_pi/src/GribOverlayFactory.cpp

Hi 
Trivial but it seems  feathers should be on the low-pressure side and we get it wrong.
Regards
Didier

Arrows feathers are on the low-pressure side of the wind direction

---

plugins/dashboard_pi/src/baro_history.cpp
plugins/dashboard_pi/src/baro_history.h
plugins/dashboard_pi/src/clock.cpp
plugins/dashboard_pi/src/clock.h
plugins/dashboard_pi/src/compass.cpp
plugins/dashboard_pi/src/compass.h
plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h
plugins/dashboard_pi/src/depth.cpp
plugins/dashboard_pi/src/depth.h
plugins/dashboard_pi/src/dial.cpp
plugins/dashboard_pi/src/dial.h
plugins/dashboard_pi/src/from_ownship.cpp
plugins/dashboard_pi/src/from_ownship.h
plugins/dashboard_pi/src/gps.h
plugins/dashboard_pi/src/instrument.cpp
plugins/dashboard_pi/src/instrument.h
plugins/dashboard_pi/src/rudder_angle.cpp
plugins/dashboard_pi/src/rudder_angle.h
plugins/dashboard_pi/src/speedometer.cpp
plugins/dashboard_pi/src/speedometer.h
plugins/dashboard_pi/src/wind.cpp
plugins/dashboard_pi/src/wind.h
plugins/dashboard_pi/src/wind_history.cpp
plugins/dashboard_pi/src/wind_history.h

Dashboard: Allow "unlimited" number of instrument types in future

---

include/plugin_cache.h
src/cat_settings.cpp
src/plugin_cache.cpp

Add some info on cache size and a Clear Cache button, the bottom panel in screenshot:
Closes: #1829

Add  cache feedback and a Clear Cache  button (#1829)

---

src/Osenc.cpp

Some IENC charts (Slovakia) contain extremely complex vector features with thousands of points
This leads to a very deep recursion in `DouglasPeucker` algorithm and a crash.
Add a preprocessing step using a naive pre-simplification procedure skipping proportional part of the points
regardless of their distance assuming that in an extremely complex shape with thousands of edges the probablity
of removing a significant feature is very low.

Presimplify vector features before DuglasPeucker

---

src/s57chart.cpp

s57chart: Move old debug message into log file

---

src/AIS_Target_Data.cpp

Include class SART SOG and COG to AIS Traget Query

---

ci/circleci-build-flatpak.sh
ci/generic-build-flatpak.sh
flatpak/README.md
flatpak/org.opencpn.OpenCPN.yaml
org.opencpn.OpenCPN.yaml

Update build scripts and docs after runtime update.
Circleci logs [here](https://app.circleci.com/pipelines/github/leamas/OpenCPN/1488/workflows/595953c6-0edd-47f5-a508-99d8dedaa1bd/jobs/2641)
Closes: #2342

flatpak: Update build for new runtime version (#2342).

---

include/macutils.h
src/macutils.c
src/ser_ports.cpp

ser_ports.cpp: Fix fatal typo (#2358).

---

include/Route.h
include/routeman.h
src/Route.cpp
src/chcanv.cpp
src/routeman.cpp

Tested under Windows 10 and Linux (Ubuntu), not on Android.

Merging and combining routes

---

plugins/dashboard_pi/src/dashboard_pi.cpp

There were hard coded sizes in the choice box dropdowns.  Some displays did not show any text making it hard to know what was selected.

Optimize dashboard dialog choice box sizing for any size display

---

CMakeLists.txt
ci/circleci-build-flatpak.sh

Fix strange conditions for including a Microsoft header. While on it, mute some noise in the build logs.
Closes: #2394 
Circlce build logs [here](https://app.circleci.com/pipelines/github/leamas/OpenCPN/1594/workflows/cf4193ad-3a27-4a7c-b335-61a5fb0bb8e6) and [here](https://app.circleci.com/pipelines/github/leamas/OpenCPN/1593/workflows/03367b91-2dce-42cb-8807-0b689e48b5fb)

CI: flatpak: Fix FTBFS

---

src/about.cpp
src/ais.cpp
src/chcanv.cpp

Fix the two uninitialized variables as of #2411. While on it, do some formatting clean-up in src
EDIT: again: Need to include  5afe535 in order to rebase the PR, see #2406. 
Closes: #2411

Chcanv.cpp, src: Fix uninitialized vars, formatting cleanup.

---

plugins/grib_pi/src/GribOverlayFactory.cpp

Hi,
I missed triangle in my previous patch

Triangle feathers are on the low-pressure side of the wind direction

---

src/pluginmanager.cpp

pluginmanager.c: Plug memory leak (#2485).

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/gps.cpp
src/SignalKEventHandler.cpp

Add SK delta gnss.type from N2k

---

data/s57data/chartsymbols.xml

Correct a small typo in chartsymbols.xml

Corrext typo in chartsymbols

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/cmake.yml
ci/github-pre-build.sh
ci/github-win_deps.bat
ci/macos-deps

Implement Github Actions CI and issue templates

---

.github/workflows/cmake.yml
ci/control

I hope the change to ci/control needed for Bionic does not break the CircleCI builds, let's see.

Add Bionic builder support to Github Actions.

---

CMakeLists.txt

This ensure it uses the wx-config tools provided in the CMake module.

Use CMake module wx-config utility

---

.github/workflows/flatpak.yml
ci/github-build-flatpak.sh
flatpak/org.opencpn.OpenCPN.yaml

While on it, fix an updated zlib link in the flatpak manifest.
Closes: #2638

Ci: Add  Flatpak build to the PR job run by github

---

include/AIS_Decoder.h
include/ais.h
src/AISTargetListDialog.cpp
src/AIS_Decoder.cpp
src/ais.cpp
src/canvasMenu.cpp
src/chcanv.cpp
src/options.cpp
src/pluginmanager.cpp

Ideally it would own its AIS_Target_Data values as unique_ptr's, but
that's somewhat complex without access to std::optional in a few
places, which would require C++17.

Convert AIS_Target_Hash to std::unordered_map, and store it inline.

---

include/Osenc.h
src/Osenc.cpp

As an aside, why does this function even need to be locked at all?

Fix useage of std::mutex and lock guards.

---

CMakeLists.txt
plugins/chartdldr_pi/src/chartcatalog.cpp
plugins/chartdldr_pi/src/chartcatalog.h
plugins/chartdldr_pi/src/chartdldr_pi.cpp
plugins/chartdldr_pi/src/chartdldr_pi.h
plugins/chartdldr_pi/src/chartdldrgui.h

Note that this is much more convenient if we can move up to C++14
as the C++ version, which gets us access to make_unique.

Replace wx arrays and cleanup object lifetimes, preventing leaks.

---

CMakeLists.txt

#2699 contained some garbage. I should have seen it. Sorry for the mess

CMakeLists: bugfix for #2699

---

include/AIS_Decoder.h
src/AIS_Decoder.cpp
src/ConfigMgr.cpp
src/ais.cpp
src/navutil.cpp
src/options.cpp

This reverts commit eba04da0bb09741f5966cd918043d9885beaff31.

Revert "Eliminate a wxArray and manage object lifetimes automatically."

---

src/ais.cpp

Also increase helicopter size. (Due to a previous user request)
Attempt to solve this [Flyspray](https://opencpn.org/flyspray/index.php?do=details&task_id=2825&opened=378&type%5B0%5D=&sev%5B0%5D=&due%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&reported%5B0%5D=)

Scale navstatus and SAR aircraft icons 

---

include/Osenc.h
src/Osenc.cpp

Revert commit 6771c95c1d2d2df53619e7677b331fb9b26b3c1e

Revert "Fix usage of std::mutex and lock guards."

---

INSTALL

- Add appropriate links to the manual.
- Update GTK2 requirement to GTK3.
- Update WxWidgets requirement to 3.0.0.
- Use generic Debian build dependency installation.
- Remove unsupported mingw instructions.
Closes: #2706

Update INSTALL documentation (#2706).

---

plugins/dashboard_pi/src/dashboard_pi.cpp

Sorry - forgot to include in last GNSS status patch. /H

GNSS status. Add extra BeiDou talker also for SignalK-data

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h

Since Dashboard now have Altitude instruments we may include also SignalK data to them.

DB: Include SignalK value with Altitude instruments

---

include/datastream.h
src/datastream.cpp
src/multiplexer.cpp

In response to https://github.com/OpenCPN/OpenCPN/issues/2736

Core/plugins accept bad NMEA checksums if requested.

---

src/observable.cpp

The basic assumption is that having two listeners with the same (window, messagetype) is an error.
However, all class level listeners are initiated using a temporary listener which is assigned to the class listener. During this window there are two listeners with the same (window, messagetype). The situation is rectified when the automatic variable goes out of scope.
For now, make the checks for duplicate listeners aware of this situation and only log actual duplicates after unlisten() i. e., after the temporary variable destructor. This should catch possible "real" duplicates. Also log when there are more than two instances.
These checks are somewhat expensive, only run in debug mode.
This mess is a consequence of using value semantics for the listener rather than the original …

observable: Clean up error detection

---

plugins/dashboard_pi/src/dashboard_pi.cpp

Seen a couple of absurd GNSS status SNR staples.

DB: Protect from bad satellite SNR values

---

include/AISTargetListDialog.h
src/AISTargetListDialog.cpp

As discussed here: https://github.com/OpenCPN/OpenCPN/discussions/2788

Add button & function Center-Info-close to AIS Target List

---

include/comm_appmsg.h
include/ocpn_plugin.h
libs/observable/include/observable.h
src/comm_plugin_api.cpp

Implements missing pieces in the plugin API: GetListener() and GetEventNavdata().

Plugin api: Implement the missing pieces

---

plugins/dashboard_pi/src/depth.cpp

DB: Fine tune depth graph. Bottom text space

---

plugins/dashboard_pi/src/altitude.cpp

Last(?) fix to Dashboard for scaled Windows

DB: Tune Altitude graph for scaled display

---

src/ais.cpp
src/pluginmanager.cpp

AIS details are a trade-off to fit different system. This PR tested on Win and Debian. Hopefully Mac is satisfied as well.

AIS Win scale

---

src/plugin_handler.cpp

plugin_handler: Accept darwin-wx32 plugins (#2875)

---

.github/workflows/cmake.yml
libs/garmin/CMakeLists.txt

This should close #2870, but we need to check the ci build for this PR first.
EDIT: 
Closes: #2870

Garmin 2870

---

libs/gtest/CMakeLists.txt

libs/gtest: Fix gtest FTBFS problems on Debian/Ubuntu (#2894).

---

libs/gdal/include/gdal/cpl_config.h
plugins/grib_pi/libs/jasper/src/include/jasper/jas_config.h.in

Clear explicit, unconfigured #undefs (#2896)

---

CMakeLists.txt
opencpn-cmd.1

As heading says: Add missing, rudimentary opencpn-cmd manpage

Add opencpn-cmd.1 manpage

---

src/nav_object_database.cpp

Intends to solve this CF [post](https://www.cruisersforum.com/forums/f134/opencpn-version-5-7-1-beta-test-1-a-271518-5.html#post3726720)

Correct exported gpx file header

---

plugins/dashboard_pi/src/dashboard_pi.cpp

(cherry picked from commit c2411de14b2191cffb1edcd27f1c97c65a9a89f4)

Stop DB COG compass from spinning wildly every time DB preferences closed

---

plugins/grib_pi/src/GribOverlayFactory.cpp
plugins/grib_pi/src/GribRequestDialog.cpp
plugins/grib_pi/src/grib_pi.cpp
plugins/grib_pi/src/pi_TexFont.cpp
plugins/grib_pi/src/pi_ocpndc.cpp

By using API function to get Win DIP factor

Rationalize font sizing for MSW

---

include/SendToPeerDlg.h
include/peer_client.h
include/routemanagerdialog.h
src/REST_server.cpp
src/SendToPeerDlg.cpp
src/nav_object_database.cpp
src/peer_client.cpp
src/routemanagerdialog.cpp

Make it possible to send multiple objects at once from the Route & waypoint manager.

Implement sending tracks and waypoints to peer instances.

---

include/SendToPeerDlg.h
include/peer_client.h
src/REST_server.cpp
src/SendToPeerDlg.cpp
src/peer_client.cpp

- Show transfer progress
- Ask for PIN before the actual transfer begins
- Show information also after successful transfer
Should address all the concerns raised in https://github.com/OpenCPN/OpenCPN/issues/2988
With very large tracks even the GPX generation can take time, but we would have to refactor it significantly to be able to report progress there.

Improve the object sending implementation

---

plugins/dashboard_pi/src/dashboard_pi.cpp

DB: Win scale of Preferences dialogs.

---

src/canvasMenu.cpp

A minor patch to make te right-click popup menu text same as the routemanger text

Uniform text Sent to Peer

---

src/ocpn_app.cpp
src/plugin_loader.cpp

-safe_mode just does not work as intended. Fix that.
This does not close #3038, but streamlines the remaining issue.

plugin_loader et. al.: Make sure safe_mode works as intended (#3038).

---

plugins/grib_pi/src/GribRequestDialog.cpp

As ZyGrib has "momentary" blocked the function, I just deactivate the option in the grib request.
Also, I added the option to get ECMWF model grib from Saildoc

Grib_pi Deactivate ZyGrib and add ECMWJ model option

---

include/tcmgr.h
src/ConfigMgr.cpp
src/OCPNPlatform.cpp
src/androidUTIL.cpp
src/navutil.cpp
src/ocpn_app.cpp
src/ocpn_frame.cpp
src/options.cpp
src/tcmgr.cpp

Sanitize the harmonic data while loading and slightly improve performance

Prevent loading duplicate harmonic datasets

---

src/ocpn_frame.cpp

This intend solve issue: #3098
I've no Mac to test on. Compared to other keys this the only difference I can see.

Correct keycode W for MacOs

---

libs/s52plib/src/mygeom.cpp
libs/s52plib/src/s52plib.cpp
libs/s52plib/src/s52s57.h
src/TCDS_Ascii_Harmonic.cpp
src/TCDS_Binary_Harmonic.cpp
src/glTextureManager.cpp

Fixes a few low hanging memory leaks reported by address sanitizer

Fix memory leaks

---

src/REST_server_gui.cpp

Only three digits was shown on my 17" screen. Strange GetCharWidth()?

Fix for RPi; Truncated (Send to peer) server PIN textctrl

---

src/canvasMenu.cpp

Update canvas menu CPA alarm text

---

include/comm_drv_n0183_serial.h
include/comm_drv_n2k_serial.h
include/comm_drv_signalk_net.h
include/garmin_protocol_mgr.h

As described in #3122, basically  a no-brainer.
The open question is if there are similar things in other parts of the code.

Use atomic_int for thread synchronization (#3122).

---

include/comm_drv_n2k_serial.h
src/comm_drv_n0183_serial.cpp
src/comm_drv_n2k_socketcan.cpp
src/connections_dialog.cpp

drivers: Add missing `#include "config.h"` (#3138)

---

src/chcanv.cpp

Correct rounding of bearing/course in route hoover popup box.
[https://www.cruisersforum.com/forums/f134/open-cpn-inconsistent-with-paper-charts-274303.html#post3761328](url)

Round the bearing shown in routehooverpopup

---

src/pluginmanager.cpp
src/svg_utils.cpp

Protect against possible havoc while loading SVG files with undefined size

---

manual/modules/ROOT/pages/linux.adoc

A few trivial updates to the linux build instructions

Slightly update the Linux build instructions

---

src/nav_object_database.cpp

Correct the creation timestamp for waypoints and route points to be UTC as expected

---

opencpn.1

Update manpage with new plugin load paths.
Closes: #3267

opencpn.1: Update, notably new plugin load paths. (#3267)

---

src/ais.cpp

Adjust ARPA target for scaled display

---

src/ais_decoder.cpp

Update catch of mmsi properties for a temporary lost AIS target

---

src/plugin_loader.cpp

Fixes for windows problems in #3374 caused by the need for system plugin metadata in the catalog.

plugin_loader: Fixes for #3374 problems.

---

src/REST_server.cpp

REST_server: Fix confusing message (#3333).

---

src/catalog_handler.cpp
src/console.cpp

opencpn-cmd: Update for new import 

---

src/console.cpp

opencpn-cmd: Fix initialization of GetPrivateDataDir et. al. (#3384)

---

plugins/grib_pi/src/email.cpp

grib_pi: Fix shell syntax invoking xdg-email (#3445)

---

CMakeLists.txt
data/opencpn.appdata.xml.in

Isn't GPDS supposed to be [GPSD](https://gpsd.gitlab.io/gpsd/)?

CMakeLists.txt and opencpn.appdata.xml.in: change GPDS to GPSD

---

buildwin/winConfig.bat

Update winConfig.bat to use latest wxWidgets
Fix also a small typo

Update wxWidgets version to 3.2.3

---

libs/mDNS/CMakeLists.txt
libs/mDNS/src/mdns_util.cpp

mDNS: Hack printf statements to become wxLogDebug (#3466)

---

src/ais_decoder.cpp

Make explicit type declarations for shared_ptr

Fix order of rapidjson includes

---

CMakeLists.txt
include/NMEALogWindow.h
include/REST_server.h
include/REST_server_gui.h
include/SendToGpsDlg.h
include/comm_n0183_output.h
include/garmin_wrapper.h
include/multiplexer.h
include/n0183_ctx_factory.h
include/nmea_log.h
include/route_gui.h
include/route_point_gui.h
include/routeman.h
src/REST_server_gui.cpp
src/SendToGpsDlg.cpp
src/comm_n0183_output.cpp
src/console.cpp
src/garmin_wrapper.cpp
src/multiplexer.cpp
src/ocpn_app.cpp
src/ocpn_frame.cpp
src/route_gui.cpp
src/route_point_gui.cpp
src/routeman.cpp

This is next part of #3106 focusing on the garmin upload parts. I don't really have the environment to test this, the compiler is my only tool here,  so the changes are not aggressive. Still, if someone with with the tools in place could test it would be great.

Replace "#ifdef CLIAPP" with callbacks, part 2 (#3105)

---

src/SendToPeerDlg.cpp

SendToPeerDlg: Fix bad alignment (#3512)

---

src/AISTargetListDialog.cpp
src/OCPNListCtrl.cpp
src/ais_decoder.cpp
src/ais_target_data.cpp

Fix after appreciated test user comments around.

AIS_Meteo: Don't obscure prioritized targets

---

CMakeLists.txt
include/ais_decoder.h
include/peer_client.h
include/route.h
include/route_point.h
include/routeman.h
include/safe_mode.h
include/safe_mode_gui.h
include/waypointman_gui.h
src/AISTargetAlertDialog.cpp
src/ais.cpp
src/ais_decoder.cpp
src/ais_info_gui.cpp
src/androidUTIL.cpp
src/console.cpp
src/ocpn_app.cpp
src/ocpn_frame.cpp
src/peer_client.cpp
src/rest_server.cpp
src/route_point_gui.cpp
src/routeman.cpp
src/safe_mode.cpp
src/safe_mode_gui.cpp
src/waypointman_gui.cpp
test/CMakeLists.txt
test/n2k_tests.cpp
test/tests.cpp

Accidentally gui-depending code has been added to route and route_point instead of route_gui and route_point_gui. This has created a dependency mess effectively blocking #3513.
Move the GL, gui-related code to appropriate _gui components and try to get it working again...
Closes: #3533

Route gui 3533

---

gui/src/AISTargetQueryDialog.cpp

As well as BASE station likewise unnecessary.

Disable Track button on Meteo AIS target query

---

plugins/dashboard_pi/src/dashboard_pi.cpp

Based on this [CF discussion](https://www.cruisersforum.com/forums/f134/which-nmea-sentence-for-heel-instrument-276972.html#post3795988)

D-board N0183 XDR ROLL and PITCH less selective match.

---

gui/src/ConfigMgr.cpp
gui/src/TCWin.cpp
gui/src/navutil.cpp
gui/src/ocpn_app.cpp
gui/src/ocpn_frame.cpp

This reverts commit 7813cbfc64061696986f8b77e51442d9165fa4ca.
Conflicts:
gui/src/ocpn_app.cpp
gui/src/ocpn_frame.cpp
EDIT: discussed in https://github.com/OpenCPN/OpenCPN/commit/7813cbfc64061696986f8b77e51442d9165fa4ca#commitcomment-137426077

Revert "ocpn_app, ocpn_frame: Remove unused junk, part 1"

---

CMakeLists.txt
libs/SQLiteCpp/CMakeLists.txt
libs/easywsclient/CMakeLists.txt
libs/garmin/CMakeLists.txt
libs/gdal/CMakeLists.txt
libs/geoprim/CMakeLists.txt
libs/glshim/CMakeLists.txt
libs/iso8211/CMakeLists.txt
libs/libtess2/CMakeLists.txt
libs/mDNS/CMakeLists.txt
libs/mongoose/CMakeLists.txt
libs/nmea0183/CMakeLists.txt
libs/serial/CMakeLists.txt
libs/ssl_sha1/CMakeLists.txt
libs/texcmp/CMakeLists.txt
libs/wxJSON/CMakeLists.txt
libs/wxcurl/CMakeLists.txt
libs/wxservdisc/CMakeLists.txt

Some low hanging fruits in the #3527 mess, clearing some libs completely from evil dependencies.

Libs: First stab on #3527

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h

Add depth Type: D Name: XDHI and XDLO. Optimize conditions. Narrow air pressure condition.
Add Air pressure priority
"Simplify" is for e.g. Air temp look for "AIR" instead of a number of precise expressions: "AirTemp", "TempAir"

D-board XDR: Simplify Airtemp and rudder angle conditions.

---

libs/N2KParser/src/N2KParser.cpp
plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h
plugins/dashboard_pi/src/instrument.h
plugins/dashboard_pi/src/nmea0183/mda.cpp
plugins/dashboard_pi/src/nmea0183/mda.hpp

Add MDA humidity
Humidity: add N2k and SK parser
Based on discussions: #3447, #3613 and CF Dashboard.
Note: New N2k parser not tested. No PGN130313 available here.

D-board Add Humidity instrument and parse XDR sentence

---

model/src/comm_drv_signalk_net.cpp
model/src/linux_usb_watch.cpp

As heading says. tested on Linux.
Closes: #3618

signalK network driver: restart after a suspend -resume cycle (#3618)

---

gui/src/ais.cpp
gui/src/canvasMenu.cpp
gui/src/chcanv.cpp

Code to draw a rectangle area notice. No code found for this.
NOTE: After monitoring a worldwide aishub.net feed no Ais8_1_22 area notices have been observed.
Simulated NMEA recording to test this PR:
[ais8_1_22.rect.txt](https://github.com/OpenCPN/OpenCPN/files/14261967/ais8_1_22.rect.txt)

AIS8_1_22_SHAPE_RECT

---

gui/src/pluginmanager.cpp
model/include/model/plugin_loader.h
model/src/plugin_loader.cpp

For some reason the code handling the imports seems to have bitrot, cannot really understand why. Not a point fix, but not that bad.
Closes: #3690

plugin_manager, plugin_loader: Fix broken imports (#3690)

---

model/include/model/ais_target_data.h
model/include/model/meteo_points.h
model/src/ais_decoder.cpp
model/src/ais_target_data.cpp

Now the SK team has kindly updated SK servers to version 2.6 including meteo data. This PR complies to that SK update.

SignalK AIS: implement METEO data. Fixes #3541

---

gui/src/ais.cpp
gui/src/canvasMenu.cpp
gui/src/chcanv.cpp
model/src/ais_decoder.cpp
model/src/comm_ais.cpp

and fix some related bugs in AIS area message handling
Closes #3713

Add support for the old US format of AIS area messages (8/366/22)

---

glutil/CMakeLists.txt

See https://github.com/OpenCPN/OpenCPN/issues/3759

Move glutil MSVC artifacts to local runtime folders

---

plugins/dashboard_pi/src/wind_history.cpp
plugins/dashboard_pi/src/wind_history.h

Wind History graph: Fix clash for present data values and statistics

---

gui/src/chcanv.cpp
gui/src/ocpn_frame.cpp

Before make a hard copy to paper hide the toolbars (and some other overlaystuff)

Hiding toolbars before printing to paper

---

gui/src/glChartCanvas.cpp
gui/src/ocpn_frame.cpp

This make the hiding of toolbars also working for OpenGL. At least it is  for me using debian.

Hide Toolbars while printing for glChartcanvas

---

libs/garmin/jeeps/garmin_wrapper_utils.c
model/include/model/garmin_protocol_mgr.h
model/src/garmin_protocol_mgr.cpp
model/src/navutil_base.cpp
plugins/grib_pi/src/CursorData.cpp
plugins/grib_pi/src/GribSettingsDialog.cpp
plugins/grib_pi/src/grib_pi.h
plugins/wmm_pi/CMakeLists.txt

Remove some duplicated defintions revealed using `-flto=4`.
EDIT: Closes: #3782

Remove duplicated definitions (#3782)

---

gui/include/gui/options.h
gui/src/options.cpp

As per request on this [CF-post](https://www.cruisersforum.com/forums/f134/beta-test-technical-30929-191.html#post3891539)

Add user speed unit to Options: "Default boat speed"

---

gui/include/gui/wiz_ui_proto.h
gui/src/initwiz/wiz_ui.cpp
gui/src/initwiz/wiz_ui_proto.cpp

@nohal You did start this. I filled the rest if you don't mind :)

First time Wiz: Add Wind speed unit

---

gui/src/chcanv.cpp

Also save key 'R' no radar ring to config. Closes #3916

---

model/src/comm_drv_n2k_net.cpp
model/src/comm_drv_n2k_serial.cpp

Invalid handling caused DLE ETX pair in middle of message to stop data reading. Specially this was problematic with position messages.

Fixed Actisense format ESC handling

---

model/src/ais_decoder.cpp

Closes #3921
Also clean out old code not used anymore.

Add condition for the optional "Use WPL position report...."

---

model/src/ais_target_data.cpp

Correct country code for MMSI Mid > 900

---

gui/include/gui/OCPNPlatform.h
gui/include/gui/shapefile_basemap.h
gui/src/shapefile_basemap.cpp

Fixes https://github.com/OpenCPN/OpenCPN/issues/3925

Fix Windows debug builds

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dial.cpp
plugins/dashboard_pi/src/dial.h
plugins/dashboard_pi/src/speedometer.cpp

D-board Adjust extra STW appearance on SOG-Speedometer

---

plugins/dashboard_pi/src/dashboard_pi.cpp

Intend to resolve this [CF issue](https://www.cruisersforum.com/forums/f134/android-radar-plugin-and-missing-data-on-signalk-287183.html#post3911601):

Add true wind calculation if missing from SignalK

---

plugins/dashboard_pi/src/dashboard_pi.cpp

DB: Add STW speedometer

---

plugins/dashboard_pi/src/wind_history.cpp

Dashboard Wind history graph. User requests for further customization of heading text with statistical data

D-board: Wind hist: Adapt the status text to actual size

---

buildwin/winConfig.bat

Adds the retrieval of quick start to local Windows builds.

Add the quick start manual to local builds.

---

buildwin/winConfig.bat

Use latest URL for quickstart
Clean local folder before unzipping

Local Build: Update to new Quickstart manual download URL.

---

manual/modules/ROOT/pages/create-deb-package.adoc

New section on publishing an existing release.

manual: Update debian package handling [skip ci]

---

libs/libdnet/CMakeLists.txt

libdnet: handle ninja FTBFS (#4117)

---

gui/src/ais.cpp
model/include/model/ais_target_data.h
model/src/ais_decoder.cpp
model/src/ais_target_data.cpp

To implement what's discussed here: https://github.com/OpenCPN/OpenCPN/discussions/3998#discussioncomment-10912019
Plenty of buoys available here: 153.44.253.27  ::  5631

Implement class AIS_BUOY for net buoys

---

plugins/demo_pi_sample/src/nmea0183/RMB.hpp
plugins/demo_pi_sample/src/nmea0183/RMC.HPP
plugins/demo_pi_sample/src/nmea0183/Response.hpp
plugins/demo_pi_sample/src/nmea0183/gsv.cpp
plugins/demo_pi_sample/src/nmea0183/gsv.hpp
plugins/demo_pi_sample/src/nmea0183/nmea0183.cpp
plugins/demo_pi_sample/src/nmea0183/nmea0183.h
plugins/demo_pi_sample/src/nmea0183/nmea0183.hpp
plugins/demo_pi_sample/src/nmea0183/response.cpp
plugins/demo_pi_sample/src/nmea0183/rmb.cpp
plugins/demo_pi_sample/src/nmea0183/rmc.cpp
plugins/demo_pi_sample/src/nmea0183/rte.cpp

Rebasing of #4171 to re-apply PR checks

Updates to #4171

---

gui/src/hotkeys_dlg.cpp
model/src/mDNS_query.cpp
model/src/mDNS_service.cpp
model/src/std_serial_io.cpp
test/tests.cpp

This fixes warnings not in the lib directory on OSX.

Fix non-lib warnings on OSX.

---

plugins/dashboard_pi/src/dashboard_pi.cpp
plugins/dashboard_pi/src/dashboard_pi.h

Not tested on Mac or Android. Please anyone.

Customize the right size of a Dashboard after instrument changes

---

gui/include/gui/pluginmanager.h
include/ocpn_plugin.h
model/include/model/comm_drv_n2k_serial.h
model/include/model/plugin_comm.h
test/tests.cpp

This PR adds code documentation for the plugin API, specifically for NMEA/SignalK message handling.

Improve code comments for NMEA/SignalK plugin API

---

gui/include/gui/shapefile_basemap.h
gui/src/shapefile_basemap.cpp

Fix #4237 
OpenCPN crashes with a segmentation fault when closing the application while shapefile data is still being loaded asynchronously. The crash occurs in the `ShapeBaseChart` destructor because there is no proper cleanup handling for in-progress async loading operations.
1. Added `CancelLoading()` method to `ShapeBaseChart `to safely stop async operations
1. Ensures async operations complete before cleanup in destructors
1. Added checks for cancelled loading throughout the `LoadSHP()` process
The fix prevents the crash by ensuring proper cleanup of resources when the application exits, even if shapefile loading is in progress.

Fix seg fault when deleting chart while chart is asynchronously loading

---

gui/include/gui/RoutePropDlgImpl.h
gui/include/gui/TrackPropDlg.h
gui/src/RoutePropDlg.cpp
gui/src/RoutePropDlgImpl.cpp
gui/src/TrackPropDlg.cpp
plugins/grib_pi/src/GribOverlayFactory.cpp

1. Add code comments for date/time formatting.
2. Create constants for time formatting.
The purpose of this PR is to make smaller changes in preparation for #4052

Add code comments. Minor refactor improvements

---

gui/include/gui/MarkInfo.h
gui/include/gui/dialog_cntrl.h
gui/src/MarkInfo.cpp
gui/src/chcanv.cpp
gui/src/dialog_cntrl.cpp
gui/src/routemanagerdialog.cpp
manual/Doxyfile

Improved and documented method to set and reset text field validator.

Fix set and reset validator.

---

android/androidUTIL.cpp
gui/src/AISTargetAlertDialog.cpp
gui/src/ais.cpp
plugins/grib_pi/src/CursorData.cpp
plugins/grib_pi/src/GribOverlayFactory.cpp
plugins/grib_pi/src/GribRequestDialog.cpp
plugins/grib_pi/src/GribUIDialog.cpp
plugins/grib_pi/src/grib_pi.cpp
plugins/grib_pi/src/grib_pi.h
plugins/wmm_pi/src/wmm_pi.cpp

This PR fixes the problem identified by @Hakansv at https://github.com/OpenCPN/OpenCPN/pull/4296#issuecomment-2644203597

Use font size as defined by the system or customized by user.

---

model/src/ais_decoder.cpp

Intent to solve the bug reported on the [CF](https://www.cruisersforum.com/forums/f134/signal-k-implementation-228038-15.html#post3971595)

Correct interpretation of signalk AIS design.draft

---

android/androidUTIL.cpp
gui/include/gui/ocpn_frame.h
gui/src/ocpn_app.cpp
gui/src/ocpn_frame.cpp
libs/gui/include/dialog_alert.h
libs/gui/include/dialog_base.h
libs/gui/include/field_text.h
libs/gui/include/ui_utils.h
libs/gui/src/dialog_alert.cpp
libs/gui/src/dialog_base.cpp
libs/gui/src/ui_utils.cpp

Refactored navigation warning dialog to use AlertDialog from the UI library.
As part of this change the PR introduces method `AddHtmlContent` to the dialog base class for HTML content. And the `ShowModal` method was refactored into the dialog base class.

Navigation warning using UI AlertDialog.

---

gui/src/compass.cpp

Tested on various Win and Debian

Increase the compass button TenHz indicator to fit on different screens

---

gui/include/gui/options.h
gui/src/navutil.cpp
gui/src/options.cpp
model/include/model/ais_decoder.h
model/src/ais_decoder.cpp

Add own ship MMSI to options Own Ship. Don't use that as an AIS target

---

include/ocpn_plugin.h

The purpose of this PR is to document all available OpenCPN plugin APIs. Everything in `ocpn_plugin.h` should now be documented.
There is no functional change.

Document OpenCPN plugin APIs

---

gui/include/gui/chcanv.h
gui/include/gui/viewport.h
gui/src/chcanv.cpp
gui/src/glChartCanvas.cpp
gui/src/viewport.cpp
include/ocpn_plugin.h
libs/geoprim/src/bbox.h

This PR improves the handling of coordinate transformations between screen pixels and geographic coordinates, with particular focus on the ViewPort class and its integration with ChartCanvas. It addresses issues with mouse coordinate tracking and viewport bounding box calculations.
1. Enhanced documentation for ViewPort and ChartCanvas classes, clearly defining their responsibilities in coordinate transformations.
2. Improved SetBoxes() function with documentation explaining the bounding box calculation algorithm.
3. Fixed mouse coordinate tracking to use canvas-relative coordinates instead of screen-wide coordinates.
4. Added detailed documentation for cursor position variables, clarifying when they're updated and how they should be used.
5. Updated API documentation to consistently use …

Fix mouse coordinates for the ViewPort.

---

buildwin/winConfig.bat

Strengthen the process of getting updates from wxWidgets GitHub repository when building locally on Windows

Strengthen wxWidgets updates from GitHub

---

gui/src/RoutePropDlg.cpp
model/include/model/route.h
model/include/model/route_point.h

1. Add tooltips to the Route Properties dialog to clarify how distances and times are calculated within the route system.
2. Add code comments.

Add tooltips and code comments for routes.

---

plugins/wmm_pi/src/GeomagnetismHeader.h
plugins/wmm_pi/src/GeomagnetismLibrary.c

- Remove the unused `MAG_readMagneticModel_Large` function
- Fix format string in `MAG_robustReadMagModels`
Closes #4475

Get rid of warnings in NOAA WMM library

---

model/src/multiplexer.cpp

Fix bug where input messages was discarded as soon as the DataMonitor was hidden
Closes: #4493

multiplexer: Don't discard messages when DM is inactive - 4493

---

libs/gui/src/dialog_base.cpp

Resolve #4473 with extra width for HTML content.

Resolve unintended scrollbar with extra width - #4473.

---

include/ocpn_plugin.h

Update some code comments according to #4242 discussions.

ocpn_plugin.h: Update comments - #4242

---

include/ocpn_plugin.h
manual/modules/ROOT/nav.adoc
manual/modules/ROOT/pages/coding-guidelines.adoc
manual/modules/ROOT/pages/plugin-api.adoc
manual/modules/ROOT/pages/plugin-messaging.adoc
model/include/model/route_point.h

PR #4459 was merged then reverted in https://github.com/opencpn/OpenCPN/commit/4af8de2fd53 because of issue https://github.com/Rasbats/shipdriver_pi/issues/608
This PR takes the documentation part of #4459
This is a doc-only PR. No code changes.

Add plugin API documentation.

---

gui/src/canvasMenu.cpp

Here's my attempt at resolving https://github.com/OpenCPN/OpenCPN/issues/4096 . Let me know if any changes are needed and I'll update.

Show Navigate to Here in main menu when layer waypoint selcted #4096

---

plugins/dashboard_pi/src/dashboard_pi.cpp

Dashboard wind data PGN 130306  have multiple variables that can come from different source so the current source priority may sort out the desired data.
See this CF post for issue identification and discussion: https://www.cruisersforum.com/forums/f134/no-wind-direction-info-288599.html#post3993098.
This change is tested by simulation, thanks to @TwoCanPlugIn. For next test we will ask the CF user identifying this issue.

DashB PGN130306 Wind. Remove source prioritization and simplify

---

gui/include/gui/chcanv.h
gui/src/options.cpp
include/ocpn_plugin.h

While troubleshooting #4437, I made a few flyby enhancements and fixes:
1. Add tooltips for AIS options.
2. Fix plugin API code comments.
3. Add code comments.

AIS tooltips and code comments

---

gui/include/gui/ais.h
gui/src/AISTargetListDialog.cpp
gui/src/OCPNListCtrl.cpp

add flag column in ais target list so now it's look

Add flag column in ais target list #4534 

---

model/src/comm_drv_n0183_net.cpp
model/src/navobj_db.cpp
po/POTFILES.in

These changes now show up in a pot-file test. Hope everyone is happy.

Add missing translations

---

gui/include/gui/connections_dlg.h
gui/src/connections_dlg.cpp

New CLion version produces much more diagnostics. Fix these, update comments and fix the not updated disabled state.
Closes: #4575

Connections dialog: More clean up, fix #4575

---

buildwin/winConfig.bat

Fixes https://github.com/OpenCPN/OpenCPN/issues/4689

Eliminate redundant xcopy operations when backing up nav database

---

plugins/wmm_pi/CMakeLists.txt

Attempt to get a reasonable license for  a CMakeLists.txt.
@nohal : Could you please review and eventually merge? This is about your copyright, it's better if you do it.

wmm_pi: clean up license

---

gui/include/gui/MarkInfo.h
gui/include/gui/TrackPropDlg.h
gui/src/MarkInfo.cpp
gui/src/RoutePropDlgImpl.cpp
gui/src/TrackPropDlg.cpp
gui/src/ocpn_frame.cpp
gui/src/ocpn_plugin_gui.cpp
model/include/model/hyperlink.h
model/src/hyperlink.cpp
model/src/nav_object_database.cpp
model/src/navobj_db.cpp
model/src/route_point.cpp

Get rid of   `WX_DECLARE_LIST(Hyperlink, HyperlinkList)` and friends. We don't like them.

hyperlink: Get rid of a WX_DEFINE_LIST

---

android/androidUTIL.cpp
gui/include/gui/Quilt.h
gui/include/gui/navutil.h
gui/src/MarkInfo.cpp
gui/src/Quilt.cpp
gui/src/RoutePropDlgImpl.cpp
gui/src/canvas_menu.cpp
gui/src/chcanv.cpp
gui/src/concanv.cpp
gui/src/gl_chart_canvas.cpp
gui/src/kml.cpp
gui/src/navutil.cpp
gui/src/ocpn_frame.cpp
gui/src/ocpn_plugin_gui.cpp
gui/src/route_gui.cpp
gui/src/routemanagerdialog.cpp
gui/src/waypointman_gui.cpp
model/include/model/nav_object_database.h
model/include/model/route.h
model/include/model/route_point.h
model/include/model/routeman.h
model/include/model/track.h
model/src/comm_n0183_output.cpp
model/src/garmin_wrapper.cpp
model/src/nav_object_database.cpp
model/src/navobj_db.cpp
model/src/route.cpp
model/src/route_point.cpp
model/src/routeman.cpp
model/src/select.cpp

route, routepoint: Get rid of two WX_DEFINE_LIST and friends

---

android/androidUTIL.cpp
gui/include/gui/navutil.h
gui/src/RoutePropDlgImpl.cpp
gui/src/canvas_menu.cpp
gui/src/chcanv.cpp
gui/src/concanv.cpp
gui/src/gl_chart_canvas.cpp
gui/src/kml.cpp
gui/src/mark_info.cpp
gui/src/navutil.cpp
gui/src/ocpn_frame.cpp
gui/src/ocpn_plugin_gui.cpp
gui/src/route_gui.cpp
gui/src/routemanagerdialog.cpp
gui/src/waypointman_gui.cpp
model/include/model/nav_object_database.h
model/include/model/route.h
model/include/model/route_point.h
model/include/model/routeman.h
model/include/model/select_item.h
model/include/model/track.h
model/src/comm_n0183_output.cpp
model/src/garmin_wrapper.cpp
model/src/nav_object_database.cpp
model/src/navobj_db.cpp
model/src/route.cpp
model/src/route_point.cpp
model/src/routeman.cpp
model/src/select.cpp
model/src/select_item.cpp

No functional changes expected.

WX_DEFINE_LIST:  Remove last WX_DEFINE_LIST in model

---

gui/src/tooltip.cpp

This should fix issue reported by @transmitterdan in #4051 
@transmitterdan , what steps did you follow? Did this happen while closing a window or something else? I think this should fix the problem, but ideally I would reproduce the same steps.

Fix tooltip crash
